### ISSUE TITLE
【BUG】用户在个人中心进行重置密码，页面跳转后，提示接口异常

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#1003]
**用文字描述你遇到的问题**

用户进行登陆后，在个人中心，进行密码重置，跳转到密码重置后，显示接口调用异常

**重现方法**

<img width="960" alt="企业微信截图_1686189293222" src="https://github.com/TencentBlueKing/bk-user/assets/49228807/f973b23f-b7f2-4d78-85e8-0f11acb4f654">
<img width="910" alt="企业微信截图_16861893591893" src="https://github.com/TencentBlueKing/bk-user/assets/49228807/cfc6e9aa-7456-4ab3-baa7-dcae74c7ba7e">

**预期行为**

无异常，且对密码，做强度校验

**版本**
- 提供用户管理的具体版本号
- 2.5.2
- 是否是企业版问题？
- 是

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by neronkl** [comment]
经排查接口`api/v1/web/passwords/settings/by_token/?token={}`，是提供给忘记密码进行密码重置功能进行密码强度检测使用的。
从个人中心进行重置密码，无token提供，因此调用失败。

**Comment by neronkl** [comment]
修复方案：
1. 前端通过解析cookie，获取用户名的domain
2. 通过domian，获取对应目录的密码设置

增加一个接口
`api/v1/web/passwords/settings/by_domain/?domain={}`

**Comment by nannan00** [comment]
1. 与前端确认 [无登录态下忘记密码后重置密码] /reset_password 和 [登录态下修改密码]/change_password 这两个页面是否共用了部分逻辑，比如拉取密码配置(密码强度要求、加密传输要求等) api/v1/web/passwords/settings/by_token/

2. 确定共用，则调整 api/v1/web/passwords/settings/by_token/ 后台API，支持token 和 登录态两种方式获取密码相关配置
- 优先Token，无Token则使用登录的用户（无Token需要与前端确认好，而不是现在的传递undefined）
- 登录态如何获取可以参考 passwords/modify/ 这个后台API的处理

**Comment by Xmandon** [comment]
2.5.4
