### ISSUE TITLE
蓝鲸6.1 ldap新创建的用户，在权限中心无法添加到用户组里边

### ISSUE THREAD

**Issue by 627465423** [TencentBlueKing/bk-user#1006]
蓝鲸6.1 ldap新创建的用户，在权限中心无法添加到用户组里边
使用蓝鲸新创建账号正常。新添加的ldap用户不能正常添加权限

请求第三方API错误: request iam error! Request=[http_post /api/v1/web/subject-members request_id=3286b59a4a884cdda6fc10eee27ba9ad] Response[code=1901500, message=system error[request_id=3286b59a4a884cdda6fc10eee27ba9ad]: [Handler:BatchAddSubjectMembers] svc.BulkCreateSubjectMembers type=`group` id=`5` members=`[{Type:user ID:test123@wanyu.com Name:}]` policy_expired_at=`1717656608` => [SubjectSVC:BulkCreateSubjectMembers] memberPKMap type=`user`, id=`test123@wanyu.com` fail => [Raw:Error] member don't exists pk] (REMOTE_REQUEST_ERROR)

![image](https://github.com/TencentBlueKing/bk-user/assets/25541938/0e7bf78a-df3c-4266-8237-f06673af4ffc)

**Comment by nannan00** [comment]
这需要在权限中心同步组织架构，用户管理与权限中心的数据同步时一天一次，并不是实时获取或同步的
