### ISSUE TITLE
登录的中英切换可以记住用户上次选择态

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#1007]
<img width="913" alt="企业微信截图_b6ff0b38-a520-4638-a58b-ab3a9b378908" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/b655a0bc-34ce-45f8-a942-ac704328c1a2">
现在登录态失效后，回到这个登录态都会变成“中文”，能不能维持失效前的选项？

**Comment by nannan00** [comment]
无法支持，因为无登录态，无法知道之前的状态
