### ISSUE TITLE
fields接口的职务require返回为false，与后台实际逻辑不一致（后台逻辑为必填）

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#1008]
**重现方法**
用户编辑页面，清空默认的职务字段值后保存，会触发下图所示异常：
![image](https://github.com/TencentBlueKing/bk-user/assets/90179140/27d79ed5-2164-4bf3-8f9b-5a6a112765cd)

**预期行为**
如果require字段显示该字段为非必填，那清空保存时不该报错

**版本**
最新版本仍旧存在该问题

**额外信息**
fields接口返回的职务（position）字段的required值为false（代表非必填），实际进行编辑的时候，清空职务字段的默认值后进行提交会报错
=》这里如果确认职务非必填，应该修改后台逻辑，接受职务值为空

**Comment by Canway-shiisa** [comment]
接口：PUT /api/v1/web/profiles/<int:id>
逻辑调整思路：
后台接收空position的传入
1. 入参序列化器ProfileUpdateInputSLZ 增加职务（position字段）：`position = serializers.CharField(required=False, allow_null=True, allow_blank=True)`
2. 增加position对应的校验：当position为空字符串的时，转换成None值，否则将position转换成整型：position = int(position)

**Comment by nannan00** [comment]
> 接口：PUT /api/v1/web/profiles/int:id 逻辑调整思路： 后台接收空position的传入
> 
> 1. 入参序列化器ProfileUpdateInputSLZ 增加职务（position字段）：`position = serializers.CharField(required=False, allow_null=True, allow_blank=True)`
> 2. serializer增加position对应的校验：当position为空字符串的时，转换成None值，否则将position转换成整型：position = int(position)
>    @nannan00

实现时, 主要是否Db保存支持None，还是说有什么默认值

**Comment by Canway-shiisa** [comment]
这个问题沟通确认后：前端进行调整，如果用户清空职务字段后保存，前端传递null值到后台（不传递字符串类型）
【后台负责验证两种场景：
1.传递null值，是否DB能正确保存
2.不传递position字段，表示该值不做更新，是否维持原值
】

**Comment by Canway-shiisa** [comment]
2.5.4中修复
