### ISSUE TITLE
多租户-admin功能部分

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#1043]
**相关原型：**
- 新建租户：
<img width="1991" alt="集团概览-新增_编辑集团" src="https://github.com/TencentBlueKing/bk-user/assets/90179140/eb8afcb1-c886-49ce-b71a-b028674c2fd3">

- 编辑租户：
<img width="1600" alt="集团概览-公司详情" src="https://github.com/TencentBlueKing/bk-user/assets/90179140/41bcce5f-ae93-4ba6-9a31-85c99c7e3ae6">

- 租户展示：
<img width="1600" alt="集团概览" src="https://github.com/TencentBlueKing/bk-user/assets/90179140/dd90970d-2cde-4d4b-9419-f192165fa4f7">

**模型设计方案：**

1. 租户表tenant

| 字段          | 字段类型 | 说明         |
| ------------- | -------- | ------------ |
| id            | varchar  | 租户ID       |
| name          | varchar  | 租户名称     |
| logo          | longtext | 租户logo     |
| is_default         | bool     | 是否默认租户 |
| enabled_user_count_display | bool     | 人员数目展示 |

- logo使用base64
- user_count_display：用户数目展示，直接做成单一配置bool
- 这里 create_time、update_time省略
- id是租户ID，规则确定后在逻辑里面使用正则校验；=>需要跟产品确认租户ID规则

2. 租户-租户管理员关联表tenant_manager

| 字段           | 字段类型 | 说明       |
| -------------- | -------- | ---------- |
| id             | int      | 自增ID     |
| tenant_user_id | varchar  | 租户用户ID |
| tenant_id      | varchar  | 租户ID     |

3. 租户用户表tenant_user

| id                  | int     | 用户ID       |
| ------------------- | ------- | ------------ |
| tanant_id           | varchar | 租户ID       |
| data_source_user_id |         | 数据源用户ID |
| username            | varchar | 用户名       |
| language            | varchar | 语言         |
| timezone            | varchar | 时区         |
| wx_userid           | varchar | 微信标识     |

- 用户ID使用uuid，蓝鲸平台用户的唯一标识
- 租户所关联的数据源通过 数据源用户ID：data_source_user_id   来关联查询就可以
- 用户的详细信息可以推过数据源ID直接查数据源用户表，但也需要考虑一些常用场景可以冗余存储，例如username

### 接口设计方案

1. 新建租户接口

URL：`.../tenants/`

method：POST

入参（body）：

| key                     | 类型          | 是否必填 | 说明               | 请求示例 |
| ----------------------- | ------------- | -------- | ------------------ | -------- |
| id                      | str           | 是       | 租户id             |          |
| name                    | str           | 是       | 租户名称           |          |
| managers                | Array[object] | 是       | 租户管理人设置     | [{}]     |
| logo                    | str           | 否       | base64化的图片     |          |
| manager_password_config | json          | 是       | 管理员初始密码配置 |          |

=>

- 租户ID这里产品要定下规则
- manager_config这里产品要确认下管理员初始密码这块还要不要，不要的话 这里不需要这个入参

managers释义：

| 参数名称  | 类型 | 是否必填 | 说明   | 请求示例 |
| --------- | ---- | -------- | ------ | -------- |
| username  | str  | 是       | 用户名 |          |
| email     | str  | 是       | 邮箱   |          |
| telephone | int  | 是       | 手机号 |          |

响应：

| 参数名称 | 类型 | 说明   | 请求示例 |
| -------- | ---- | ------ | -------- |
| id       | str  | 租户ID |          |

2. 租户下用户列表（用于编辑租户 管理员下拉框）

URL：`.../tenants/<str:租户ID>/list_users/`

method：`get`

入参：

| 参数名称 | 类型 | 说明       | 请求示例 |
| -------- | ---- | ---------- | -------- |
| id       | str  | 租户ID     |          |
| keyword  | str  | 搜索关键词 |          |

response:

| 参数名称 | 类型 | 说明                 |
| -------- | ---- | -------------------- |
| id       | int  | 租户用户id           |
| username | str  | 用户名               |
| logo     | str  | 用户logo（一期没有） |

=>

- 这里产品要确认下拉取的是租户下 所有用户 还是只拉取租户下本地数据源的用户？

3. 编辑租户接口

URL： `.../tenants/<str:租户ID>/`

method：`PUT`

入参（body）：

| 参数名称                   | 类型 | 是否必填 | 说明               | 请求示例 |
| -------------------------- | ---- | -------- | ------------------ | -------- |
| name                       | str  | 是       | 租户名称           |          |
| manager_ids                | list | 是       | 租户管理人ID列表   |          |
| logo                       | str  | 是       | base64化的图片     |          |
| enabled_user_count_display | bool | 是       | 是否展示人员数量   |          |
| manager_password_config    | json | 是       | 管理员初始密码配置 |          |

=>

- manager_config这里产品要确认下管理员初始密码这块还要不要，不要的话 这里不需要这个入参

manager_ids释义：租户用户id列表

响应：

| 参数名称 | 类型 | 释义   |
| -------- | ---- | ------ |
| id       | int  | 租户id |

4. 租户列表接口

URL： `.../tenants/`

method：`GET`

入参（query_params）：

| 参数    | 类型 | 释义       |
| ------- | ---- | ---------- |
| keyword | str  | 搜索关键词 |

响应：

| 参数         | 类型          | 说明         |      |
| ------------ | ------------- | ------------ | ---- |
| name         | str           | 租户名称     |      |
| id           | int           | 租户ID       |      |
| logo         | str           | 租户logo     |      |
| data_sources | Array[object] | 租户下数据源 | [{}] |
| managers     | Array[object] | 租户管理员   | [{}] |

data_sources释义：

| 参数名称 | 类型 | 释义       |
| -------- | ---- | ---------- |
| id       | int  | 数据源ID   |
| name     | str  | 数据源名称 |

managers释义：

| 参数名称 | 类型 | 释义                   |
| -------- | ---- | ---------------------- |
| id       | int  | 蓝鲸用户名，租户用户id |
| username | str  | 管理员用户名           |

5. 租户详情接口

URL： `.../tenants/`{id}/

method：`GET`

响应：

| 参数名称 | 类型          | 释义       |
| -------- | ------------- | ---------- |
| id       | int           | 租户id     |
| name     | str           | 租户名称   |
| logo     | str           | 租户logo   |
| managers | Array[object] | 租户管理员 |

tenant_managers释义：

| 参数名称     | 类型 | 释义                   |
| ------------ | ---- | ---------------------- |
| id           | int  | 蓝鲸用户名，租户用户id |
| username     | str  | 管理员用户名           |
| display_name | str  | 管理员名称             |
| telephone    | str  | 手机号                 |
| email        | str  | 邮箱                   |

**Comment by neronkl** [comment]
## 接口设计

### 租户创建

url: `.../tenants/`

method: `post`

body

| 参数名称 | 类型 | 是否必填 | 释义           |
| -------- | ---- | -------- | -------------- |
| id       | int  | 是       | 租户id         |
| name     | str  | 是       | 租户名称       |
| managers | list | 是       | 租户管理人设置 |
| logo     | str  | 否       | base64化的图片 |

managers参数解释

| 参数名称     | 类型 | 是否必填 | 释义   |
| ------------ | ---- | -------- | ------ |
| username     | str  | 是       | 用户名 |
| display_name | str  | 是       | 名称   |
| email        | str  | 是       | 邮箱   |
| telephone    | int  | 是       | 手机号 |

response

| 参数名称 | 类型 | 释义     |
| -------- | ---- | -------- |
| id       | str  | 租户id   |
| name     | str  | 租户名称 |



### 租户编辑

url: `.../tenants/{id}/`

method: `put`

body:

| 参数名称    | 类型 | 是否必填 | 释义           |
| ----------- | ---- | -------- | -------------- |
| name        | str  | 是       | 租户名称       |
| manager_ids | list | 是       | 租户管理人设置 |
| logo        | str  | 是       | base64化的图片 |

**manager_ids参数解释：类型list 租户用户id列表**

response

| 参数名称 | 类型 | 释义     |
| -------- | ---- | -------- |
| id       | int  | 租户id   |
| name     | str  | 租户名称 |



### 租户展示

url: `.../tenants/`

method: `get`

query_params:

| 参数    | 类型 | 释义       |
| ------- | ---- | ---------- |
| keyword | str  | 搜索关键词 |

response

| name         | str  | 租户名称     |
| ------------ | ---- | ------------ |
| id           | int  | 租户id       |
| name         | str  | 租户名称     |
| logo         | str  | 租户logo     |
| data_sources | list | 租户下数据源 |
| managers     | list | 租户管理员   |

返回参数data_sources解释:

| 参数名称 | 类型 | 释义       |
| -------- | ---- | ---------- |
| name     | str  | 数据源名称 |
| status   | str  | 数据源状态 |

返回参数managers解释:

| 参数名称     | 类型 | 释义                   |
| ------------ | ---- | ---------------------- |
| id           | int  | 蓝鲸用户名，租户用户id |
| username     | str  | 管理员用户名           |
| display_name | str  | 管理员名称             |
| telephone    | str  | 手机号                 |
| email        | str  | 邮箱                   |



### 单个租户详情展示

url: `.../tenants/`{id}/

method: `get`

response

| 参数名称     | 类型 | 释义         |
| ------------ | ---- | ------------ |
| id           | int  | 租户id       |
| name         | str  | 租户名称     |
| logo         | str  | 租户logo     |
| data_sources | list | 租户下数据源 |
| managers     | list | 租户管理员   |

返回参数data_sources解释:

| 参数名称 | 类型 | 释义       |
| -------- | ---- | ---------- |
| name     | str  | 数据源名称 |
| status   | str  | 数据源状态 |

返回参数tenant_managers解释:

| 参数名称     | 类型 | 释义                   |
| ------------ | ---- | ---------------------- |
| id           | int  | 蓝鲸用户名，租户用户id |
| username     | str  | 管理员用户名           |
| display_name | str  | 管理员名称             |
| telephone    | str  | 手机号                 |
| email        | str  | 邮箱                   |



### 获取租户下用户

url: `.../tenants/{id}/list_users/`

method: `get`

query_params:

| 参数    | 类型 | 释义       |
| ------- | ---- | ---------- |
| keyword | str  | 搜索关键词 |

response:

| 参数名称     | 类型 | 释义       |
| ------------ | ---- | ---------- |
| id           | int  | 租户用户id |
| username     | str  | 用户名     |
| display_name | str  | 用户名称   |
| logo         | str  | 用户logo   |

**Comment by neronkl** [comment]
#1042
