### ISSUE TITLE
bk-user用户管理 没有安装指引

### ISSUE THREAD

**Issue by zhucaipeng** [TencentBlueKing/bk-user#1084]
bk-user用户管理 没有安装指引

![WZH{2Q2YEHSRPA7@7@`LTX8](https://github.com/TencentBlueKing/bk-user/assets/18751306/9ab91ee9-ff9b-477c-b599-a5e5cd2b99c0)
![{8E4IMHR1WBB D57NHL8JR4](https://github.com/TencentBlueKing/bk-user/assets/18751306/6a9ee2ff-d961-49fa-a9f4-77ce5aa85818)

**Comment by nannan00** [comment]
蓝鲸所有产品容器化部署的文档已放置到蓝鲸官网，单独产品部署文档已不在代码库里维护https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.0/beginners_guide.md?catalog_id=1017
