### ISSUE TITLE
启动Saas后端，报错ModuleNotFoundError: No module named 'bkuser_shell.config.overlays.dev'

### ISSUE THREAD

**Issue by Xouer** [TencentBlueKing/bk-user#1104]
**用文字描述你遇到的问题**

![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/820ec699-bb55-4e3b-989b-3a2f70c76051)

**重现方法**

命令行执行 ： bash bin/start_dev.sh
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/a4ec0799-39be-4376-9099-ebc205800fa8)

**预期行为**

预期的正常行为

**版本**
- v2.5.2版本

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-user/tree/v2.5.2/src/api/bkuser_core/config/overlays

<img width="303" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/17491932/8d8b4fdb-430b-40ad-ae37-67480213cef8">

需要自行添加 dev.py文件，dev.tmpl是参考模板

**Comment by Xouer** [comment]
> https://github.com/TencentBlueKing/bk-user/tree/v2.5.2/src/api/bkuser_core/config/overlays
> 
> <img alt="image" width="303" src="https://user-images.githubusercontent.com/17491932/256689503-8d8b4fdb-430b-40ad-ae37-67480213cef8.png">
> 需要自行添加 dev.py文件，dev.tmpl是参考模板

谢谢您的回答，确实解决了这个问题，之后出现了新的问题。重新执行后，报了一下的错误内容
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/582c4425-45c1-450a-a830-d76a3bf64722)
