### ISSUE TITLE
login服务上进行登录报404  /console/

### ISSUE THREAD

**Issue by Xouer** [TencentBlueKing/bk-user#1110]
**用文字描述你遇到的问题**

在login服务上，进行登录，登录成功后，
WARNING [2023-07-30 14:31:16,706] "GET /console/ HTTP/1.1" 404 3903
WARNING [2023-07-30 14:31:16,886] "GET /favicon.ico HTTP/1.1" 404 3912
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/bfb6b507-5638-473e-9c88-39887adfd343)

**重现方法**

在login服务上，进行登录，登录成功后

**预期行为**

预期的正常行为

**版本**
- v2.5.2

**Comment by nannan00** [comment]
正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台

本地测试时，带上curl参数即可正确redirect

**Comment by Xouer** [comment]
请教，我如何能够，直接调整到用户管理的操作页面上？

**Comment by Xouer** [comment]
> 正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台
> 
> 本地测试时，带上curl参数即可正确redirect
请教，我如何能够，直接调整到用户管理的操作页面上？

**Comment by Xouer** [comment]
> 正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台
> 
> 本地测试时，带上curl参数即可正确redirect

请教，我如何能够，直接跳转到用户管理的操作页面上？

**Comment by nannan00** [comment]
> > 正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台
> > 本地测试时，带上curl参数即可正确redirect
> 
> 请教，我如何能够，直接跳转到用户管理的操作页面上？

添加 c_url = xxxxxx

xxxxx 即为用户管理的地址，比如 http://{dev-bkuser host}/organization

需要保证 登录与用户管理域名是共父域名，即bk_token的Cookie可共享

**Comment by Xouer** [comment]
> 



> > > 正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台
> > > 本地测试时，带上curl参数即可正确redirect
> > 
> > 
> > 请教，我如何能够，直接跳转到用户管理的操作页面上？
> 
> 添加 c_url = xxxxxx
> 
> xxxxx 即为用户管理的地址，比如 http://{dev-bkuser host}/organization
> 
> 需要保证 登录与用户管理域名是共父域名，即bk_token的Cookie可共享
我按照配置文件，修改了对应域名，现在已经在hosts文件上，创建了一个域名，并且这个域名已经设置成相同的，但是没有解决。
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/792970c2-911f-4b02-9429-85bf36a43365)

![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/e047464f-b0cf-45ba-8d7c-f28fddf88f3a)

**Comment by Xouer** [comment]
> > 
> 
> > > > 正常预期内，在生产环境上，登录如果无curl参数，则会自动跳转到蓝鲸桌面/工作台
> > > > 本地测试时，带上curl参数即可正确redirect
> > > 
> > > 
> > > 请教，我如何能够，直接跳转到用户管理的操作页面上？
> > 
> > 
> > 添加 c_url = xxxxxx
> > xxxxx 即为用户管理的地址，比如 http://{dev-bkuser host}/organization
> > 需要保证 登录与用户管理域名是共父域名，即bk_token的Cookie可共享
> 
> 我按照配置文件，修改了对应域名，现在已经在hosts文件上，创建了一个域名，并且这个域名已经设置成相同的，但是没有解决。 ![image](https://user-images.githubusercontent.com/15797062/257166565-792970c2-911f-4b02-9429-85bf36a43365.png)
> 
> ![image](https://user-images.githubusercontent.com/15797062/257169372-e047464f-b0cf-45ba-8d7c-f28fddf88f3a.png)

这个问题，需要修改page里面面index-dev文件，我修改完毕后，成功了。
