### ISSUE TITLE
组织架构树展示&查看部门/用户/用户与部门关系

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1112]
Note: @neronkl  根据设计稿，补充需要实现的API和功能点

**Comment by neronkl** [comment]
- [ ]  租户下数据源展示
- [ ]  租户下组织架构树展示
- [ ]  租户下组织架构树下部门用户展示（仅仅展示本部门）分页支持
- [ ]  租户下组织内搜索人员，分页支持

**Comment by neronkl** [comment]
**多租户下组织架构展示，限定范围是当前租户下**

#### 数据源展示

通过绑定关系，展示租户对应数据源。

api：`api/v1/web/tenants/{tenant_id}/data_sources/`

功能点：

- 数据源由当前租户所创建，通过数据源的owner字段，获取当前租户的数据源
- 通过绑定关系，获取协同数据源
- 类比旧版目录展示，数据源数据返回，同时携带其下的根组织

细节：
1. 通过租户ID(tenant_id) 获取当前租户创建的数据源
2. 根据获取的数据源，返回基础信息（id， name，plugin_type）
3. 根据获取的数据源id，拉取数据源下根组织基础信息，判断是否有子组织（has_children）
4. 根组织基础数据返回，数据源组织id转换为租户部门id
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/c9c9886b-b7a4-4d85-8329-3d06379d63bd)







#### 组织架构展示

在多租户版本中，租户下的组织架构是通过映射数据源而来，页面涉及到组织的ID都是租户部门ID。租户部门仅保存映射关系，不会冗余部门信息。部门相关的数据，需通过映射关系，查询对应数据源下的对应部门信息。

api： `api/v1/web/tenant_departments/{tenant_department_id}/`

功能点：

- 页面上组织架构展示的ID为该租户部门ID
- 通过映射关系返回部门数据
- 数据返回：基础信息，子部门信息(has_children, children)，部门路径(full_name)

细节：

1. 部门展示是基于租户所绑定的数据源返回的租户根组织进行
2. 根据租户部门ID，反查所映射的数据源部门，返回部门基础信息
3. 根据部门基础信息has_children, 返回子部门数据

![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/608d3138-568c-4e3d-8518-2bc4fe0d3256)




#### 人员展示

人员展示是基于某个组织下进行展示。因为数据源会绑定租户，数据源用户会和租户生成映射关系。租户下的用户ID即是bk_username（全局唯一）

部门下用户查询过程

功能点

- 组织下人员常规展示, `api/v1/web/tenant_deparments/{tenant_department_id}/users/`
- 组织下多关键词人员搜索 `api/v1/web/tenant_deparments/{tenant_department_id}/users/search/`
- 数据返回：用户基础信息，蓝鲸属性，**租户用户ID(bk_username)**

细节：

1. 根据租户部门ID，反查数据源部门ID
2. 根据数据源部门ID，查询该部门下的用户
3. 返回用户基础信息，蓝鲸属性，转换id为租户用户id
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/d395d369-cd99-4018-a99a-b59a4c769d49)



#### 全局搜索

全局搜索，可能是搜索部门，可能是搜索租户用户

- 搜索部门：部门搜索一般是通过名称搜索

​		1. 获取租户下绑定部门

​		2. 通过所绑定的部门，在数据源通过那么进行过滤

- 搜索用户：用户搜索，搜索命中字段：邮箱，手机号，QQ等。

细节：

1. 以上查询都是基于租户绑定的数据源进行
2. 转换为对应的租户部门ID，以及租户用户ID

**Comment by neronkl** [comment]
排期：
开发：20230810-20230818

**Comment by nannan00** [comment]
1. API URL尽可能的遵守Restful风格
    - `/api/v1/web/tenant_departments/{tenant_department_id}/  => /api/v1/web/tenant-departments/{tenant_department_id}/`
------
1. 第一层是租户，应该有租户列表接口
2. 第二层是租户下所有数据源的部门列表
3. 第三层是子部门列表
----
1. 为什么需要extras？
2. 租户信息应该是一个另外接口
3. api/v1/web/tenant_departments/{tenant_department_id}/接口 为什么同时需要children和has_children字段
4. api/v1/web/tenant_deparments/{tenant_department_id}/users/接口，不要多种用途
5. 搜索接口和列表接口应该是可以同一个，并不需要两个
6. 全局搜索暂时不做

**Comment by neronkl** [comment]
> 1. API URL尽可能的遵守Restful风格
>    
>    * `/api/v1/web/tenant_departments/{tenant_department_id}/  => /api/v1/web/tenant-departments/{tenant_department_id}/`
> 
> 1. 第一层是租户，应该有租户列表接口
> 2. 第二层是租户下所有数据源的部门列表
> 3. 第三层是子部门列表
> 
> 1. 为什么需要extras？
> 2. 租户信息应该是一个另外接口
> 3. api/v1/web/tenant_departments/{tenant_department_id}/接口 为什么同时需要children和has_children字段
> 4. api/v1/web/tenant_deparments/{tenant_department_id}/users/接口，不要多种用途
> 5. 搜索接口和列表接口应该是可以同一个，并不需要两个
> 6. 全局搜索暂时不做

已在原方案调整
1. 租户组织接口去掉extras，has_children

**Comment by neronkl** [comment]
> 1. API URL尽可能的遵守Restful风格
>    
>    * `/api/v1/web/tenant_departments/{tenant_department_id}/  => /api/v1/web/tenant-departments/{tenant_department_id}/`
> 
> 1. 第一层是租户，应该有租户列表接口
> 2. 第二层是租户下所有数据源的部门列表
> 3. 第三层是子部门列表
> 
> 1. 为什么需要extras？
> 2. 租户信息应该是一个另外接口
> 3. api/v1/web/tenant_departments/{tenant_department_id}/接口 为什么同时需要children和has_children字段
> 4. api/v1/web/tenant_deparments/{tenant_department_id}/users/接口，不要多种用途
> 5. 搜索接口和列表接口应该是可以同一个，并不需要两个
> 6. 全局搜索暂时不做

1. 组织接口协议去掉extra，has_children

**Comment by neronkl** [comment]
> 1. API URL尽可能的遵守Restful风格
>    
>    * `/api/v1/web/tenant_departments/{tenant_department_id}/  => /api/v1/web/tenant-departments/{tenant_department_id}/`
> 
> 1. 第一层是租户，应该有租户列表接口
> 2. 第二层是租户下所有数据源的部门列表
> 3. 第三层是子部门列表
> 
> 1. 为什么需要extras？
> 2. 租户信息应该是一个另外接口
> 3. api/v1/web/tenant_departments/{tenant_department_id}/接口 为什么同时需要children和has_children字段
> 4. api/v1/web/tenant_deparments/{tenant_department_id}/users/接口，不要多种用途
> 5. 搜索接口和列表接口应该是可以同一个，并不需要两个
> 6. 全局搜索暂时不做

已在原方案修改
1. 组织数据协议去掉extras，has_children
2. 租户列表接口：`api/v1/web/tenant-departments/tenants/`
3. 组织内用户接口：增加keyword参数作为搜索参数
4. 去掉全局搜索接口搜索
