### ISSUE TITLE
前端访问后端接口报CORS error,用户信息缺失

### ISSUE THREAD

**Issue by Xouer** [TencentBlueKing/bk-user#1122]
**用文字描述你遇到的问题**

我刚刚登录成功，现在去使用功能发现，后端接口报CORS问题。

**重现方法**
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/98942f4c-03d1-4e73-8246-bc3ff378d7b1)
8004端口为API后端服务；
在页面点击“用户目录”发现了CORS问题

![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/37b73a53-25f4-47f0-9e25-4646c09a5a44)
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/d0e3cb1c-abe4-48f2-ab2d-0afb1532f194)
返回200的接口，页面数据返回
![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/70c1fab2-e0d5-4a75-a2d7-73beb36c6b1c)
用户信息缺失

8月2日，刚刚发现，我登录成功后跳转到index-dev.html页面后，用户并没有显示，这就对应了“用户信息缺失”的内容，这表示，只是页面发生了跳转，用户登录成功的用户信息，并没有在index-dev.html显示。

这样我又回到了，这个问题下面，这个地址应该写成什么？要写前端SAAS的服务端口，还是要写后端SAAS的服务端口？
https://github.com/TencentBlueKing/bk-user/issues/1110#issue-1827828069

**预期行为**

点击，能够获取正常数据

**版本**
- 提供用户管理的具体版本号--v2.5.2

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**
 - OS: [e.g. iOS]  === Ubuntu
 - Browser [e.g. chrome, safari] ===chrome
 - Version [e.g. 22]   === 2.5.2

**额外信息**

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/overlays/dev.tmpl

请参考 dev.tmpl 配置，支持CORS配置

**Comment by Xouer** [comment]
> 

![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/77767500-6730-41cf-afb1-c03e1b332e37)
这是我本地的配置文件内容，该文件在saas后端下面，我对比了您的链接内容，没有找到任何差异

**Comment by Xouer** [comment]
> https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/overlays/dev.tmpl
> 
> 请参考 dev.tmpl 配置，支持CORS配置

![image](https://github.com/TencentBlueKing/bk-user/assets/15797062/9d6a8e9d-a5c2-4ce8-adf4-326ab7da7387)
这是我本地的配置文件内容，该文件在saas后端下面，我对比了您的链接内容，没有找到任何差异
