### ISSUE TITLE
完善基础框架配置

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1126]
- [x] pytest
- [x] monitoring
   - [x] healthz/ping
   - [x] metrics(django_prometheus)
   - [x] otel
   - [x] sentry
- [x] 性能排查&统计配置(比如 pyinstrument)
- [x] 日志 添加request_id_filter
- [x] redis、cache配置
- [x] github action
- [x] github template

**Comment by nannan00** [comment]
添加 pull request的 template，参考：https://github.com/TencentBlueKing/blueking-apigateway/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by narasux** [comment]
https://github.com/TencentBlueKing/bk-user/pull/1132
https://github.com/TencentBlueKing/bk-user/pull/1144

**Comment by narasux** [comment]
pyinstrument 暂时不考虑
