### ISSUE TITLE
用户管理的配置文件api#bkuser_core#config#overlays#prod.py在哪里？

### ISSUE THREAD

**Issue by JackHuang-888** [TencentBlueKing/bk-user#1142]
产品：用户管理2.4.2版本
版本： 蓝鲸社区版6.1.2
问题描述： 蓝鲸6.1.2的用户管理API后台部署时会通过api#bkuser_core#config#overlays#prod.py模板文件渲染生成 prod.py配置文件，我从github源码中没有找到这个模板文件，想问下官方，这些模板文件源码存放在哪里？

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-user/tree/master/src/build/api/support-files/templates
