### ISSUE TITLE
本地数据源-用户增改查

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1147]
本地数据源用户的增改查功能，列出所需API，以及API所需实现的大概思路or步骤

**Comment by Canway-shiisa** [comment]
**新建用户：**
1. 相关原型：
![image](https://github.com/TencentBlueKing/bk-user/assets/90179140/64ce6d72-cbeb-4f87-be7f-6ffe4dd6fc07)

2. 接口设计相关（待完善）
URL： `.../data_source/<int:数据源ID>/user/`
method：`POST`

3. 思路（职务、在职状态、账号过期时间、密码过期时间等一期暂不处理）：
- 校验用户信息
- 提供拉取当前数据源所有用户的接口（用于新建时下拉选择直属上级）
- 提供拉取当前数据源所有部门的接口（用于新建时下拉选择所属组织）
- 关联用户到owner租户下

**用户详情：**
1. 相关原型：
![image](https://github.com/TencentBlueKing/bk-user/assets/90179140/11b68d01-e1c0-47c7-8431-a5745633d218)

2. 接口设计相关（待完善）
URL： 
method：`GET`

3. 思路


**更新用户：**
1. 相关原型：
![image](https://github.com/TencentBlueKing/bk-user/assets/90179140/11b68d01-e1c0-47c7-8431-a5745633d218)

2. 接口设计相关（待完善）
URL： 
method：`GET`

3. 思路



**获取当前数据源下所有部门：**
1. 接口设计相关（待完善）
URL： 
method：`GET`

2. 思路


**获取当前数据源下所有用户：**
1. 接口设计相关（待完善）
URL： 
method：`GET`

2. 思路

**Comment by nannan00** [comment]
1. 补充每个接口需要的工作量，以天为单位
2. 只有本地数据源才支持页面的新增&修改
3. URL补全，不要使用 `...`
4. 新建数据源用户接口
    - 部门非必填的，可以与产品确认
    - 除了手机号，还有手机号的国际区号字段
    - username有什么字符要求？其他字段的字符校验要求
    - 事务里是否还需要包括部门与用户关系、Leader关系的新增
 5. 数据源下用户列表接口
    - 不要一个接口做所有事情，要考虑是否合适
 6. 更新（编辑）数据源用户接口
    - 无leader是否self判断
    - username是不可以更新的

**Comment by Canway-shiisa** [comment]
> 1. 补充每个接口需要的工作量，以天为单位
> 2. 只有本地数据源才支持页面的新增&修改
> 3. URL补全，不要使用 `...`
> 4. 新建数据源用户接口
>    
>    * 部门非必填的，可以与产品确认
>    * 除了手机号，还有手机号的国际区号字段
>    * username有什么字符要求？其他字段的字符校验要求
>    * 事务里是否还需要包括部门与用户关系、Leader关系的新增
> 5. 数据源下用户列表接口
>    
>    * 不要一个接口做所有事情，要考虑是否合适
> 6. 更新（编辑）数据源用户接口
>    
>    * 无leader是否self判断
>    * username是不可以更新的

1. 已更新在原方案中
2. 嗯嗯 这个了解~
3. 已更新在原方案中
4. 新建数据源用户接口相关问题:
- 部门是否必填，待 @Xmandon 确认
- 已补充
- 已有标识，同步迁移到新建部分的思路中  
- 关系也都有做新增，新版方案中已标注
5. 更新为不同接口
- 数据源用户列表接口
- 数据源用户详情接口
- 下拉leaders列表接口
6. 更新（编辑）数据源用户接口
- `无leader是否self判断`=>这个有传入 leader会判断不能传递自己作为leader
- ok

**Comment by Canway-shiisa** [comment]
- [新建数据源用户 ]

**Comment by Canway-shiisa** [comment]
- [ ] 测试
