### ISSUE TITLE
设置-用户字段设置

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#1205]
- [x] 用户字段列表（不分页）
- [x] 添加用户字段
- [x] 编辑用户字段
- [x] 删除用户字段
- [ ] 相关单元测试

**Comment by Canway-shiisa** [comment]
### 模型设计方案

1. 动态字段表dynamic_field

| 字段            | 字段类型 | 说明         |
| --------------- | -------- | ------------ |
| id              | int      | 自增ID       |
| display_name_en | varchar  | 字段英文名称 |
| display_name_zh | varchar  | 字段中文名称 |
| type            | varchar  | 字段类型     |
| require         | bool     | 是否必填     |
| unique          | bool     | 是否唯一     |
| editable        | bool     | 是否可编辑   |
| builtin         | bool     | 是否内置字段 |
| visible         | bool     | 是否展示     |
| order           | int      | 顺序         |
| default         | longtext | 默认值       |
| options         | longtext | 选项         |

- default存储一些内置字段默认值，枚举默认选项等  
- options  存储枚举选项

**Comment by narasux** [comment]
有以下几个问题：
1. 表字段没有包含租户信息，动态字段是各租户独有的
2. 不需要 display_name_en/zh，而是需要 field_name，display_name
3. type 意义不够准确，用 data_type 会更合适，需要补充类型枚举类设计
4. editable 字段功能不明确，待产品确认是否保留
5. builtin 字段去掉，内置字段不在这个表维护
6. visible 属性是设计稿中存在的吗，不要保留暂时不需要的属性
7. 唯一索引，应该与 租户信息 做联合唯一索引

**Comment by narasux** [comment]
模型名称可以是 TenantUserCustomField，dynamic 其实并不准确

**Comment by narasux** [comment]
讨论结果：editable 字段本期不加，后面考虑清楚再上

**Comment by Canway-shiisa** [comment]
产品沟通结果：
1. 页面展示调整：原 英文标识 调整为 唯一标识
2. 不进行页面调整字段展示排序的功能（=》去掉order字段），按照默认顺序：内置字段在前，自定义字段在后
3. 唯一性以及可编辑性一期暂不实现
