### ISSUE TITLE
个人中心展示

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#1210]
个人中心，需求解析，方案设计
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/9b7b82f0-7453-489f-b58a-1a1915168b07)

**Comment by neronkl** [comment]
### 租户账号详情展示

根据当前所选择的租户用户（租户用户ID），展示改租户用户的身份信息数据，以上信息除了phone和Email可以变更，其他信息都不能编辑

提供接口：租户用户详情

url：`api/user-center/<id:str>/`

method:GET

url入参

| 字段名称 | 类型 | 必填 | 释义       |
| -------- | ---- | ---- | ---------- |
| id       | str  | 是   | 租户用户ID |

response

| 字段名称           | 类型         | 释义                 |
| ------------------ | ------------ | -------------------- |
| username           | str          | 用户名               |
| full_name          | str          | 全名                 |
| tenant_id          | str          | 租户ID               |
| email              | str          | 邮箱                 |
| is_inherited_email | bool         | 是否继承数据源邮箱   |
| phone              | int          | 手机号               |
| is_inherited_phone | bool         | 是否继承数据源手机号 |
| departments        | list[object] | 所属部门             |
| leaders            | list[object] | 上级                 |



### 变更手机号/邮箱

点击自定义: is_inherited_email(is_inherited_phone) = False

点击继承： is_inherited_email(is_inherited_phone) = True

点击继承=》拉取租户用户对应数据源用户的手机号/邮箱，自动切换为数据源邮箱/手机号



提供接口：租户用户-数据源数据（phone&email）

该接口仅提供查询该租户所绑定数据源用户的联系方式（phone&email）

url：`api/user-center/<id:str>/data-source-user/contacts/`

method:GET

url入参

| 字段名称 | 类型 | 必填 | 释义       |
| -------- | ---- | ---- | ---------- |
| id       | str  | 是   | 租户用户ID |

response

| 字段名称 | 类型 | 释义   |
| -------- | ---- | ------ |
| phones   | str  | 手机号 |
| email    | str  | 邮箱   |



提供接口：租户联系方式数据变更

url：`api/user-center/<id:str>/contact/`

method:PATCH

url入参

| 字段名称 | 类型 | 必填 | 释义       |
| -------- | ---- | ---- | ---------- |
| id       | str  | 是   | 租户用户ID |

request_body

url入参

| 字段名称       | 类型 | 必填 | 释义                      |
| -------------- | ---- | ---- | ------------------------- |
| is_inherited   | bool | 是   | 数据是否继承数据源        |
| contact_method | str  | 是   | 联系方式选择：phone/email |
| value          | str  | 是   | 联系方式                  |





### 自然人已关联账号展示

账号关联情景：

- 同一数据源用户（一个自然人）被多个租户所绑定（至少有一个数据源所归属的租户）

  

- 自然人绑定了非自身对应数据源的租户用户

**Comment by nannan00** [comment]
1. 自然人 与 数据源用户解耦
- 自然人目的是用于将多个数据源账号关联在一起，后续可以让用户切换不同账号，所以自然人只需要在绑定时生成

2. api url命名问题，user-center是一个功能模块，不是具体对象，后面不应该有 /<id:str>/的表达，没有多个”个人中心“

3. 关联的账号列表，需要有租户名称 和 用户ID

4. 租户用户信息欠缺：继承的email和phone，还有手机国际区号

5. email的修改和phone的修改分开，手机号还有国际区号

**Comment by neronkl** [comment]
1. 解耦：自然人不在数据源用户生成时创建

**Comment by neronkl** [comment]
已在源方案进行修改
1.自然人解耦：自然人不在数据源用户生成时创建
2.
展示已关联账号=>`api/user-center/tenant-users/`
租户账号详情展示=>`api/user-center/tenant-users/<id:str>/`
3. 补充字段 ：id， tenant_name
4. 补充字段：phone_country_code， custom_phone， custom_phone_country_code， custom_email
5.
修改邮箱=>`api/user-center/tenant-users/<id:str>/change_mail/`
修改手机号=>`api/user-center/tenant-users/<id:str>/change_phone/`
