### ISSUE TITLE
feat: ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials

### ISSUE THREAD

**Issue by zhengwe** [TencentBlueKing/bk-user#1247]
使用蓝鲸云平台接入ldap用户认证失败报错如下：
![image](https://github.com/TencentBlueKing/bk-user/assets/38490510/03bc61af-bf67-44d4-bb8b-bb653dbbc87f)

后台日志报错如下：
![30f5cc2b4cf8168e20cce88744e5bf09](https://github.com/TencentBlueKing/bk-user/assets/38490510/be5c9346-0308-43b3-a978-d91fb50eee83)

**版本**
- 社区版-7.0

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**
 - OS: cetons 7.0
 - Browser: chrome
 - Version: 116.0.5845.187（正式版本） (arm64)

**Comment by zhengwe** [comment]
用户名和密码是正确的

**Comment by nannan00** [comment]
可以按照LDAP FAQ排查： https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1125623021

**Comment by zhengwe** [comment]
> 可以按照LDAP FAQ排查： [#429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1125623021)

![image](https://github.com/TencentBlueKing/bk-user/assets/38490510/2935018f-cd29-435e-bc02-c7c74e931a66)
LDAP FAQ给出的答案是：用户名密码错误，我用此帐号密码又可以登录ldap管理后台，就很奇怪，不知道有没有其它原因

**Comment by nannan00** [comment]
@zhengwe 该错误是由于Python库[ldap3](https://pypi.org/project/ldap3/) 抛出的异常，建议可以直接使用该库进行连接测试

----
可能的原因：此账号密码并没有配置bind操作
