### ISSUE TITLE
用户管理 - ad目录同步的时候，出现大量慢查询

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#125]
用户目录配置：
![image](https://user-images.githubusercontent.com/90179140/139014657-43f020eb-8ade-449b-90d6-f4efee2f9cd9.png)

![image](https://user-images.githubusercontent.com/90179140/139014492-3290d8b8-2773-42a1-b318-aabb39d2212a.png)

具体慢查询记录：
![image](https://user-images.githubusercontent.com/90179140/139015215-03363280-3f12-4971-998b-e7b4ee5617be.png)

**Comment by IMBlues** [comment]
如果 #198 的内容完成了，应该能够大幅度减少单次向数据库提交内容的大小，该问题会得到缓解。先关闭该 issue，待有环境稳定重现时可重新打开。
