### ISSUE TITLE
登录及修改密码相关的接口应该使用【密文】传递密码

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#126]

**Comment by IMBlues** [comment]
可能的前端加密方案：

![image](https://user-images.githubusercontent.com/4225292/140893864-e4ff42a6-5334-49f5-b18e-514506ef0912.png)

https://github.com/travist/jsencrypt

后端以私钥解密后，保持原逻辑不变

**Comment by IMBlues** [comment]
临时使用 base64 隐藏明文

**Comment by wklken** [comment]
1. 前端base64编码
2. 后台form表单拿到之后, 第一时间decode, 往后走逻辑

------

需要变更, 提交 PR 到两个项目:
1. 7.0 https://github.com/TencentBlueKing/bk-user  的login项目
2. 6.0/3.0 https://github.com/Tencent/bk-PaaS/tree/develop  这个分支
   6.1/3.1之后的版本 https://github.com/Tencent/bk-PaaS/tree/ft_upgrade_py3  (直接cherry pick过来)


------

**Comment by Chace-wang** [comment]
需求：蓝鲸登录前端密码传输时，rsa加密处理

**Comment by Chace-wang** [comment]
需求：蓝鲸登录前端密码传输时，rsa加密处理
修改模块：
    1. bk-PaaS/paas2/login
    2. bk-user/src/login
    
修改内容：
    1. login/conf/default
        添加DEFAULT_RSA_PUBLIC_KEY，DEFAULT_RSA_PRIVATE_KEY、RSA_PRIVATE_KEY、RSA_PRIVATE_KEY配置
        因为代码开源，为了安全，配置可从环境变量修改
        
       ![image](https://user-images.githubusercontent.com/34097844/161360968-055853b7-6c17-412c-b046-d0eb67e9afa5.png)

    2. common/context_processors.py
        增加传参RSA_PUBLIC_KEY给前端
        
        ![image](https://user-images.githubusercontent.com/34097844/161361049-e7ab4e04-ce9a-4e47-90b9-e821751683da.png)

    4.  增加utils/crypt
          添加rsa解密函数
        ![image](https://user-images.githubusercontent.com/34097844/161361236-c650f615-3f0c-4875-a571-4342e2c55b17.png)

    5.  bkauth/forms
          密码认证前进行解密
         ![image](https://user-images.githubusercontent.com/34097844/161361276-03cde04d-c451-4de5-9185-7bf6405b8cd3.png)

    6. static/assets/ 
        新增依赖jsencrypt.js，前端rsa加密用
    8.

**Comment by IMBlues** [comment]
> 需求：蓝鲸登录前端密码传输时，rsa加密处理 修改模块： 1. bk-PaaS/paas2/login 2. bk-user/src/login
> 
> 修改内容： 1. login/conf/default 添加DEFAULT_RSA_PUBLIC_KEY，DEFAULT_RSA_PRIVATE_KEY、RSA_PRIVATE_KEY、RSA_PRIVATE_KEY配置 因为代码开源，为了安全，配置可从环境变量修改
> 
> ![image](https://user-images.githubusercontent.com/34097844/161360968-055853b7-6c17-412c-b046-d0eb67e9afa5.png)
> 
> ```
> 2. common/context_processors.py
>     增加传参RSA_PUBLIC_KEY给前端
> ```
> 
> ![image](https://user-images.githubusercontent.com/34097844/161361049-e7ab4e04-ce9a-4e47-90b9-e821751683da.png)
> 
> ```
> 4.  增加utils/crypt
>       添加rsa解密函数
> ```
> 
> ![image](https://user-images.githubusercontent.com/34097844/161361236-c650f615-3f0c-4875-a571-4342e2c55b17.png)
> 
> ```
> 5.  bkauth/forms
>       密码认证前进行解密
> ```
> 
> ![image](https://user-images.githubusercontent.com/34097844/161361276-03cde04d-c451-4de5-9185-7bf6405b8cd3.png)
> 
> ```
> 6. static/assets/ 
>     新增依赖jsencrypt.js，前端rsa加密用
>     依赖下载地址：https://www.bootcdn.cn/jsencrypt/
> 
> 7. templates/account/login.html or login_ce.html
>     密码传输前进行rsa加密
> ```
> 
> ![image](https://user-images.githubusercontent.com/34097844/161361714-d5b706cc-2505-41fc-9eba-b3d2c38f666e.png)

看起来流程都是 OK 的，用户管理还有修改密码部分，看看要不要一并修改了？

**Comment by Chace-wang** [comment]
需求：修改、重置密码时传输加密
(因缺少前端开发人员，暂只提供后端修改方案)
### 后端修改
修改模块：bk-user/src/saas
1. saas/bkuser_shell/config/common/platform.py
    添加DEFAULT_RSA_PUBLIC_KEY，DEFAULT_RSA_PRIVATE_KEY、RSA_PRIVATE_KEY、RSA_PRIVATE_KEY配置

2. saas/bkuser_shell/common/context_processors.py
    增加传参RSA_PUBLIC_KEY给前端

3. saas/bkuser_shell/common/增加crypt.py，添加解密函数，同上面login模块的crypt.py
    (后续可以把crypt.py放到bkuser_global中共用)

4. saas/bkuser_shell/common/serializers.py
    修改函数Base64OrPlainField
    a. 去除兼容base64的代码
    b. 添加rsa加密

**Comment by wklken** [comment]
登录的已合并: https://github.com/TencentBlueKing/bk-user/pull/532
版本: > [v2.3.4-beta.29](https://github.com/TencentBlueKing/bk-user/releases/tag/v2.3.4-beta.29)
