### ISSUE TITLE
【多租户】用户字段的使用

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#1277]

**Comment by nannan00** [comment]
- 本地数据源用户自定义字段 增/改/查
- 个人中心、租户组织架构-租户用户 展示用户自定义字段信息（不仅仅所有数据源用户都有自定义字段）

**Comment by neronkl** [comment]
# 本地数据源用户自定义字段使用 

## 1. 数据源用户表保存自定义字段

使用已内置extras字段

## 2. 数据源用户的自定义字段的增/改/查

现在数据源用户的系列接口，仅仅使用的内置字段

### 2.1 用户新增

#### 2.1.1 前端处理

- 前端获取当前租户的设置自定义字段
- 调用新增接口，自定义字段的英文标识为key，输入数据为value。和内置字段的数据一并上传。

​			   部份非必填字段，用户无需求，value为默认值

​			**数字以str的形式，进行传递。旧版，数字控件因为输入方式的原因，可能是数字类型，或者为字符串类型**

​			例：

```python
// name="example", display_name="示列", value="test"/"123.123"/"2xxx.xx.xx"
// 传入协议
{
    ... // 内置字段数据
    "example" : "test" // "123.123" or "2xxx.xx.xx"
}
```

​			枚举类型：枚举类型较为特殊，使用其设置选项的id作为value

```python
// display_name: "性别"
// name: "gender"
// options: [{id: 0, value: "男"}, {id: 1, value: "女"}]
{
    ... // 内置字段数据
    "gender" : 0 
}
```



#### 2.1.2 后台处理

- 接口的slz层只会校验内置字段，
- `request.data` 做动态字段系列操作
  - 动态字段的存在检测
  - 非法数据检查 （枚举字段的枚举值是否非法）
  - 必填/非必填检测 （非必填字段，使用提供默认值）
- 数据组装，动态字段kv，写入用户extra。内置字段常规写入



### 2.2 用户查看

#### 2.2.1 后台处理

​	用户查看有两个接口：用户列表查看，单个用户详情。两者的输出协议几乎一样

- slz 层 获取extras字段，slz输出单个用户的时候，将extra拍平返回

#### 2.2.2 前端处理

- 拉取字段设置展示接口
- 做映射展示

### 2.3 用户编辑

​	前端, 后台处理可参考 **2.1.1**。extra字段做update处理

**Comment by Canway-shiisa** [comment]
![image](https://github.com/TencentBlueKing/bk-user/assets/90179140/65896b2f-bbce-4b76-98bc-cfde0ff9a1d7)
用户列表展示的字段应该是需要根据这里的表格设置来决定，不是全部字段都展示，这块要确认下

**Comment by neronkl** [comment]
@Canway-shiisa 
1. 暂时不做展示设置
2. 这部分前端内置字段的username写死不给编辑，@narasux，内置字段是否需要补充可编辑属性

**Comment by nannan00** [comment]
1.2.1.1： 为什么需要考虑旧版用户管理的数字控件
  - extras里的字段类型是数字，前端就需要传入数字，不应该统一成字符串

1.2.1.2：需要做哪些检查，列举出来，比如必填、唯一性、后续是否可修改等等？

**Comment by narasux** [comment]
1.2.1.1 需要评估下，枚举类型目前用数字作为 id 的合理性，在导出等场景下，可读性很差，需要与产品进行讨论

**Comment by neronkl** [comment]
数字控件的输入，无论怎么输入统一为数值类型

数据检查 （枚举字段的枚举值）
- 必填性检查，其中非必填则可使用默认值
- 枚举类型：非法枚举值检查
- 唯一性检查（TODO：当前未涉及）
- 可编辑性检测（TODO：当前为涉及）：这个点主要针对用户编辑

**Comment by neronkl** [comment]
自定义字段的英文标识增加输入规则：`"^[a-zA-Z][a-zA-Z0-9_]{1,30}[a-zA-Z0-9]$"`
枚举字段的options设置，id支持自定义数据，且id/value都不可重复
