### ISSUE TITLE
LDAP同步MAD后，组织架构及用户显示正常，但用户名@域登录后报错账户或者密码错误

### ISSUE THREAD

**Issue by blur1111** [TencentBlueKing/bk-user#1279]
产品： 用户管理2.5.4
版本：社区版6.2 用户管理2.5.4
环境信息： 规格： 三台8C32G 操作系统：Centos7.6
问题描述：
使用LDAP AD域同步账号后，用户名@域 登录显示密码不正确，已确认账号密码无误。 求大神解答
异常截图：
![1696748510374](https://github.com/TencentBlueKing/bk-user/assets/147300430/d9aca4c3-a8a0-415f-a002-5c5f991d4da4)

排查 usermgr 日志无报错，
open_paas/login.log日志有报错报错如下：

ERROR [2023-09-28 15:01:37] ./components/esb.py 69 _call_esb_api 16 139705323570232 
 	 call esb api error! http_post [http://paas.service.consul:80/api/c/compapi/v1/usermanage/login/check/](http://paas.service.consul/api/c/compapi/v1/usermanage/login/check/), data: {'username': 'ex-wangzhaobo001', 'password': 'wan******', 'domain': 'test', 'bk_app_code': 'bk_paas', 'bk_app_secret': 'b35******', 'bk_username': 'admin', 'app_code': 'bk_paas', 'app_secret': 'b35******'}, code: 3210013, message: 账户或者密码错误，请重新输入 

ERROR [2023-09-28 15:02:25] ./components/esb.py 69 _call_esb_api 31 139705323535720 
 	 call esb api error! http_post [http://paas.service.consul:80/api/c/compapi/v1/usermanage/login/check/](http://paas.service.consul/api/c/compapi/v1/usermanage/login/check/), data: {'username': 'ex-gebaolei001', 'password': 'GbL******', 'domain': 'test', 'bk_app_code': 'bk_paas', 'bk_app_secret': 'b35******', 'bk_username': 'admin', 'app_code': 'bk_paas', 'app_secret': 'b35******'}, code: 3210013, message: 账户或者密码错误，请重新输入 

ERROR [2023-09-28 15:02:36] ./components/esb.py 69 _call_esb_api 31 139705323535720 
 	 call esb api error! http_post [http://paas.service.consul:80/api/c/compapi/v1/usermanage/login/check/](http://paas.service.consul/api/c/compapi/v1/usermanage/login/check/), data: {'username': 'zhangpeijie', 'password': '261******', 'domain': 'test', 'bk_app_code': 'bk_paas', 'bk_app_secret': 'b35******', 'bk_username': 'admin', 'app_code': 'bk_paas', 'app_secret': 'b35******'}, code: 3210013, message: 账户或者密码错误，请重新输入
账号同步信息一致，如下：
![image](https://github.com/TencentBlueKing/bk-user/assets/147300430/b1ef89d5-efd1-4d53-8131-619e0dbc6468)
用户管理-审计 界面如下：
![image](https://github.com/TencentBlueKing/bk-user/assets/147300430/00f246f4-6b5e-4c75-bc34-a79385fb39c6)

**Comment by neronkl** [comment]
可去用户管理的后台，查看日志

**Comment by nannan00** [comment]
日志级别调整为DEBUG，然后查询日志是否有LDAP相关的信息（需查看代码里打印的日志关键字）

LDAP/MAD 校验密码的代码逻辑： 
https://github.com/TencentBlueKing/bk-user/blob/develop/src/api/bkuser_core/categories/plugins/mad/login.py#L18
https://github.com/TencentBlueKing/bk-user/blob/develop/src/api/bkuser_core/categories/plugins/ldap/login.py#L32

**Comment by blur1111** [comment]
各位老师，目前usermgr/api.log 报错如下，麻烦请教下如下报错如何处理
INFO [2023-10-09 15:48:08] 106 search 1284 140605046284616
going to search (&(objectClass=user)(sAMAccountName=ex-gebaolei001)) from OU=***公司,dc=xhafz,dc=com

ERROR [2023-10-09 15:48:09] 205 login 1284 140605046284616
login check, check profile<ex-gebaolei001> of username=ex-gebaolei001, domain=test in category<mad-测试-5> failed
Traceback (most recent call last):
  File "/data/bkce/usermgr/api/bkuser_core/api/login/views.py", line 197, in login
    login_class().check(profile, password)
  File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/login.py", line 69, in check
    client.check(username=target_dn, password=password)
  File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/client.py", line 130, in check
    conn.extend.standard.who_am_i()
  File "/cache/.bk/env/lib/python3.6/site-packages/ldap3/extend/__init__.py", line 66, in who_am_i
    controls).send()
  File "/cache/.bk/env/lib/python3.6/site-packages/ldap3/extend/operation.py", line 51, in send
    raise LDAPExtensionError('extension not in DSA list of supported extensions')
ldap3.core.exceptions.LDAPExtensionError: extension not in DSA list of supported extensions

**Comment by nannan00** [comment]
> 各位老师，目前usermgr/api.log 报错如下，麻烦请教下如下报错如何处理 INFO [2023-10-09 15:48:08] 106 search 1284 140605046284616 going to search (&(objectClass=user)(sAMAccountName=ex-gebaolei001)) from OU=***公司,dc=xhafz,dc=com
> 
> ERROR [2023-10-09 15:48:09] 205 login 1284 140605046284616 login check, check profile of username=ex-gebaolei001, domain=test in category<mad-测试-5> failed Traceback (most recent call last): File "/data/bkce/usermgr/api/bkuser_core/api/login/views.py", line 197, in login login_class().check(profile, password) File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/login.py", line 69, in check client.check(username=target_dn, password=password) File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/client.py", line 130, in check conn.extend.standard.who_am_i() File "/cache/.bk/env/lib/python3.6/site-packages/ldap3/extend/**init**.py", line 66, in who_am_i controls).send() File "/cache/.bk/env/lib/python3.6/site-packages/ldap3/extend/operation.py", line 51, in send raise LDAPExtensionError('extension not in DSA list of supported extensions') ldap3.core.exceptions.LDAPExtensionError: extension not in DSA list of supported extensions

使用Chatgpt 查询到的回答 ：

<img width="1168" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/17491932/74255e7e-9963-4838-acd2-c14b504c73d3">

**Comment by blur1111** [comment]
各位老师，目前这个问题，还是没有找到解决办法

**Comment by neronkl** [comment]
当前你的ldap服务缺少who_am_i的这个协议，或许你可以研究一下如何配置该协议，或者通过插件的形式进行配置
