### ISSUE TITLE
【多租户】租户账号设置-账号有效期

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#1280]
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/2f54e663-9ec6-4cae-99ab-c8ea2d3ef148)

**Comment by neronkl** [comment]
## 1. 租户设置-配置元信息

## 1.1 引入配置元信息

账户有效期是所有租户共有的配置项，抽象化成配置元信息，租户设置和配置元信息成映射关系

### 1.1.1 模型设计

`TenantSettingMeta`： 租户元设置

| 字段名称  | 类型 | 默认值 | 说明     |
| --------- | ---- | ------ | -------- |
| key       | str  | 无     | 配置键   |
| default   | str  | 无     | 默认值   |
| choices   | json | 无     | 可选值   |
| required  | bool | True   | 是否必要 |
| namespace | str  | 无     | 命名空间 |
| enabled   | bool | True   | 使能值   |

`TenantSetting`： 租户设置

| 字段名称  | 类型 | 说明         |
| --------- | ---- | ------------ |
| meta_id   | int  | 元配置信息ID |
| value     | str  | 配置值       |
| tenant_id | str  | 配置所属租户 |
| enabled   | bool | 使能值       |



## 2. 租户设置-账户有效期以及过期提醒设置

### 2.1 接口设计

### 2.1.1 获取当前租户设置

- url：`api/v1/web/tenants/<id:str>/settings/namespaces/<namespace:str>/`

- method:` GET`

- request

| 字段名称  | 类型 | 必填 | 说明         | 位置 |
| --------- | ---- | ---- | ------------ | ---- |
| id        | str  | 是   | 租户用户ID   | path |
| namespace | str  | 是   | 设置名称空间 | path |

- response 

  - data

    | 字段名称 | 类型 | 说明           |
    | -------- | ---- | -------------- |
    | id       | int  | ID             |
    | key      | str  | 配置键         |
    | value    | json | 配置键值       |
    | defalut  | str  | 配置键默认值   |
    | choices  | list | 配置键值可选项 |
    | enabled  | bool | 使能值         |



### 2.1.2 更新当前租户设置

- url：`api/v1/web/tenants/<id:str>/settings/namespaces/<namespace:str>/`

- method:` PUT`

- request

| 字段名称  | 类型 | 必填 | 说明         | 位置 |
| --------- | ---- | ---- | ------------ | ---- |
| id        | str  | 是   | 租户用户ID   | path |
| namespace | str  | 是   | 设置名称空间 | path |
| key       | str  | 是   | 配置键       | body |
| value     | json | 是   | 配置键值     | body |
| enabled   | bool | 是   | 使能值       | body |



### 2.2 方案逻辑

1. 增加-账号有效期元信息配置项

   ```python
   # 账号有效期
   {
   	"key":"expired_after_days",
       "default":-1,
       "choices": [-1, 30, 90, 180, 365] # 永久：-1，单位:days
       "namespace": "account"
       "enabled": True
   }
   
   # 发送周期
   {
   	"key":"account_expiration_notice_interval",
       "default":[1, 7, 15],
       "choices": [1, 7, 15],
       "namespace": "account"
       "enabled": True
   }
   
   # 发送方式
   {
   	"key":"account_expiration_notice_methods",
       "default":["email"],
       "choices": ["email", "sms"],
       "namespace": "account"
       "enabled": True
   }
   
   # 临过期发送提醒（邮件模板）
   {
   	"key":"expiring_account_email_template",
       "default":{
           "title": "蓝鲸智云 - 账号到期提醒", 
           "sender": "蓝鲸智云",
           "content": "{username}，您好：您的蓝鲸智云平台账号将于{expired_at}天后到期，为避免影响使用，请尽快联系平台管理员进行续期。蓝鲸智云平台用户管理处",
           "content_html": "<p>{username}，您好：</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您的蓝鲸智云平台账号将于<span style=\"color: rgb(225, 60, 57);\">{expired_at}</span>天后到期，为避免影响使用，请尽快联系平台管理员进行续期。</p><p style=\"text-align: right;\">蓝鲸智云平台用户管理处</p>"
       },
       "choices": [],
       "namespace": "account"
       "enabled": True
   }
   
   # 临过期发送提醒（短信模板）
   {
   	"key":"expiring_account_sms_template",
       "default":{
           "sender": "蓝鲸智云", 
           "content": "【蓝鲸智云】账号到期提醒！{username}，您好，您的蓝鲸平台账号将于{expired_at}天后到期，为避免影响使用，请尽快联系平台管理员进行续期。", 
           "content_html": "<p>【蓝鲸智云】账号到期提醒！{username}您好，您的蓝鲸平台账号将于{expired_at}天后到期，为避免影响使用，请尽快联系平台管理员进行续期。</p>"
       },
       "choices": [],
       "namespace": "account"
       "enabled": True
   }
   
   # 过期发送提醒（邮件模板）
   {
   	"key":"expired_account_email_template",
       "default":{"title": "蓝鲸智云 - 账号到期提醒", "sender": "蓝鲸智云", "content": "{username}，您好：您的蓝鲸智云平台账号已过期，为避免影响使用，请尽快联系平台管理员进行续期。蓝鲸智云平台用户管理处", "content_html": "<p>{username}，您好：</p><p style=\"text-align: left;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您的蓝鲸智云平台账号已过期，为避免影响使用，请尽快联系平台管理员进行续期。</p><p style=\"text-align: right;\">蓝鲸智云平台用户管理处</p>"},
       "choices": [],
       "namespace": "account"
       "enabled": True
   }
   
   # 过期发送提醒（短信模板）
   {
   	"key":"expired_account_sms_template",
       "default":{"sender": "蓝鲸智云", "content": "【蓝鲸智云】账号到期提醒！{username}，您好，您的蓝鲸智云平台账号已过期，为避免影响使用，请尽快联系平台管理员进行续期。", "content_html": "<p>【蓝鲸智云】账号到期提醒！{username}您好，您的蓝鲸平台账号已到期，为避免影响使用，请尽快联系平台管理员进行续期。</p>"},
       "choices": [],
       "namespace": "account"
       "enabled": True
   }
   
   ```

   

2. 租户设置-账号有效期设置

   根据上面的元配置信息，生成配置项目

   - 新增的租户默认生成配置信息

   - 存量租户补充配置信息

   

3. 租户账号有效期设置

   - 当前存量用户的有效期默认为永久（account_expired_time=-1）,是否需要重新适配？

   - 新增的租户用户则是：account_expired_time = now + 租户设置，如果租户设置为永久，则account_expired_time 则为默认值：2100.1.1
   - 新增周期任务：扫描临过期用户，发送提醒邮件
   - 新增周期任务：已过期用户，发送提醒邮件

**Comment by neronkl** [comment]
和@Xmandon讨论， 租户账号续期，暂不开放。

**Comment by narasux** [comment]
1. 为什么需要抽象 TenantSettingMeta，放一个完整的 model 会有什么问题？

看下预留的 bkuser.apps.tenant.models.AccountValidityPeriodConfig

2. 没理解接口设计中的 "命名空间" 的作用，看起来是老版本中区分不同的 meta 类型，但是我们是否需要这么灵活的设计？

---

建议：
1. 不要使用过于灵活的 Meta 设计，用传统的 Model 即可
2. 邮件/短信配置可参考本地数据源配置建模（通知部分）

**Comment by neronkl** [comment]
1. 去掉TenantSettingMeta，
2. 但是感觉不可直接使用AccountValidityPeriodConfig，调整TenantSetting(TenantCommonConfig)字段设计，
3. namespace来进行区分设置类型，考虑到后续设置扩展：租户登录设置，需要保留
4. 邮件/短信配置将会通过NotificationTemplate的协议进行

**Comment by narasux** [comment]
enabled_account_expiration -> enable_account_expiration
validity_period_days -> valid_time
notification_content_template -> notification_template

```json5
{
    "enable_account_expiration": true,         // 是否启用账号有效期设置
    "valid_time": "-1",                        // 有效期，单位：天
    "remind_before_expire": [7, 15]            // 临X天过期发送提醒
    "enabled_notification_methods": ["email"]  // 通知方式
    "notification_templates": [                // 通知模板
        {
            "method": "email",
            "scene": "account_expiring",
            "title": "蓝鲸智云 - 账号即将到期提醒",
            "sender": "蓝鲸智云",
            "content": "{{ username }}，您好：您的蓝鲸智云平台账号将于 {{ expired_at }} 天后到期，为避免影响使用，请尽快联系平台管理员进行续期。此邮件为系统自动发送，请勿回复。",
            "content_html": "<p>{{ username }}，您好：</p><p>您的蓝鲸智云平台账号将于 {{ expired_at }} 天后到期，为避免影响使用，请尽快联系平台管理员进行续期。</p><p>此邮件为系统自动发送，请勿回复。</p>"
        },
        {
            "method": "email",
            "scene": "account_expired",
            "title": "蓝鲸智云 - 账号到期提醒",
            "sender": "蓝鲸智云",
            "content": "{{ username }}，您好：您的蓝鲸智云平台账号已过期，如需继续使用，请尽快联系平台管理员进行续期。此邮件为系统自动发送，请勿回复。",
            "content_html": "<p>{{ username }}，您好：</p><p>您的蓝鲸智云平台账号已过期，如需继续使用，请尽快联系平台管理员进行续期。</p><p>此邮件为系统自动发送，请勿回复。</p>"
        },
        {
            "method": "sms",
            "scene": "account_expiring",
            "title": null,
            "sender": "蓝鲸智云",
            "content": "{{ username }}，您好：您的蓝鲸智云平台账号将于 {{ expired_at }} 天后到期，为避免影响使用，请尽快联系平台管理员进行续期。此邮件为系统自动发送，请勿回复。",
            "content_html": "<p>{{ username }}，您好：</p><p>您的蓝鲸智云平台账号将于 {{ expired_at }} 天后到期，为避免影响使用，请尽快联系平台管理员进行续期。</p><p>此邮件为系统自动发送，请勿回复。</p>"
        },
        {
            "method": "sms",
            "scene": "account_expired",
            "title": null,
            "sender": "蓝鲸智云",
            "content": "{{ username }}，您好：您的蓝鲸智云平台账号已过期，如需继续使用，请尽快联系平台管理员进行续期。此邮件为系统自动发送，请勿回复。",
            "content_html": "<p>{{ username }}，您好：</p><p>您的蓝鲸智云平台账号已过期，如需继续使用，请尽快联系平台管理员进行续期。</p><p>此邮件为系统自动发送，请勿回复。</p>"
        }
    ]
}
```

**Comment by narasux** [comment]
2.1.1

api/v1/web/tenant-setting/settings/account-validity-period/default/

account_expiration 不能很好表示有效期，另外需要优先使用中划线

data 字段参考上一个评论修改下

2.1.2， 2.1.3 同上

2.2

存量租户（测试数据），可以直接 manage shell 生成配置，不需要提供 migration

重置账号有效期，需要前端二次确认弹窗

**Comment by nannan00** [comment]
0. 不要体现account，而应该是TenantUser
1.1 表字段名修改：
  - enable_account_expiration => enabled
  - enable_account_expiration  => validity_period
2 URL调整
  - /api/v1/web/tenant-setting/settings/tenant-user-validity-period/default-config
  - /api/v1/web/tenant-setting/settings/tenant-user-validity-period/

**Comment by neronkl** [comment]
- 账户有效期功能处于启用状态，更新有效期设置，用户的有效期

     |                        | 有效期变更为1个月 | 有效期变更为3个月 | 有效期变更为6个月 | 有效期变更为1年 | 有效期变更为永久 |
     | ---------------------- | ----------------- | ----------------- | ----------------- | --------------- | ---------------- |
     | 存量用户【过期用户】   | 不处理            | 不处理            | 不处理            | 不处理          | 不处理           |
     | 存量用户【未过期用户】 | 不处理            | 不处理            | 不处理            | 不处理          | 不处理           |
     | 存量用户【永久用户】   | 不处理            | 不处理            | 不处理            | 不处理          | 不处理           |
     | 新增用户               | now()+30d         | now()+60d         | now()+90d         | now()+365d      | 2100/1/1         |

     

禁用账户有效期功能 **enabled_validity_period=False**

   - 账户有效期功能从启用状态变更为禁用状态，用户的有效期如何处理

   |              | 配置更新有效期设置      |
   | ------------ | ----------------------- |
   | 已过期的用户 | 保持不变                |
   | 未过期用户   | 保持不变                |
   | 永久用户     | 保持不变                |
   | 新增的用户   | **valid_time=2100.1.1** |

   **临过期/过期提醒仍正常执行**

   

重启启用账户有效期功能 **enabled_validity_period=False => True**

   - 账户有效期功能从禁用状态变更为启用状态

   |              | 配置更新有效期设置 |
   | ------------ | ------------------ |
   | 已过期的用户 | 保持不变           |
   | 未过期用户   | 保持不变           |
   | 永久用户     | 保持不变           |
   | 存量用户【功能禁用期间，产生】 | 保持不变           |
   | 新增的用户   | now() + 配置       |

**Comment by neronkl** [comment]
- [x] 提供设置的获取/更新接口
- [x] 新建租户用户根据配置，做有效期设置
- [ ] 过期/临期通知-异步执行
- [ ] 登录拦截过期任务
