### ISSUE TITLE
SaaS 个人信息展示

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#1316]
v3 版本，用户管理&登录对外的username/bk_username 的值 可能是 uuid，这对于用户来说的不可读的
- 需要通过display_name来展示
- [初期] display_name 可以直接是 数据源的username，也可以是 full_name
- [后期] display_name 需要支持表达式配置

具体展示的场景：
- 一般 SaaS 右上角个人信息显示
- 各种“记录”的创建者 / 更新者 / 执行者 等等

**Comment by neronkl** [comment]
## 1. 租户设置-配置信息

### 1.1 模型设计

`TenantUserDisplayNameConfig`： 租户-名称展示设置

| 字段名称   | 类型 | 默认值                 | 说明         |
| ---------- | ---- | ---------------------- | ------------ |
| tenant_id  | str  |                        | 配置所属租户 |
| expression | str  | {username}({fullname}) | 名称表达式   |



## 2 涉及的展示场景

- 页面右上角的登录用户基础信息。
- 数据源更新的updater展示
- 认证源更新的updater展示
- 数据源同步记录operator

以上的展示，需根据当前租户的display_name表达式设置进行展示，

```python
# 数据源/认证源slz层
class XXXXOutputSLZ
	....
	updater = serializer.SerializerMethodField
	
	def get_updater(self, instance):
		return 根据名称表达式生成的value

# 数据更新记录
class DataSourceSyncRecordListOutputSLZ(serializers.Serializer):
    ....
    operator = serializers.SerializerMethodField
    
    def get_operator(self, instance):
		return 根据名称表达式生成的value

```





## 3 接口

### 3.1 展示display_name表达式

- api：`/api/v1/web/tenant-setting/settings/tenant-user-display-name-expression/`

- method：GET

- response

  - data 

    | 字段名称   | 类型 | 说明       |
    | ---------- | ---- | ---------- |
    | expression | str  | 名称表达式 |

### 3.2 编辑display_name表达式

- api：`/api/v1/web/tenant-setting/settings/tenant-user-display-name-expression/`

- method：PUT

- response

  - data 

    Null

### 3.3 当前登录用户接口

- api：`/api/v1/web/basic/current-user/`

- method：GET

- response

  - data 

    新增字段display_name

| 字段名称     | 类型 | 说明     |
| ------------ | ---- | -------- |
| display_name | str  | 名称展示 |

**Comment by narasux** [comment]
关联 issue：https://github.com/TencentBlueKing/bk-user/issues/442

**Comment by narasux** [comment]
第 2 点 用户管理展示场景：
slz 中获取 display_name 应该是从 context 中获取，否则会有 N+1 问题，构造该 context 的 handler 可以放在 biz 层

第 4 点 API 接口设计：
不在这里提供 logo
