### ISSUE TITLE
多租户版本部署支持

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1327]
预计排期：23.11.20 - 12.10

- 容器化版本
  - [x] Dockerfile
  - [x] 镜像构建流水线
  - [x] Helm Chart
    - [x] 环境变量（values.yaml） 
    - [ ] 第三方插件挂载 & 依赖 https://github.com/TencentBlueKing/bk-user/issues/1310

**Comment by nannan00** [comment]
1. ingress 支持多种controller 可以在values定义规则，特别是login模块
2. bk-login和bk-user 支持挂载plugin
3. 支持通过values 随时添加环境变量

**Comment by nannan00** [comment]
* 二进制版本的登录是与PaaS V2耦合的，并不在用户管理项目里，多租户版本将改为使用用户管理项目里的登录
    - 需要梳理出之前与PaaS V2开发者中心、桌面、ESB等PaaS套件的调用关注，可能还需要相关系统做兼容改造？
* 登录无论是二进制版还是容器化版，域名都是与桌面等共享的，通过/login/子路径来区分的，新版本部署需要兼容

**Comment by narasux** [comment]
https://git.woa.com/blueking/helm-charts/blob/master/bk-user/charts/api/values.yaml#L96

HelmChart 需要支持默认超级管理员的初始化
