### ISSUE TITLE
各维度对象的状态流转和生命周期

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1343]
对象：租户、数据源、数据源用户、数据源部门、租户用户、租户部门、认证源

状态：软删除(不可用)、停用(冻结)、正常、过期等等

生命周期：产生(如何产生，特别是有多的地方产生)以及关联产生、软删除、硬删除(回收站功能)、恢复、停用/启用、有效期？

涉及每个对象的生命周期&状态流转以及影响的功能（比如租户停用则用户无法切换到该租户、用户不可登录等等）

**Comment by nannan00** [comment]
关联 issue：
- https://github.com/TencentBlueKing/bk-user/issues/1351

**Comment by narasux** [comment]
### 租户

**Comment by narasux** [comment]
### 数据源

**Comment by narasux** [comment]
### 数据源用户

同步遇上软删除/停用？怎么处理这个场景？

**Comment by narasux** [comment]
### 租户用户

**Comment by narasux** [comment]
### 数据源部门

**Comment by narasux** [comment]
### 租户部门

**Comment by narasux** [comment]
回收站

- 数据软删除后会进入到回收站，默认保留 30 天，30 天后会有定时任务进行清理

**Comment by narasux** [comment]
所有停用，删除按钮都需要二次弹窗确认，并告知用户该操作的影响范围

**Comment by narasux** [comment]
前端配合调整：
- 数据源用户页面
    - 状态为 disabled 的用户，编辑 / 重置密码 按钮需要禁用
