### ISSUE TITLE
ldap/mad 同步插件，重新同步之前被删除部门，同步异常

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#1428]
**用文字描述你遇到的问题**
ldap/mad 同步插件，重新同步之前被删除部门，同步异常

**重现方法**

ldap/mad 同步插件，部门同步异常：
1. 首次同步成功
2. 二次同步，将某个测试部门在ad做删除操作
3. 三次重新同步，在ad重新启用被删除部门， 此时的同步会提示该部门的code异常

**预期行为**

重新启用的部门，同步正常

**版本**
- 2.4.3 （2.5.4版本也会存在该问题)

- 是否是企业版问题？
是

**Comment by neronkl** [comment]
经过排查：
1. 部门入库前，会暂且在内存中保存。
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/95a831e9-b747-4f28-9d23-cbb9e4408f04)
2. 写入内部前，会和当前enabled=1的部门做比对（更新/新建）
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/077ffd2b-66a6-4acb-a5fd-5521aac5a5aa)
![image](https://github.com/TencentBlueKing/bk-user/assets/49228807/6cd5b4f5-f169-4a12-9b92-95fb592a94c5)

**Comment by neronkl** [comment]
问题在于，只和enabled=1的部门做比对，而不是当前目录下的所有部门做比对。导致重新激活的部门，入库会产生异常：部门code冲突
`django.db.utils.IntegrityError: (1062,"xxxxxxxx’ for key 'code"")`

**Comment by nannan00** [comment]
参考FAQ: https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1128778024
