### ISSUE TITLE
评估 & 处理自定义字段增删改对数据 / 同步流程的影响

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1431]
增删改自定义字段可能导致的问题：

### 增加

本地数据源
- 如果是不覆盖的导入，则存量数据永远不会被更新
- 页面上展示 / 编辑用户时候，会有空值问题（无数据）

非本地数据源
- 在没有更新数据源字段映射的情况下，新增的自定义字段都不会被同步
- 页面上展示用户时候，会有空值问题（无数据）

### 删除

本地数据源
- 如果是不覆盖的导入，则存量数据永远不会被更新
- 存量数据有脏数据（extras）

非本地数据源
- 在没有更新数据源字段映射的情况下，被删除的自定义字段还是会被同步

### 改动（改枚举值/必填/唯一属性）

本地数据源
- 增加枚举：影响比较小
- 删除枚举：存量数据导出再导入 / 页面上更新用户保存会失败
- 修改必填/唯一属性：可能会有存量数据变得不合法，影响和删除枚举类似

非本地数据源：
- 同步可能会失败（因为原来的数据不一定满足新的规则）

**Comment by Xmandon** [comment]
删除（异步）
-----
1. 本地数据源：同时删除实例数据
2. 非本地数据源：后台自动去掉该字段的映射配置，同时删除实例数据

修改：
1. 删除枚举时，需要让用户重新指定新的枚举值，需要设计支持
