### ISSUE TITLE
[v2升级v3] 用户管理 OpenAPI 兼容

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1444]
### 提供OpenAPI调用的统计的方法
- 可以提供脚本或者运维相关命令指引等方式
- 统计内容包括
    - 每个API的请求参数（只开放了查询接口，都是GET接口）
    - 请求量
    - 调用方

### 涉及的核心 API: 

- 用户类 @nannan00 
  - [x] /api/v2/profiles/{lookup_value}/ 查询单个用户信息
  - [x] /api/v2/profiles/ 查询用户列表
  - [x] /api/v2/departments/{id}/profiles/ 查询部门下用户列表
- 部门类 @narasux 
  - [x] /api/v2/departments/{id}/ 查询单个部门信息
  - [x] /api/v2/departments/ 查询部门列表
  - [x] /api/v2/departments/{lookup_value}/children/ 子部门列表(只是直接子部门，并非子孙)
  - [x] /api/v2/profiles/{lookup_value}/departments/ 查询单个用户的部门列表
- 其他 @narasux 
  - [x] /api/v2/categories 查询目录列表
  - [x] /api/v2/edges/department_profile/ 部门与用户关系列表
  - [x] /api/v2/edges/leader/ 用户Leader关系列表

### 非核心 API:
- [x] /api/v2/profiles/{id}/languages/ [PUT/GET] 查询用户设置的语言

### ESB 定制接口：
- [x] https://github.com/TencentBlueKing/blueking-apigateway/blob/master/src/esb/esb/components/bk/apisv2/usermanage/

**Comment by nannan00** [comment]
- 缓存
- 对应3.x 版本里哪个概念数据
- 2.x 对象都对外暴露了哪些字段

-----

对象[profile / department / category ] 列表、 edges [部门之间关系、UserLeader关系]： 
- fields: 返回对象的字段列表，空则返回所有字段
    - 对象profile：允许包含relation字段，比如departments、leader
    - 对象department:  full_name、has_children
- lookup_field： 指定过滤或搜索字段，只能一个字段
- exact_lookups：[精准匹配] 过滤时lookup_field指定字段的值， 多个值逗号分隔（多值是Or 关系）
- fuzzy_lookups： [模糊匹配] 搜索时lookup_field指定字段的值，多个值逗号分隔（多值是Or 关系）
- wildcard_search： 【多个字段模糊匹配的keyword 】 与 fuzzy_lookups/exact_lookups 是 AND 关系，即这是另外的模糊匹配
- wildcard_search_fields: 【多个字段模糊匹配】 与 wildcard_search 一起使用，支持多个字段， 多个字段是 OR 关系
- best_match：【排序】使用fuzzy_lookups进行模糊匹配时， 匹配到的字段记录，值长度小的记录排前面，比如 搜索到 abcdedf,  abcd，那边 abcd的记录会在 abcdedf 前面
- ordering：返回数据的排序字段，逆序添加-， 多个字段使用逗号分隔
- page / page_size / no_page : 分页相关
- include_disabled: 是否包含软删除的记录
- 【部门特有】 with_ancestors： 是否返回祖先列表

-----

单一对象[profile / department / category ]：
- path 参数： 对于profile，通过lookup_field指定path key 是 id或username， value可能是包含domain也可能不包括
- fields: 返回对象的字段列表，空则返回所有字段
    - 对象profile：允许包含relation字段，比如departments、leader
    - 对象department:  full_name、has_children, children
- include_disabled: 是否包含软删除的记录
-  with_ancestors(兼容with_family)： 是否返回祖先列表
  - 对于department:  与children字段返回是二选一，有祖先无子孙、有子孙无祖先
  - 对于 profile: 则返回用户所属部门列表时是否还要包括部门的祖先， 即Department记录多了family字段

**Comment by nannan00** [comment]
### /api/v2/profiles/{lookup_value}/ 查询单个用户信息

- 路径参数：
  - 通过 lookup_field 指定路径参数值的字段是 id 还是 username, 默认是 username
  - 对于 username，解析出 username 和 domain 进行 DB 唯一性查询

- fields: 返回所需用户字段
  - 允许的字段：
    - 基本字段：
      - id, username, email, telephone, logo, extras, code, display_name, position
      - time_zone, language, country_code, iso_code, qq, wx_userid, wx_openid
      - domain, category_id
      - status, staff_status, enabled
    - 其他字段：password_valid_days, password_update_time, last_login_time, account_expiration_date, create_time, update_time
    - 废弃字段：type, role
    - 关联字段：
      - departments：[{id, name, full_name, order}]
      - leader: [{id, username, display_name}]
  - 默认为空，返回所有字段

- 问题：
  - code 在旧插件、新插件、新旧数据迁移的不一致问题

**Comment by nannan00** [comment]
### /api/v2/departments/{id}/ 查询单个部门信息
- fields: 返回所需的部门字段
  - 允许字段：
    - 基本字段：
      - id, name, code, extras
      - category_id, parent
      - enabled
    - MPTT字段：order, lft, rght, tree_id, level
  - 默认为空，返回所有字段

- with_ancestors 是否包括祖先
  - 返回字段 ancestors: [{id, name}]

- 当 fields 为空时，额外返回字段
  - full_name
  - has_children
  - children: [{id, name, full_name, has_children}]
- 只要指定了fields, 那么返回一定是按照 fields 的字段返回，比如在指定fields情况下，即使使用with_ancestors参数，也不会返回ancestors

**Comment by nannan00** [comment]
### /api/v2/profiles/ 查询用户列表

- fields: 返回所需用户字段
  - 允许的字段：
    - 基本字段：
      - id, username, email, telephone, logo, extras, code, display_name, position
      - time_zone, language, country_code, iso_code, qq, wx_userid, wx_openid
      - domain, category_id
      - status, staff_status, enabled
    - 其他字段：password_valid_days, password_update_time, last_login_time, account_expiration_date, create_time, update_time
    - 废弃字段：type, role
    - 关联字段：
      - departments：[{id, name, full_name, order}]
      - leader: [{id, username, display_name}]
  - 默认为空，返回所有字段

- lookup_field + exact_lookups 或 lookup_field + fuzzy_lookups: 指定一个字段进行精确或模糊匹配
  - lookup_field: Profile Model 所有字段，由于并没有对 lookup_field 约束，所以理论上支持 leader__ 这类的
  - exact_lookups: [Or(Q(equal), ...)] 精确查询 lookup_field 所指定的字段, 支持多选，以逗号分隔
  - fuzzy_lookups: [Or(Q(__icontains), ...)] 模糊查询 lookup_field 所指定的字段, 支持多选，以逗号分隔
  - 特殊 lookup_field=username :
    - 使用 ```if(`domain`=%s, `username`, CONCAT(`username`, "@", `domain`))=%s``` 构造 where 条件
    - 使用 ```if(`domain`=%s, `username`, CONCAT(`username`, "@", `domain`)) LIKE %{value}%``` 构造 where 条件
    - 其中 domain 是指 default domain
  - best_match，是否按照最短匹配排序，只对 fuzzy_lookups 有效
    - 比如 lookup_field = username, fuzzy_lookups = abc，那么匹配到 username=abcdefg (长度 7)的记录会在 username=abcdefgh (长度 8)的前面
- wildcard_search + wildcard_search_fields: 指定多个字段模糊匹配，[Or(Q(__icontains), ...)]
  - wildcard_search_fields: 指定多个字段，以逗号分隔
  - wildcard_search: 模糊匹配的值，只支持一个值
- include_disabled: 是否包含软删除的记录，即 enabled=False 的记录

**Comment by nannan00** [comment]
### /api/v2/departments/ 查询部门列表
- fields: 返回所需的部门字段
  - 允许字段：
    - 基本字段：
      - id, name, code, extras
      - category_id, parent
      - enabled
    - MPTT字段：order, lft, rght, tree_id, level
  - 默认为空，返回所有字段

- with_ancestors 是否包括祖先（Note: 只有fields为空时才生效，因为fields是不支持指定 ancestors 的）
  - 返回字段 ancestors: [{id, name}]
  - 返回字段 children: [{id, name, full_name, has_children}]

- 当 fields 为空时，额外返回字段
  - full_name
  - has_children

- lookup_field + exact_lookups 或 lookup_field + fuzzy_lookups: 指定一个字段进行精确或模糊匹配
- wildcard_search + wildcard_search_fields: 指定多个字段模糊匹配，[Or(Q(__icontains), ...)]
- include_disabled: 是否包含软删除的记录，即 enabled=False 的记录

**Comment by nannan00** [comment]
### /api/v2/categories 查询目录列表
- fields: 返回所需的部门字段
  - 允许字段：
    - id, display_name, type, description
    - domain, default
    - enabled, status
    - create_time, update_time, order, last_synced_time
  - 默认为空，返回所有字段
- lookup_field + exact_lookups 或 lookup_field + fuzzy_lookups: 指定一个字段进行精确或模糊匹配
- wildcard_search + wildcard_search_fields: 指定多个字段模糊匹配，[Or(Q(__icontains), ...)]
- include_disabled: 是否包含软删除的记录，即 enabled=False 的记录

**Comment by nannan00** [comment]
### /api/v2/profiles/{lookup_value}/departments/ 查询单个用户的部门列表

- 路径参数：
  - 通过 lookup_field 指定路径参数值的字段是 id 还是 username, 默认是 username
  - 对于 username，解析出 username 和 domain 进行 DB 唯一性查询

- include_disabled: 是否支持返回软删除用户的部门，默认是false， 对于 false，则查询的用户被软删除了则 raise 404
- with_ancestors(或 with_family): 是否返回祖先
    - False 或 无参数，返回: [{id, name, full_name, order}]
    - True，返回：[{id, name, family}]
      - family 值是列表: [{id, name, full_name, order}]
- 列表排序：order_by("-level", "lft")

**Comment by nannan00** [comment]
### /api/v2/departments/{id}/profiles/ 查询部门下用户列表
- include_disabled: 是否支持返回软删除部门的用户，这里部门指路径参数里的ID，默认是false，对于 false，则查询的部门被软删除了则 raise 404
- recursive: 是否递归
- wildcard_search: 模糊查找用户的 username & display_name 字段
- 返回字段(无法通过参数指定)：
  - 基本字段：
    - id, username, email, telephone, logo, extras, display_name, position
    - time_zone, language, country_code, iso_code, qq, wx_userid
    - domain, category_id
    - status, staff_status, enabled
  - 其他字段：password_valid_days, last_login_time, account_expiration_date, create_time, update_time
  - 关联字段：
    - departments：[{id, name, full_name, order}]
    - leader: [{id, username, display_name}]
- 返回特殊逻辑说明：
  - 只返回 enabled=True 的用户
  - last_login_time 字段值在该接口返回时都是 None
  - 无返回字段：code、wx_openid、password_update_time、type, role
  - 存在 BUG，不分页情况下，没有过滤掉敏感字段数据

**Comment by nannan00** [comment]
### /api/v2/edges/department_profile/ 部门与用户关系列表
- 返回字段：id, department_id, profile_id
- 只返回 profile__enabled=True, department__enabled=True 的数据
- page / page_size / no_page : 分页相关
- 实际上也支持，只是字段局限在了 id, department_id, profile_id
  - lookup_field + exact_lookups 或 lookup_field + fuzzy_lookups
  - wildcard_search + wildcard_search_fields: 指定多个字段模糊匹配，[Or(Q(__icontains), ...)]

### /api/v2/edges/leader/ 用户Leader关系列表
- 返回字段：id, from_profile_id, to_profile_id
- 只返回 to_profile__enabled=True, from_profile__enabled=True 的数据
- page / page_size / no_page : 分页相关
- 实际上也支持，只是字段局限在了 id, from_profile_id, to_profile_id
  - lookup_field + exact_lookups 或 lookup_field + fuzzy_lookups
  - wildcard_search + wildcard_search_fields: 指定多个字段模糊匹配，[Or(Q(__icontains), ...)]

**Comment by wklken** [comment]
- with_ancestors / wildcard_search* / include_disabled / recursive 这类, 基于数据样本看下, 如果没有调用直接抹掉好了, 如果调用量少可以考虑跟调用方确认(影响不大直接下掉)
- youti 的自定义登录有一个 `from bklogin.components.usermgr_api import get_profile_by_code` 得看下依赖什么

**Comment by nannan00** [comment]
output slz 全部固定字段，且提供默认值

**Comment by nannan00** [comment]
#### 1. [retrieve_user] /api/v2/profiles/{lookup_value}/
  - lookup_field = "username"
  - fields = ""
  - include_disabled = False

#### 1. [retrieve_department] /api/v2/departments/{lookup_value}/
  - lookup_field = "id"
  - fields = ""
  - include_disabled = False
  - with_ancestors = False

#### 1. [list_users] /api/v2/profiles/
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""

#### 1. [list_departments] /api/v2/departments/
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""
  - with_ancestors = False

#### 1. [list_categories] /api/v2/categories/
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""

#### 1. [list_profile_departments] /api/v2/profiles/{lookup_value}/departments/
  - lookup_field = "username"
  - include_disabled = False
  - with_ancestors = False
  - with_family = False

#### 1. [list_department_profiles] /api/v2/departments/{id}/profiles/
  - lookup_field = "id"
  - no_page = False
  - include_disabled = False
  - recursive = False
  - wildcard_search = ""

#### 1. [list_edges_department_profile] /api/v2/edges/department_profile/
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""

#### 1. [list_edges_leader_profile] /api/v2/edges/leader/
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""

#### 1. [fe_list_users] /api/v2/profiles/
  - 固定了敏感字段数据（https://github.com/TencentBlueKing/blueking-apigateway/blob/db98676be27e65e87381bd2589e2d45d036d1ee4/src/esb/esb/components/bk/apisv2/usermanage/fe_list_users.py#L54）
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""

#### 1. [fs_list_users] /api/v2/profiles/
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - time_field = ""
  - 请求 /api/v2/profiles/ 固定参数：
    - no_page = False
    - best_match = True
    - fields = "id,username,display_name,domain,category_id,log,staff_status"
    - 其他参数则来自对外的请求，只是会使用固定参数进行 dict update
  - 请求 /api/v2/categories/ 固定参数：
    - no_page = True
    - fields = "id,display_name"
  - 对外额外填充了 category_name 字段

#### 1. [get_batch_users] /api/v2/profiles/
  - 固定参数请求：
    - lookup_field = "username"
    - exact_lookups = "From request query param - bk_username_list"
    - no_page = False
    - best_match = True
    - fields = "id,username,display_name,domain,category_id,log,staff_status"

#### 1. [fe_list_departments] /api/v2/departments/
  - 与 list_departments 是等价的，只是该接口只允许前端调用
  - no_page = False
  - fields = ""
  - include_disabled = False
  - lookup_field = ""
  - wildcard_search_fields = ""
  - best_match = False
  - time_field = ""
  - with_ancestors = False

#### 1. [fe_list_department_children] /api/v2/departments/{lookup_value}/children/
  - lookup_field = "id"
  - include_disabled = False

#### 1. [fe_list_department_profiles] /api/v2/departments/{lookup_value}/profiles/
  - 与 list_department_profiles 是等价的，只是该接口只允许前端调用
  - lookup_field = "id"
  - no_page = False
  - include_disabled = False
  - recursive = False
  - wildcard_search = ""

**Comment by nannan00** [comment]
bk_console 需要调整：https://github.com/TencentBlueKing/blueking-console/blob/master/backend/components/usermgr_api.py

**Comment by narasux** [comment]
关联 issue：https://github.com/TencentBlueKing/bk-user/issues/1573
