### ISSUE TITLE
用户管理页面 API 性能优化专项

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1460]
多租户版本中，部分 API 实现逻辑不佳，存在不小的性能问题，需要后续抽时间进行重构

待处理 API：
- [ ] 获取某租户部门下租户用户列表

**Comment by nannan00** [comment]
应该有：数据源部门 -> 租户部门 这两层概念的单独封装，而不是到处直接处理或直接取出底层DB Models数据
