### ISSUE TITLE
个人中心自定义字段使用相关 API

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1474]
目前个人中心为展示自定义字段，调用了需要租户管理员权限的 TenantUserFieldListApi，这是不合理的

需要评估下怎么操作，比如说独立的 api 提供自定义字段信息（不含敏感的默认值，枚举选项等），

但是这样会有一个问题：前端对枚举类型，无法说转换成 value，只能是 id

或者说个人中心的 api 对 extras 进行解包，直接后台处理掉？但是后续如果开放字段编辑，枚举类型不好处理

**Comment by Xmandon** [comment]
字段设置页面，补充字段：
1. 在个人中心展示
2. 编辑：a. 用户管理员可编辑； b. 个人中心可编辑

**Comment by nannan00** [comment]
若 “个人中心可编辑” ，对于 枚举字段，需要提供 用户会看到所有 options
