### ISSUE TITLE
用户重置密码N次内不能相同

### ISSUE THREAD

**Issue by lilacfl** [TencentBlueKing/bk-user#149]
**功能需求背景，例如你遇到了什么问题**

当前用户管理重置密码要求3次内不能相同，沟通几个客户的管理要求，会有大于3次的需求，比如不得与最近5次相同。

**描述你觉得更好的解决方案**

支持变量，用户自定义次数

**额外信息**

任何你觉得有助于理解的信息

**Comment by Xmandon** [comment]
前端增加配置项

**Comment by Xmandon** [comment]
设计稿 ：
https://si9r15.axshare.com
