### ISSUE TITLE
通过google Oauth登录蓝鲸桌面后跳转其他组件失败（无限循环重定向到google认证）

### ISSUE THREAD

**Issue by crazyhuwho** [TencentBlueKing/bk-user#1527]
**用文字描述你遇到的问题**
版本：社区版7.1 K8S部署
单点登录对接了google Oauth，登录成功后进入到蓝鲸桌面，但是当我跳转到其他组件时，比如用户管理组件，能进入到页面，但是会无限循环重定向到google认证

**重现方法**

![image](https://github.com/TencentBlueKing/bk-user/assets/24505465/4a083a8e-8de6-4758-9aa5-734222d0137a)

**Comment by nannan00** [comment]
请自行查看对应的应用日志进行排查

**Comment by crazyhuwho** [comment]
已解决
