### ISSUE TITLE
Release 3.0 版本功能开发评估汇总

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1578]
核心功能：
- 租户管理
- 虚拟账号
- 组织架构
- 管理员配置
- 数据源配置
- 跨租户协同
- 登录设置
- 账号设置
- 字段设置
- 基本设置

--------------
其他功能：
- 消息通知
- 国际化
- 版本日志
- 权限变更：平台管理员 = 默认租户的租户管理员+该租户用户的数据源类型为 builtin_management

--------------
初始化默认租户数据 migration 调整

**Comment by yuri0528** [comment]
租户管理静态页面【1天】

-  新建/编辑、详情

虚拟账号静态页面【1.5天】

- 列表、搜索、删除、新增、编辑

组织架构静态页面【5天】

- 组织树交互
- 列表、搜索
- 导入
- 编辑、详情
- 移动至组织、添加至组织
- 重置密码、删除
- 快速录入、从其他组织拉取

管理员配置静态页面【1天】

- 管理员账号、实名账号

数据源配置静态页面【5天】

- 数据源配置列表
- 导入用户
- 切换数据源
- 企业微信配置、HTTP数据源配置、LDAP数据源配置、本地数据源配置
- 企业微信详情、HTTP数据源详情、LDAP数据源详情、本地数据源详情

跨租户协同静态页面【3.5天】

- 租户列表、搜索、删除
- 新建、编辑、详情
- 数据更新记录

登录设置静态页面【1.5天】

- 登录方式交互
- 账密登录配置、详情
- 企业微信登录配置、详情

账号设置静态页面【0.5天】

基本设置静态页面【0.5天】

**Comment by nannan00** [comment]
| 功能模块 | 工作量 | 关键点 |
|---|---|---|
| 租户管理 | 2天 |  创建租户管理员配置、修改租户管理员配置、查询租户管理配置 |
| 管理员配置 | 2天 | 查看&编辑管理员账号配置、查看编辑管理员实名账号 |
| 基础配置 | 2天 | 查看&编辑租户基本信息(租户可见性、数量可见性) |
| 虚拟账号 | 2天 | 增删改查虚拟账号 |
| 登录配置 | 3天 | 本地登录账密配置(涉及密码)、登录认证字段匹配 |
| 登录流程 | 5天 | 新增协同用户群体 | 
| 消息通知 | 2天 | 涉及登录页面、用户管理页面 |
| 版本日志 | 2天 | 用户管理Markdown 版本日志 |

**Comment by narasux** [comment]
| 功能模块 | 工作量 | 关键点 | 预计 API 时间点 |
| --- | --- | --- | --- |
| 数据源配置 | 3 天 | 创建/切换数据源交互 | 3.27  |
| 组织架构 | 7 天 | 部门新建/管理，部门，用户相关 API 调整 | 4.8 |
| 跨租户协同 | 7 天 | 协同策略（新建/确认/删除），同步机制相关调整 | 4.18 |

**Comment by nannan00** [comment]
| 功能模块 | [前端] 工作量 |  关键点 | 预计可体验时间点 |
|---|---|---|---|
| 租户管理 | [静态]1天 + [联调] 0.5 |  新建/编辑、详情 | 03-26 |

**Comment by yuri0528** [comment]
| 功能模块 | [前端] 工作量 |  关键点 | 预计可体验时间点 |
| 租户管理 | [静态] 1天 + [联调] 0.5天 |  新建/编辑、详情 | 03-25 |
| 管理员配置 | [静态] 1天 + [联调] 0.5天 |  管理员账号、实名账号 | 03-27 |
| 基础配置 | [静态] + [联调] 0.5天 |  用户数量、公司名 | 03-28 |
| 数据源配置 | [静态] 4天 + [联调] 2天 |  数据源配置列表、导入用户、本地数据源、HTTP数据源配置/详情 | 04-10 |
| 虚拟账号 | [静态] 1.5天 + [联调] 1.5天 |  列表、搜索、新增、编辑、删除 | 04-15 |
| 登录配置 | [静态] 1.5天 + [联调] 1天 |  登录方式交互、账密登录、企业微信登录配置、详情 | 04-18 |
| 跨租户协同 | [静态] 3天 + [联调] 2天 |  租户列表、搜索、删除、新建/编辑/详情、数据更新记录 | 04-26 |

**Comment by brookylin** [comment]
| 功能模块 | [前端] 工作量 | 关键点 | 预计 API 时间点 |
|---|---|---|---|
| 组织架构 | [静态] 5天 + [联调] 4天 |  组织架构树、数据更新记录、列表、编辑/详情| 04-17 |
| 登录流程 | [静态] 1天 + [联调] 1天 |  新增协同用户群体 | 04-19 |
| 消息通知 | [静态] 1天 + [联调] 1天 |  | 04-24 |
| 版本日志 | [静态] 1天 + [联调] 1天 | 用户管理Markdown 版本日志 | 04-26 |

**Comment by yuri0528** [comment]
| 功能模块 | [前端] 工作量 |  关键点 | 预计可体验时间点 |
|---|---|---|---|
| 租户管理 | [静态] 1天 + [联调] 0.5天 |  新建/编辑、详情 | 03-25 |
| 管理员配置 | [静态] 1天 + [联调] 0.5天 |  管理员账号、实名账号 | 03-27 |
| 基础配置 | [静态] + [联调] 0.5天 |  用户数量、公司名 | 03-28 |
| 数据源配置 | [静态] 4天 + [联调] 2天 |  数据源配置列表、导入用户、本地数据源、HTTP数据源配置/详情 | 04-10 |
| 虚拟账号 | [静态] 1.5天 + [联调] 1.5天 |  列表、搜索、新增、编辑、删除 | 04-15 |
| 登录配置 | [静态] 1.5天 + [联调] 1天 |  登录方式交互、账密登录、企业微信登录配置、详情 | 04-18 |
| 跨租户协同 | [静态] 3天 + [联调] 2天 |  租户列表、搜索、删除、新建/编辑/详情、数据更新记录 | 04-26 |
