### ISSUE TITLE
[Release 3.0] 组织架构功能 Web API 

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1610]
现状：数据源组织架构 + 租户组织架构是两套 API
目标：统一成一套 -> 组织架构

现存的 API：
- 数据源组织架构
  - 获取数据源用户列表
  - 创建数据源用户（仅本地数据源）
  - 获取数据源部门列表（主要是用于下拉框选择）
  - 获取数据源用户上级列表（主要是用于下拉框选择）
  - 获取数据源用户详情
  - 更新数据源用户详情
  - 重置数据源用户密码（仅本地数据源）
  - 获取用户所属部门组织路径（如 公司/部门/中心)
- 租户组织架构
  - 拉取租户列表（用于左侧目录树展示）
  - 拉取某租户的租户用户列表
  - 获取某租户部门的子部门信息（左侧目录树展示）
  - 拉取某租户部门的租户用户列表
  - 获取租户用户详情

目标 API：
- 左侧组织树
  - [x] 租户信息（含数据源信息 ID，类型...）
  - [x] 当前租户根部门列表 / 协同租户根部门列表
  - [x] 租户部门子部门列表 / 协同租户部门子部门列表（注：可能直接和前一个 API 合并）
  - [x] 协同租户列表
  - [x] （仅本地数据源）添加，编辑，删除子部门 API
  - [x] 数据变更记录（本租户的是数据源同步日志记录，协同的在协同策略处查看）(复用 data_source.sync_record.list & retrieve)
  - [x] 部门搜索：支持按照部门名称模糊搜索（只提供前 50 个，2 字符起搜）
  - [x] 用户搜索：支持按照用户名，姓名，邮箱，手机号搜索（只提供前 50 个，2 字符起搜）
- 租户用户数据 
  - [x] 拉取租户用户列表（支持按用户名，全名搜索，支持递归 / 仅本级部门用户）
  - [x] 快速录入，支持自定义字段，通过 tooltips 提示可选项（和导入的 xlsx 模板类似）
  - [x] 从其他组织拉取 -> 相当于为一批用户添加 部门 - 用户 关联边
  - [x] 租户用户停用 / 启用
  - [x] 租户用户字段 & 自定义字段列表（复用 tenant_setting_fields.list）
  - [x] 仅本地数据源有效
    - [x] 租户用户移动到组织（只有批量操作，不支持单个移动）
    - [x] 租户用户添加到组织（只有批量操作，不支持单个移动）
    - [x] 租户用户批量删除
    - [x] 租户用户创建
    - [x] 租户用户编辑（含 logo）
    - [x] 获取租户用户详情
    - [x] 租户用户重置密码
    - [x] 租户用户删除（考虑影响范围）
    - [x] 数据源导出，导入（在顶级组织架构树的下拉）（复用 data_source.export & import）
  - [x] 下拉框数据来源 API
    - [x] 可选 leaders 用户列表
    - [x] 可选部门列表 
   - [x] 查询租户用户部门组织路径（独立 API）

**Comment by narasux** [comment]
关联需求：数据源导入改异步 https://github.com/TencentBlueKing/bk-user/issues/1294

**Comment by Xmandon** [comment]
1. 部门搜索交互，j具体参考上云bkuser：
<img width="525" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/94532d93-0116-4108-a0b6-05685375e3e5">

**Comment by Xmandon** [comment]
2. 从其他组织拉取，交互为：
<img width="612" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/445f135b-ebc4-403f-9bd5-aa9e9409e62e">

**Comment by Xmandon** [comment]
?）租户用户移动到组织（只有批量操作？是否支持单个移动？）
-----
批量操作足够支持，不再单独用户后面增加单个移动操作。

**Comment by Xmandon** [comment]
（?）快速录入（需要等产品确定，自定义字段如何处理？）
这里逻辑跟字段设置逻辑一致，必填字段必须需要加入到快速录入字段里（不管什么类型的字段，都只填写值即可）

<img width="1263" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/bbbcf018-ba48-4203-bb38-f21d2e00d1ad">

**Comment by Xmandon** [comment]
（?）数据源导出（设计稿没有体现）
一期只针对本地数据源允许导出。

<img width="949" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/165fb0be-2c8c-46f0-9d63-04b7224064e3">

<img width="831" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/19284021/8a3ef677-3dda-4793-924c-3026b0788811">
