### ISSUE TITLE
控制数据源/租户同步事务执行时间

### ISSUE THREAD

**Issue by narasux** [TencentBlueKing/bk-user#1618]
避免出现大事务导致锁表/锁 DB 的情况，需要优化同步器逻辑

获取数据源数据需要在事务外完成，在事务内尽量少查询 DB，或者将 DB 查询逻辑优化出去

但是存在一个问题，部门，用户修改/新建/删除是需要在同一个事务内的

**Comment by narasux** [comment]
最新结论，拆分成小事务 

比如：写入部门数据 / 写入用户数据 / 写入关联数据 分别是一个任务，但是存在的问题是，可能有短时的数据不一致情况（部分失败）

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-user/issues/1889
