### ISSUE TITLE
[讨论] 在用户删除后重新同步或录入后 UserID 是否变更

### ISSUE THREAD

**Issue by nannan00** [TencentBlueKing/bk-user#1692]
- 协同策略删除后重建，用户UserID 可能变化
- 本租户数据源同步到租户用户时，删除用户又添加，用户UseID 可能变化

具体看UserID 生成规则，如果是 uuid， 则会变化，如果是username之类，可能不变

**Comment by nannan00** [comment]
是否能根据数据源的用户 code决策，code 变化 usename=new_uuid, code 不变则 username=old_uuid

**Comment by narasux** [comment]
讨论结果：添加 DB 表，存储 tenant + code -> tenant_user_id（readable / uuid） 映射，新建 TenantUser 分配 ID 时候需要刷新该表
