### ISSUE TITLE
helm 部署文档链接跳转 404 

### ISSUE THREAD

**Issue by JaredTan95** [TencentBlueKing/bk-user#1715]
<img width="335" alt="image" src="https://github.com/TencentBlueKing/bk-user/assets/12468337/73848fd7-d46d-46fd-8a42-8d8a61dfe25d">

https://github.com/TencentBlueKing/bk-user/blob/main/deploy/helm/bk-user/README.md

**Comment by nannan00** [comment]
即将删除，后续直接查看官网部署指引：https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.1/index.md
