### ISSUE TITLE
配置AD登录，使用AD用户登录非常慢，如何排查？

### ISSUE THREAD

**Issue by yssky** [TencentBlueKing/bk-user#1724]
配置微软AD登录，使用AD用户登录非常慢，如何排查？

**重现方法**

使用本地用户登录非常快；
使用微软AD用户登录非常慢；

**预期行为**

需要达到本地用户登录一样的速度

**版本**
- 提供用户管理的具体版本号：V2.4.1
- 是否是企业版问题？：社区版

**Comment by nannan00** [comment]
https://github.com/TencentBlueKing/bk-user/issues/783

可以参数 python manage.py shell  命令行下，测试 check 的速度

https://github.com/TencentBlueKing/bk-user/blob/ba45342481330983726d6c1cbf90b2c290c25227/src/api/bkuser_core/categories/plugins/ldap/login.py#L32

https://github.com/TencentBlueKing/bk-user/issues/783
