### ISSUE TITLE
MAD账号同步异常

### ISSUE THREAD

**Issue by dan86755** [TencentBlueKing/bk-user#1832]
【产品】用户管理
【版本】社区版6.2.1
【使用环境】生产环境
【资源配置】centos7.9 16C/32G VM
【环境描述】MAD同步账号不成功
【自查情况】重启服务/测试配置连接成功/查看日志无报错信息
【问题描述】MAD方式手动同步账号，前端日志显示更新成功，实际没有同步，日志没有报错信息。
【图片信息】https://bk.tencent.com/s-mart/community/question/13660?type=answer

追问1： worker日志有如下提示，如何开启ENABLE_OTEL_TRACE，方便检查更多日志信息
[2024-07-09 15:27:04,456: WARNING/ForkPoolWorker-49] ENABLE_OTEL_TRACE = False

**Comment by nannan00** [comment]
配置环境变量 BKAPP_ENABLE_OTEL_TRACE = True 即可

**Comment by dan86755** [comment]
@nannan00 您好，感谢您的回复。MAD账号同步不成功的问题帮忙看一下，感谢！

**Comment by dan86755** [comment]
----------------------------日志分割线------------------------------------------------
#2023-07-15 补充api日志信息

INFO [2024-07-15 12:02:24] 265 disable_profiles_before_sync 155 140643420849984
Going to mark profiles(and relations)(all: 152) in category<2> as deleted, skipping 0 profiles

INFO [2024-07-15 12:02:24] 212 _sync 155 140643420849984
======== Going to bulk_create(count: 11) for Profile =========

INFO [2024-07-15 12:02:24] 225 _sync 155 140643420849984
======== Syncing part of Profile(1/1) current: 0 + 11 =========

WARNING [2024-07-15 12:02:24] 239 _sync 155 140643420849984
Profile bulk_create failed, count=11, extra_params={}, will try to sync one by one

ERROR [2024-07-15 12:02:24] 252 _sync 155 140643420849984
Profile bulk_create: save one by one fail, item=528-工号-NORMAL, will not be updated, detail={’_state’: <django.db.models.base.ModelState object at 0x7fea0a809438>, “账号字段信息隐蔽”}
Traceback (most recent call last):
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 84, in _execute
return self.cursor.execute(sql, params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/mysql/base.py”, line 73, in execute
return self.cursor.execute(query, args)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/cursors.py”, line 148, in execute
result = self._query(query)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/cursors.py”, line 310, in _query
conn.query(q)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 548, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 775, in _read_query_result
result.read()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 1156, in read
first_packet = self.connection._read_packet()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 725, in _read_packet
packet.raise_for_error()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/protocol.py”, line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/err.py”, line 143, in raise_mysql_exception
raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, “Duplicate entry ‘721b8ec3f015329751cc13be8cbed3fcaaee03745bea8e4cccd845c10d1a23df’ for key ‘code’”)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File “/data/bkce/usermgr/api/bkuser_core/common/db_sync.py”, line 232, in _sync
getattr(getattr(self.meta.target_model, manager), method)(part, **extra_params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/manager.py”, line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/query.py”, line 503, in bulk_create
objs_with_pk, fields, batch_size, ignore_conflicts=ignore_conflicts,
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/query.py”, line 1293, in _batched_insert
self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/query.py”, line 1270, in _insert
return query.get_compiler(using=using).execute_sql(returning_fields)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py”, line 1416, in execute_sql
cursor.execute(sql, params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 84, in _execute
return self.cursor.execute(sql, params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/utils.py”, line 90, in exit
raise dj_exc_value.with_traceback(traceback) from exc_value
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 84, in _execute
return self.cursor.execute(sql, params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/mysql/base.py”, line 73, in execute
return self.cursor.execute(query, args)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/cursors.py”, line 148, in execute
result = self._query(query)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/cursors.py”, line 310, in _query
conn.query(q)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 548, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 775, in _read_query_result
result.read()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 1156, in read
first_packet = self.connection._read_packet()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/connections.py”, line 725, in _read_packet
packet.raise_for_error()
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/protocol.py”, line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File “/cache/.bk/env/lib/python3.6/site-packages/pymysql/err.py”, line 143, in raise_mysql_exception
raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, “Duplicate entry ‘721b8ec3f015329751cc13be8cbed3fcaaee03745bea8e4cccd845c10d1a23df’ for key ‘code’”)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/data/bkce/usermgr/api/bkuser_core/common/db_sync.py”, line 243, in _sync
one.save()
File “/data/bkce/usermgr/api/bkuser_core/profiles/models.py”, line 169, in save
super().save(force_insert, force_update, using, update_fields)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/base.py”, line 740, in save
force_update=force_update, update_fields=update_fields)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/base.py”, line 778, in save_base
force_update, using, update_fields,
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/base.py”, line 859, in _save_table
forced_update)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/base.py”, line 912, in _do_update
return filtered._update(values) > 0
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/query.py”, line 802, in _update
return query.get_compiler(self.db).execute_sql(CURSOR)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py”, line 1559, in execute_sql
cursor = super().execute_sql(result_type)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py”, line 1175, in execute_sql
cursor.execute(sql, params)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/utils.py”, line 78, in _execute
self.db.validate_no_broken_transaction()
File “/cache/.bk/env/lib/python3.6/site-packages/django/db/backends/base/base.py”, line 448, in validate_no_broken_transaction
"An error occurred in the current transaction. You can’t "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can’t execute queries until the end of the ‘atomic’ block.

…省略剩余账号错误
-------------------------------日志分隔线---------------------------------------------

所有账号同步都报如下这条日志，为什么会和现有的账号code冲突？
django.db.utils.IntegrityError: (1062, “Duplicate entry ‘721b8ec3f015329751cc13be8cbed3fcaaee03745bea8e4cccd845c10d1a23df’ for key ‘code’”

**Comment by dan86755** [comment]
删除这个code，重新同步成功。
