### ISSUE TITLE
本地目录导入功能，删除用户不彻底

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#1853]
**用文字描述你遇到的问题**

在组织架构界面，可通过目录配置的导出导入功能对用户信息进行批量修改。根据导出的excel模板，将指定用户的【账户状态】字段值修改为【被删除】，导入后用户管理侧完成账号删除。

用户账号状态通过bk_user.profiles_profile表的status和enabled两个字段维护。被删除账号的status为DELETED,enabled=0；而通过导入方式则status为DELETED,enabled=1。导入方式与页面手动删除方式的状态字段更新不一致。

**重现方法**

构建测试导入文件
![image](https://github.com/user-attachments/assets/c16663e2-7700-4333-ab7e-6c64ce8ed67d)
![image](https://github.com/user-attachments/assets/b126907d-919f-4446-8795-bc012a10d1bb)

**预期行为**

被正常删除

**版本**
- v2.5.4
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by nannan00** [comment]
2.x 不支持

**Comment by bevis-canway** [comment]
是缺陷还是设计如此？预计会在哪个版本支持呢
