### ISSUE TITLE
[SaaS]支持同一个用户支持多种登录方式

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#186]
用户管理的需求：用户管理对接AD后，使用AD验证进行登录，在AD维护期间，或者演练的时候，或者AD平台故障时，会无法通过AD登录平台。目前客户要求能够在AD无法登录验证的时候，可以通过本地登录的方式，进行应急登录平台维护操作。

实现效果：同一个用户，可以支持蓝鲸登录，也可以使用AD登录，后台有一个配置，可以切换用户当前采用哪种登录方式。

相当于现在的蓝鲸本地用户支持本地登录，也支持其他方式的登录一样

**Comment by wklken** [comment]
Credentials校验是在 AD 侧? 是的话无法实现`AD 不可用`的情况下登录

除非独立, 一个用户支持两种登录方式: AD 登录及蓝鲸登录

**Comment by wklken** [comment]
close, see #473
