### ISSUE TITLE
修改用户密码有效期不同步更新密码修改时间字段

### ISSUE THREAD

**Issue by qq1114631740** [TencentBlueKing/bk-user#204]
**功能需求背景，例如你遇到了什么问题**

新建用户密码修改时间字段为空，如果在一个月之后修改用户的密码有效期为一个月。按照代码的逻辑（如果密码修改时间字段为空则用新建用户时间） 用户是直接过期的。

**描述你觉得更好的解决方案**

在修改用户密码有效期时，同步更新密码修改时间字段

**额外信息**

任何你觉得有助于理解的信息

**Comment by lilacfl** [comment]
两个点：
1，用户在创建时，已经有初始密码，那么对应的密码更新时间这个字段默认就应该有值吧？
2，当前修改密码有效期是不会更新密码更新时间字段的，这个是否可以考虑更新？

**Comment by IMBlues** [comment]
> 两个点： 1，用户在创建时，已经有初始密码，那么对应的密码更新时间这个字段默认就应该有值吧？ 2，当前修改密码有效期是不会更新密码更新时间字段的，这个是否可以考虑更新？

@lilacfl 

1. 密码更新字段是 记录**用户或者管理员主动发起**密码更新记录的字段。所以用户创建之后，并不会自动更新该字段，设计如此。
2. 修改密码有效期是针对整个目录配置而言的，也不应该存量更新用户的密码更新字段。

如果目录 A 的配置是密码有效期为一个月，主要表达的意思是“当前目录中，用户密码有效期为一个月，除非用户或者管理员**主动更新密码**“

之所以用户创建时不会产生密码更新记录的考量是，由平台分配的密码安全性较低，所以需要用户或者管理主动发起密码更新，以提高密码的安全性。

> 新建用户密码修改时间字段为空，如果在一个月之后修改用户的密码有效期为一个月。按照代码的逻辑（如果密码修改时间字段为空则用新建用户时间） 用户是直接过期的。

@qq1114631740 

所以目前这个过期行为是我们设计的预期行为。这里主要的理解出入是，这个过期时间是**从什么时间点开始计算**的。

- 我们是按照用户创建时间开始计算
- 管理员可能会理解为是修改目录有效期配置时开始生效

@Xmandon 所以是否可以考虑增加一个**_目录维度的_**、密码生效起始时间配置？如果不启用该配置，就从用户创建时间开始计算，否则从这个配置时间开始计算？

**Comment by lilacfl** [comment]
@IMBlues @Xmandon 可能之前关注点仅在于需求本身了，晚上我仔细梳理了下目前遇到的场景：1，用户密码到期之后，登录的提示是"用户名或密码错误"，无法感知到密码过期；2，告知用户可以通过"忘记密码"方式进行密码重置，也会存在邮件白名单或者邮件地址重复的问题导致无法自助重置密码；3，客户安全要求密码最长不超过3个月，所以大的规模企业里会经常有需要批量重置密码的需要。

从这几个场景归纳下，核心在于如何让客户更快更自主的处理密码过期的问题：让用户知道密码过期了，并提供自助重置密码的模块；管理员可以批量重置密码。

所以我理解是否可以对密码重置模块进行优化，参考其他产品：

- 密码过期之后直接跳转到重置密码页面，提示密码过期的同时，需要用户输入原密码和新密码进行密码更新；
- 点击忘记密码后，挑战至重置密码页面，提示正在进行重置密码操作，用户输入原密码和新密码进行密码更新；
- 管理员批量重置密码，提供勾选后批量操作；

帮忙看是否可行，如果可以，密码有效期这块的设计是无需改动的。

**Comment by IMBlues** [comment]
> @IMBlues @Xmandon 可能之前关注点仅在于需求本身了，晚上我仔细梳理了下目前遇到的场景：1，用户密码到期之后，登录的提示是"用户名或密码错误"，无法感知到密码过期；2，告知用户可以通过"忘记密码"方式进行密码重置，也会存在邮件白名单或者邮件地址重复的问题导致无法自助重置密码；3，客户安全要求密码最长不超过3个月，所以大的规模企业里会经常有需要批量重置密码的需要。
> 
> 从这几个场景归纳下，核心在于如何让客户更快更自主的处理密码过期的问题：让用户知道密码过期了，并提供自助重置密码的模块；管理员可以批量重置密码。
> 
> 所以我理解是否可以对密码重置模块进行优化，参考其他产品：
> 
> * 密码过期之后登录时直接跳转到重置密码页面，提示密码过期的同时，需要用户输入原密码和新密码进行密码更新；
> * 点击忘记密码后，跳转至重置密码页面，提示正在进行重置密码操作，用户输入原密码和新密码进行密码更新；
> * 管理员批量重置密码，提供勾选后批量操作；
> 
> 帮忙看是否可行，如果可以，密码有效期这块的设计是无需改动的。

1. 新版本修正了密码过期相关提示逻辑，可以等待新版发布之后测试看看具体的提示信息
2. 忘记密码只能通过邮箱重置，我们会考虑解决邮箱重复的问题，详见 #37 
3. 批量重置密码这个功能可以考虑。 @Xmandon  可以看下怎么设计会更好，类似于管理员平台可以针对批量用户进行密码重置操作，包括初始密码或者邮箱密码

**Comment by lilacfl** [comment]
> 忘记密码只能通过邮箱重置，我们会考虑解决邮箱重复的问题，详见 邮箱、手机号支持唯一性校验 #37
这个点不太理解，从我个人感觉上，无论是安全还是使用体验上，通过旧密码进行密码重置，会比邮箱更舒服；请问是有什么设计考虑吗

**Comment by IMBlues** [comment]
> > 忘记密码只能通过邮箱重置，我们会考虑解决邮箱重复的问题，详见 邮箱、手机号支持唯一性校验 #37
> 
> 这个点不太理解，从我个人感觉上，无论是安全还是使用体验上，通过旧密码进行密码重置，会比邮箱更舒服；请问是有什么设计考虑吗

没有，因为这是**“忘记”**密码，既然都忘记了，当然是**不记得旧密码**了 xD

**Comment by lilacfl** [comment]
> 忘记密码只能通过邮箱重置，我们会考虑解决邮箱重复的问题，详见 邮箱、手机号支持唯一性校验 #37

这个点不太理解，从我个人感觉上，无论是安全还是使用体验上，通过旧密码进行密码重置，会比邮箱更舒服；请问是有什么设计考虑吗

没有，因为这是 “忘记” 密码，既然都忘记了，当然是不记得旧密码了 xD

哦哦，明白，‘忘记’密码和‘重置’密码属于两个事情了，那就看下

> 1.新版本修正了密码过期相关提示逻辑，可以等待新版发布之后测试看看具体的提示信息

的效果吧，期望提示信息能在登录时体现，然后更进一步就是跳转强制重置密码。
