### ISSUE TITLE
社区版蓝鲸6.0.5无法部署usermgr2.3.1

### ISSUE THREAD

**Issue by lianghuiyuan** [TencentBlueKing/bk-user#217]
**问题描述**
社区版蓝鲸6.0.5默认使用2.2.6-b3版本的usermgr，但是无法同步MAD，为了能同步MAD，将usermgr升级到2.3.1，但发现部署2.3.1时：
$ ./bk_install saas-o bk_user_manage      执行成功
<img width="940" alt="image" src="https://user-images.githubusercontent.com/8090998/147333733-ad5f3e7b-4f67-4388-95f7-6d13e137273f.png">

$ ./bkcli install usermgr        执行失败

![E33791329C3B432600EBCF6CBF3C6939](https://user-images.githubusercontent.com/8090998/147333552-c52e8765-d99c-488f-9af8-3b3d052612c2.png)

看了报错信息显示缺少env文件，尝试做了以下操作：
$ source /data/install/utils.fc
$ source /data/install/load_env.sh
$ ./bkcli stop usermgr
$ ssh $BK_USERMGR_IP 'rmvirtualenv usermgr-api'
$ ./bkcli install usermgr 
依然报错。。。导致我无法进入 【用户管理】平台

**版本**
- 2.3.1
- 蓝鲸社区版6.0.5
 - OS: [Centos Linux release 7.6.1810 (Core)]

**Comment by IMBlues** [comment]
这里的 env 文件不是必须的，报错内容实际上只是 `warning` ，并不影响服务拉起。

就截图的内容而言，没有看到实质性的错误信息，如果是 SaaS 访问异常，请把发一下请求的具体内容。

**Comment by lianghuiyuan** [comment]
**现象描述**

在蓝鲸工作台点击进入【用户管理】服务，此时浏览器一直卡住(此时URL为 `http://paas.domain.com/console/`)，【用户管理】服务拉不起，一段时间后页面跳到登陆界面（账号被迫退出登陆状态），
URL为 ` http://paas.domain.com/login/?c_url=http%3A//paas.domain.com/o/bk_user_manage/&app_id=bk_user_manage `

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/8090998/147343512-6a6e5a91-1ff4-4b03-9e25-d379d48cadb4.png">

**Comment by lianghuiyuan** [comment]
usermgr 服务拉起过程的是怎样的呢？ 怎么看服务拉起过程中的日志？

**Comment by lianghuiyuan** [comment]
**日志**

从`bk_user_manager/uwsgi.log`日志中看，似乎最开始是因为`Abnormal error in verify_bk_token...`报错导致[Errno 110]Connection timed out

`/data/bkce/paas_agent/apps/logs/bk_user_manager/uwsgi.log` 日志：

![image](https://user-images.githubusercontent.com/8090998/147351447-b7a433ea-b700-4588-b683-8fc95c5506f3.png)
![image](https://user-images.githubusercontent.com/8090998/147351490-c487192e-50db-44e5-839e-5e9e73278bb1.png)
![image](https://user-images.githubusercontent.com/8090998/147351570-a3c6c208-97da-405f-bbca-eeaf9ac72fbc.png)
![image](https://user-images.githubusercontent.com/8090998/147351804-c23561a2-e857-4a48-a980-0ee1f32a0af2.png)

**Comment by IMBlues** [comment]
@lianghuiyuan 

用户管理有两个模块：Api 和 SaaS。前者是登录 & 用户信息查询的主要服务提供者，后者仅是**管理客户端**。

从以上的日志文件来看，Api 模块的拉起是正常的，如果对应的日志文件没有变更，可能主要的原因是**没有来自登陆服务的没有登录校验请求**。然后，从 SaaS 的日志看起来，是 SaaS 向登陆服务请求校验登录票据 `bk_token` 失败，无法连接到登陆服务。

需要进一步排查，可以尝试以下的方法：
- 使用隐身窗口访问任意蓝鲸平台产品，检查是否能够正常登录，如果可以，说明登录 + Api 模块没有问题，反之则需要再调查二者的日志。
- 可以进入用户管理 SaaS 容器，并尝试 curl 访问登录服务，一般的地址是 `http://paas.domain.com/login/`，也可以直接拼接上日志中的 bk_token。

**Comment by lianghuiyuan** [comment]
@IMBlues 

1. 使用admin 账户可以登陆除【用户管理】外的其他平台，eg：cmdb，itsm，权限中心等
2. 登陆模块的日志如下：
> `/data/bkce/logs/open_paas/login_uwsgi.log`
> ![image](https://user-images.githubusercontent.com/8090998/147431823-9969820b-f203-409e-aec3-08083d1978e4.png)
> `/data/bkce/logs/open_paas/esb_uwsgi.log`
> ![image](https://user-images.githubusercontent.com/8090998/147432418-e216f943-2ace-449f-878d-716bff0213af.png)


3. 进入任意SaaS容器，使用Curl访问登陆服务`http://paas.djicorp.com/login`无法访问，如图：
![image](https://user-images.githubusercontent.com/8090998/147436405-6bca371c-9e3f-48bf-80ce-6144d24f3d21.png)

**Comment by IMBlues** [comment]
1. 基本可以排除登录服务和 Api 模块的问题了。
2. 有些诡异，理论上所有 SaaS 都会调用登录服务的 API 去校验 bk_token，感觉可能是不应该走外网域名，导致网络不通。

看下是否方便为用户管理 SaaS 容器添加环境变量：
`BK_LOGIN_API_URL=http://paas.service.consul/login`

**Comment by lianghuiyuan** [comment]
1.  注入环境变量后貌似也是不行，如图：
![image](https://user-images.githubusercontent.com/8090998/147455089-81a0dfbb-834b-49b9-8b4b-18a8a382d80b.png)

2. Api模块--usermgr（2.3.1版本）
    SaaS模块--bk_user_manage(2.3.1版本)
    疑点1: 将bk_user_manage从版本2.3.1回退到版本2.2.6，用户管理服务能够正常使用，版本日志显示此时用户管理的版本是2.2.6
    疑点2:如何确定运行的usermgr是哪个版本 ？通过代码了解到【开发者中心->版本信息->用户管理  usermgr版本 v2.3.1】是从`/data/src/usermgr/VERSION`读取的版本号，有没有可能实际运行的usermgr版本不是2.3.1，而是2.2.6，因为在`./bkcli upgrade usermgr`时有报错：[问题的开始](https://github.com/TencentBlueKing/bk-user/issues/217#issue-1088234800)
![image](https://user-images.githubusercontent.com/8090998/147457762-0be5bf23-3ebf-4a59-ab9c-e3b03bfd24e5.png)
![image](https://user-images.githubusercontent.com/8090998/147457816-8989e8ed-5979-4335-bd57-0afbd92c1ec2.png)

    感觉问题是不是API模块和SaaS服务版本没有匹配？

**Comment by IMBlues** [comment]
1. 这点有点奇怪，可以在 2.2.6 的日志中看一下，具体访问的登录 URL 是什么，然后在 2.2.6 版本的容器中是否能正常访问登录？如果和 2.3.x 的地址有出入，可以直接通过环境变量覆盖，以成功访问的 URL 为准。
2. 版本日志显示的最新内容就是当前 SaaS 的版本，2.3.x 和 2.2.x 不兼容，不建议混合使用。

**Comment by IMBlues** [comment]
@lianghuiyuan 感觉提供的信息和变量已经足够多了，如果还有问题，欢迎通过企业微信即时联系排障

**Comment by lianghuiyuan** [comment]
收到，现在已回退到2.2.6，基本功能先用着，后面再尝试升级用户管理模块，非常感谢支持！
我先关了这个issue，后面有需要再打开。

**Comment by IMBlues** [comment]
https://github.com/TencentBlueKing/bk-user/releases/tag/v2.3.1

2.3.1 出的二进制包少了一个 BK_LOGIN_API_URL 变量，目前已经更新了二进制包，有空可以重新试试

@lianghuiyuan
