### ISSUE TITLE
LDAP/MAD 使用SSL加密报错 

### ISSUE THREAD

**Issue by wwyhy** [TencentBlueKing/bk-user#219]
**遇到的问题**

配置MAD认证时加密方式选择SSL后，登陆失败报错。并且登陆失败（加密方式为“无”，登陆正常）。
![image](https://user-images.githubusercontent.com/83105/147524003-0506821b-539d-42b7-8931-625f664b6b09.png)

![image](https://user-images.githubusercontent.com/83105/147524024-c37c5067-4645-4cd5-bf51-5b1f736c90af.png)

**重现方法**

配置MAD认证时加密方式选择SSL, 然后查看usermgr日志。

**预期行为**

无报错且正常登陆

**版本**
- 用户管理版本号： 2.2.6-b3
- 社区版： 6.0.4

**Comment by IMBlues** [comment]
我们会尝试复现一下

**Comment by IMBlues** [comment]
连接地址需要写成 

> **遇到的问题**
> 
> 配置MAD认证时加密方式选择SSL后，登陆失败报错。并且登陆失败（加密方式为“无”，登陆正常）。 ![image](https://user-images.githubusercontent.com/83105/147524003-0506821b-539d-42b7-8931-625f664b6b09.png)
> 
> ![image](https://user-images.githubusercontent.com/83105/147524024-c37c5067-4645-4cd5-bf51-5b1f736c90af.png)
> 
> **重现方法**
> 
> 配置MAD认证时加密方式选择SSL, 然后查看usermgr日志。
> 
> **预期行为**
> 
> 无报错且正常登陆
> 
> **版本**
> 
> * 用户管理版本号： 2.2.6-b3
> * 社区版： 6.0.4

@wwyhy 

仔细看了下，地址栏的填写有些问题

- 不使用 ssl 时，应该写成 `ldap://x.x.x.x:389`
- 使用 ssl 时，需要写成 `ldaps://x.x.x.x:636`

**Comment by IMBlues** [comment]
@wwyhy 是否有进一步测试？我先关闭这个 issue，有任何问题可以打开，继续留言

**Comment by wwyhy** [comment]
使用 ssl写成 ldaps://x.x.x.x:636, 报同样的错误， 并且 测试连接就会失败。

**Comment by IMBlues** [comment]
> 使用 ssl写成 ldaps://x.x.x.x:636, 报同样的错误， 并且 测试连接就会失败。

是否有具体报错的 API 模块日志呢？

**Comment by wwyhy** [comment]
上面截图为具体报错，模块为用户管理， 日志文件是： /data/bkce/logs/usermgr/bk_usermgr.log

**Comment by IMBlues** [comment]
> 上面截图为具体报错，模块为用户管理， 日志文件是： /data/bkce/logs/usermgr/bk_usermgr.log

确认端口没有错么？我写的 636 只是约定俗成的示例

**Comment by IMBlues** [comment]
> 端口636确定没有错误，内部IT也确认无问题。

@wwyhy 联系一下对应的蓝鲸助手？我们可以在企业微信上实时沟通看看
