### ISSUE TITLE
去除原有的 bk_fields \ mad_fields 配置，新增 dynamic_fields_mapping 配置

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#224]
增加一个 dynamic_fields_mapping Setting， value 应该是一个 Dict，存储 dynamic_field 字段的 key 和 远端 MAD 服务自定义字段的 key 映射关系。

同时需要在 migrations 中尝试删除原有的无用配置 mad_fields & bk_fields。

另外，考虑到 DynamicField 可能有删除，可以支持一种同步逻辑，在适当的时机保证配置中 dynamic_field key 都是真实有效的。

```json
{
  "key": "dynamic_fields_mapping",
  "value": {
    "dingding": "dingding",
    "gender": "gender",
    # 实际上已经在 DynamicField 表中被删除了
    "some_name": "someName"
  }
}
# 经过同步 =>

{
  "key": "dynamic_fields_mapping",
  "value": {
    "dingding": "dingding",
    "gender": "gender"
  }
}
```

好处就是，在后续对于该配置的处理时，可以不需要增加防御逻辑，防止当自定义字段被删除时出现的异常，数据库中也不会一直无用的冗余内容。

**Comment by Canway-shiisa** [comment]
##### 目录配置接口调整

###### 请求地址

复用saas侧接口：/api/v2/categories/\<int: category_id\>/settings/namespaces/fields/

###### 请求方法

POST

###### 请求示例

```json
[
  {
    "key": "basic_pull_node",
    "value": "",
    "region": "basic"
  },   
  {
    "key": "dynamic_fields_mapping",
    "value": {
        "bk_gender":"gender",
    	"bk_employeeID": "employeeID"
    },
    "region": "extend"
  },
   
  {
    "key": "user_group_class",
    "value": "groupOfUniqueNames",
    "region": "group"
  }
]
```

###### 调整部分：

1. 请求字段去除原有的bk_fields和mad_fields【调整API侧user_settings中的migrations】
2. 请求字段新增自定义字段配置，key固定是dynamic_fields_mapping，region固定是extend，value默认为一个空字典，如果存在自定义字段配置，则传递自定义字段配置



##### 自定义字段配置同步更新



![image-20211230141144290](C:\Users\canway\AppData\Roaming\Typora\typora-user-images\image-20211230141144290.png)



1.字段删除接口

###### 请求地址

复用saas侧接口：/api/v2/fields/\<PVAR_FIELD_ID\>/

###### 请求方法

DELETE



2.用户目录配置更新接口

###### 请求地址



新增Saas侧接口：api/v2/settings/dynamic_fields/<str: dynamic_field_name\>/

###### 请求方法

PATCH





新增API侧接口：api/v2/settings/dynamic_fields/<str: dynamic_field_name\>/

###### 请求方法

PATCH

**Comment by IMBlues** [comment]
> ##### 目录配置接口调整
> ###### 请求地址
> 复用saas侧接口：/api/v2/categories/<int: category_id>/settings/namespaces/fields/
> 
> ###### 请求方法
> POST
> 
> ###### 请求示例
> ```json
> [
>   {
>     "key": "basic_pull_node",
>     "value": "",
>     "region": "basic"
>   },   
>   {
>     "key": "dynamic_fields_mapping",
>     "value": {
>         "bk_gender":"gender",
>     	"bk_employeeID": "employeeID"
>     },
>     "region": "extend"
>   },
>    
>   {
>     "key": "user_group_class",
>     "value": "groupOfUniqueNames",
>     "region": "group"
>   }
> ]
> ```
> 
> ###### 调整部分：
> 1. 请求字段去除原有的bk_fields和mad_fields【调整API侧user_settings中的migrations】
> 2. 请求字段新增自定义字段配置，key固定是dynamic_fields_mapping，region固定是extend，value默认为一个空字典，如果存在自定义字段配置，则传递自定义字段配置
> 
> ##### 自定义字段配置同步更新
> 思路：删除操作调用两个接口，一个字段删除接口，一个用户目录配置更新接口(新增)
> 
> ![image](https://user-images.githubusercontent.com/90179140/147734948-b5913cc8-cf5f-440f-8c50-3731b5e37f50.png)
> 
> 1.字段删除接口
> 
> ###### 请求地址
> 复用saas侧接口：/api/v2/fields/<PVAR_FIELD_ID>/
> 
> ###### 请求方法
> DELETE
> 
> 2.用户目录配置更新接口
> 
> ###### 请求地址
> 新增Saas侧接口：api/v2/settings/dynamic_fields/<str: dynamic_field_name>/
> 
> ###### 请求方法
> PATCH
> 
> 新增API侧接口：api/v2/settings/dynamic_fields/<str: dynamic_field_name>/
> 
> ###### 请求方法
> PATCH

我们是不是可以在 ldap 插件中增加一个 signal 的 handler，监听 DynamicField 的删除事件，删除发生后尝试同步，这样是不是就不需要增加 SaaS API 了？

**Comment by Canway-shiisa** [comment]
##### 目录配置接口调整

###### 请求地址

复用saas侧接口：/api/v2/categories/\<int: category_id\>/settings/namespaces/fields/

###### 请求方法

POST

###### 请求示例

```json
[
  {
    "key": "basic_pull_node",
    "value": "",
    "region": "basic"
  },   
  {
    "key": "dynamic_fields_mapping",
    "value": {
        "bk_gender":"gender",
    	"bk_employeeID": "employeeID"
    },
    "region": "extend"
  },
   
  {
    "key": "user_group_class",
    "value": "groupOfUniqueNames",
    "region": "group"
  }
]
```

###### 调整部分：

1. 请求字段去除原有的bk_fields和mad_fields【调整API侧user_settings中的migrations】
2. 请求字段新增自定义字段配置，key固定是dynamic_fields_mapping，region固定是extend，value默认为一个空字典，如果存在自定义字段配置，则传递自定义字段配置



##### 自定义字段配置同步更新

思路：在ldap插件中新增一个 signal 的 handler，监听 DynamicField 的删除事件，删除发生后尝试同步

![image](https://user-images.githubusercontent.com/90179140/147734948-b5913cc8-cf5f-440f-8c50-3731b5e37f50.png)




1.字段删除接口

###### 请求地址

复用saas侧接口：/api/v2/fields/\<PVAR_FIELD_ID\>/

###### 请求方法

DELETE



2.配置同步更新

```python
bkuser_core/categories/signals.py
post_dynamic_fields_update =  django.dispatch.Signal()
post_dynamic_fields_delete = django.dispatch.Signal()
```

```python
bkuser_core/categories/plugins/ldap/handler.py
@receiver(post_dynamic_fields_update)
@receiver(post_dynamic_fields_delete)
def update_dynamic_fields():
    pass
```

```python
bkuser_core/profiles/views.py
class DynamicFieldsViewSet(AdvancedModelViewSet, AdvancedListAPIView):
        def update(self, request, *args, **kwargs):
        """更新自定义字段"""
        post_dynamic_fields_update.send()
        return self._update(request, partial=False)
    
    
        def destroy(self, request, *args, **kwargs):
        """移除自定义字段"""
		....
        post_dynamic_fields_delete.send()
        return super().destroy(request, *args, **kwargs)
    
```

**Comment by IMBlues** [comment]
可以使用 https://github.com/TencentBlueKing/bk-user/releases/tag/v2.3.2-beta.2 验证功能
