### ISSUE TITLE
蓝鲸6.0.4新增用户，提示邮件发送成功，实则失败

### ISSUE THREAD

**Issue by jackchenkai** [TencentBlueKing/bk-user#228]
**用文字描述你遇到的问题**

请用简练的文字描述你遇到的问题，问题描述的清晰程度决定了问题被解决的效率。

**重现方法**

请描述问题重现的方法，如果不方便描述，可以通过截图或者视频辅助。

**预期行为**

预期的正常行为

**版本**
- 提供用户管理的具体版本号
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容
# 蓝鲸版本：6.0.4
### 问题现象：
* 配置邮件服务器成功，curl命令测试发送邮件成功
* 用户管理-新增用户后，提示用户创建成功并已发送邮件，实则未收到邮件
查看相关日志提示： component.log
```ERROR [2021-12-31 15:48:40] component(ln:96): Component return error message: Signature [bk_signature] and APP Secret [bk_app_secret] cannot be empty at the same time, request_id=f22b19b317b247b0a0c92c3fd1ccd4a8, url=http://我们的域名:80/api/c/compapi/v2/cmsi/send_mail/, params=None, data={'title': '蓝鲸智云社区版 - 您的帐户已经成功创建```

**Comment by IMBlues** [comment]
1. 请尽量提供用**户管理的版本**，而不是蓝鲸版本
2. 根据报错内容可以判断，需要到 ESB 的数据库中检查用户管理的 bk_app_secret 是否填写正确，具体步骤可以咨询相关部署同学

**Comment by jackchenkai** [comment]
好的，用户管理版本是2.26,
通过curl命令测试发送邮件没问题





---原始邮件---
发件人: "Blues ***@***.***&gt;
发送时间: 2022年1月5日(周三) 上午10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentBlueKing/bk-user] 蓝鲸6.0.4新增用户，提示邮件发送成功，实则失败 (Issue #228)




  
请尽量提供用户管理的版本，而不是蓝鲸版本 

根据报错内容可以判断，需要到 ESB 的数据库中检查用户管理的 bk_app_secret 是否填写正确，具体步骤可以咨询相关部署同学 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jackchenkai** [comment]
追问，部署同学，如何联系到，是蓝鲸助手们？



---原始邮件---
发件人: "Blues ***@***.***&gt;
发送时间: 2022年1月5日(周三) 上午10:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentBlueKing/bk-user] 蓝鲸6.0.4新增用户，提示邮件发送成功，实则失败 (Issue #228)




  
请尽量提供用户管理的版本，而不是蓝鲸版本 

根据报错内容可以判断，需要到 ESB 的数据库中检查用户管理的 bk_app_secret 是否填写正确，具体步骤可以咨询相关部署同学 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IMBlues** [comment]
我们这边建议升级到 [2.3.x](https://github.com/TencentBlueKing/bk-user/releases/tag/v2.3.1) 版本测试

**Comment by jackchenkai** [comment]
这个版本刚上线？
前几天看还没呢



---原始邮件---
发件人: "Blues ***@***.***&gt;
发送时间: 2022年1月17日(周一) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentBlueKing/bk-user] 蓝鲸6.0.4新增用户，提示邮件发送成功，实则失败 (Issue #228)




 
我们这边建议升级到 2.3.x 版本测试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IMBlues** [comment]
> 这个版本刚上线？ 前几天看还没呢
> […](#)
> ---原始邮件--- 发件人: "Blues ***@***.***&gt; 发送时间: 2022年1月17日(周一) 下午4:09 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [TencentBlueKing/bk-user] 蓝鲸6.0.4新增用户，提示邮件发送成功，实则失败 (Issue #228) 我们这边建议升级到 2.3.x 版本测试 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

发布有段时间了，可以关注我们 [releases](https://github.com/TencentBlueKing/bk-user/releases)，后续最及时的版本都在这里更新

**Comment by IMBlues** [comment]
@jackchenkai 是否还有后续计划？如果没有，我这里先关闭这个 issue，有任何问题都可以打开继续留言
