### ISSUE TITLE
2022H1产品规划

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#232]
### 新增功能

1. ad/ldap支持自定义字段 https://github.com/TencentBlueKing/bk-user/issues/107 `1月`
2. 密码强度规则优化 https://github.com/TencentBlueKing/bk-user/issues/238 `1月`
3. 密码过期前邮件提醒 https://github.com/TencentBlueKing/bk-user/issues/117 `2月`
4. 对接企业微信 https://github.com/TencentBlueKing/bk-user/issues/118 `3月`
5. 多租户支持 https://github.com/TencentBlueKing/bk-user/issues/30 `3月`
6. 二次登录认证 https://github.com/TencentBlueKing/bk-user/issues/34 `4月`

### 优化项
1. 手机、邮箱唯一性校验 https://github.com/TencentBlueKing/bk-user/issues/37 `2月`
2. 人员表格搜索优化 https://github.com/TencentBlueKing/bk-user/issues/73 `1月`
3. 敏感字段设置 https://github.com/TencentBlueKing/bk-user/issues/36 `4月`
4. 邮件通知模板优化 https://github.com/TencentBlueKing/bk-user/issues/231 `2月`
5. 个人中心支持自定义字段编辑 https://github.com/TencentBlueKing/bk-user/issues/230 `2月`

### 待确认

1. 虚拟账号/公共账号，结合Oauth2.0、权限中心评估

**Comment by Xmandon** [comment]
接口需求：http://tapd.oa.com/20365752/bugtrace/bugs/view?bug_id=1120365752081240478

**Comment by Xmandon** [comment]
补充：
1. 接口需求
2. 口令复杂度需求
3. 账号变更通知提醒

**Comment by wwyhy** [comment]
https://github.com/TencentBlueKing/bk-user/issues/219 这个issue能验证和修复吗？

**Comment by Xmandon** [comment]
> #219 这个issue能验证和修复吗？

评估中

**Comment by wklken** [comment]
多渠道登录 => qq/wecom/wechat/weibo等等第三方登录 => 统一的`uniq_id`反向检索`user`
