### ISSUE TITLE
密码强度规则优化

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#238]
![image](https://user-images.githubusercontent.com/19284021/148877880-07933f5f-c500-4dbb-a6fc-45f2adbb1225.png)

**Comment by IMBlues** [comment]
关于让用户自定义输入正则，需要注意的问题：Python 正则很慢，而我们页面上每次添加用户都需要走密码校验，导致服务本身可能会被 DoS 攻击。

是否在用户填写时多增加一些提示和警告？

参考：
- https://swtch.com/~rsc/regexp/regexp1.html
- https://security.stackexchange.com/questions/112096/are-there-any-risks-to-matching-user-supplied-regex-against-user-supplied-inputs

**Comment by Xmandon** [comment]
补充设计稿
https://tp5it9.axshare.com/#id=2t0c5w&p=%E5%AF%86%E7%A0%81%E5%BC%BA%E5%BA%A6%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE&g=1

**Comment by IMBlues** [comment]
关于 ReDoS 我这里做了一些总结和分析，有兴趣可以扩展阅读：

https://emergencyexit.xyz/index.html
