### ISSUE TITLE
希望能在 v2.3.x 版本中支持 /api/v1/profile_list/ 接口，可以让5.2.10版本的故障自愈使用人员选择器

### ISSUE THREAD

**Issue by wenchao-h** [TencentBlueKing/bk-user#245]
**功能需求背景，例如你遇到了什么问题**
用户管理v2.3.2-beta.2缺少/api/v1/profile_list/接口导致故障自愈报错

<img width="1431" alt="857808c6-155c-4a89-af03-1fe3294ebb35" src="https://user-images.githubusercontent.com/33511440/149332120-cde6a4e2-58c4-4ca3-8888-14fddbf9ddf0.png">
<img width="427" alt="7740711f-45b4-44e5-8858-c722ab43959c" src="https://user-images.githubusercontent.com/33511440/149332218-57c6d300-5da6-467f-869c-53418a4a3b63.png">

![企业微信截图_16409387667721](https://user-images.githubusercontent.com/33511440/149332324-7cd439f4-351b-462a-930b-f6a7013863c5.png)

为什么会有这个点子？或者遇到了什么问题驱使你需要这个功能？

**描述你觉得更好的解决方案**

可以举例子来描述你觉得怎样做会更好

**额外信息**

任何你觉得有助于理解的信息

**Comment by IMBlues** [comment]
## 问题原因

在 2.3.x 版本中我们[废弃了原本提供的 v1 版接口](https://github.com/TencentBlueKing/bk-user/blob/master/docs/precautions/upgrade_from_2dot2.md)

## 解决方案

我们将提供一份 “越狱”后的兼容方案

### 添加“越狱”文件

```python
from bkuser_core.profiles.models import Profile
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response


@csrf_exempt
@api_view(["GET"])
def profile_list(request):
    """
    获取所有用户
    """
    role = request.GET.get("bk_role", "")
    profile_objs = Profile.objects.all()
    if role in ["0", "1", "2", "3", "4"]:
        profile_objs = profile_objs.filter(role=int(role), enabled=True)

    data = profile_objs.extra(select={"bk_role": "role", "bk_username": "username"}).values(
        "id",
        "bk_username",
        "display_name",
        "qq",
        "bk_role",
        "language",
        "telephone",
        "wx_userid",
        "email",
        "status",
        "staff_status",
        "time_zone",
    )

    return Response(data=list(data))

```

将以上文件内容保存到文件 `v1_api_profile_list_patch.py` 中，并添加到 api 模块的路径 `bkuser_core/apis/` 中。

### 修改 urls 入口
在 `bkuser_core/urls.py` 文件的末尾添加内容

```python
from bkuser_core.apis.v1_api_profile_list_patch import profile_list

urlpatterns += [
    url(r"^api/v1/profile_list/", profile_list),
]
```

然后尝试**重启 api 服务**。



## 影响

由于该接口提供的是全量人员查询，没有分页，也没有对返回字段进行限制，当人员数量较多时，该 API 的行为近似于“脱表”，无法保证 API 响应时间。而大多使用场景都是前端的“人员选择器”，所以当人员过多时，页面会出现卡顿。

因此，请牢记该文件仅作为 **临时** 解决方案，请勿长期在生产使用，人员选择器请尽快升级到通用的企业版方案。

**Comment by wklken** [comment]
故障自愈最新版, 已经前端支持, 切换使用新版API
