### ISSUE TITLE
批量获取用户接口/api/v2/batch/profiles/，swagger显示的是没有参数，但实际代码中校验参数query_ids

### ISSUE THREAD

**Issue by Ysach** [TencentBlueKing/bk-user#26]
**访问批量获取用户接口/api/v2/batch/profiles/，返回错误：**
`{"result":false,"data":null,"code":-1,"message":"request failed, please check api log of bk-user"}`

**源码：**
bkuser_core-->common-->viewset.py的mutliple_retrieve获取query_ids

**建议修改文件** bkuser_core/profiles/views.py：

>  @swagger_auto_schema(
>         manual_parameters=[],
>         responses={"200": local_serializers.ProfileSerializer()},
>         tags=["profiles"],
>     )
> 

**bkuser_core/profiles/views.py文件增加导入** openapi

> from drf_yasg import openapi

swagger部分修改：

>     @swagger_auto_schema(
>         manual_parameters=[openapi.Parameter("query_ids", openapi.IN_QUERY,
>                                              description="input departments query_ids,逗号分割",
>                                              type=openapi.TYPE_STRING)],
>         responses={"200": local_serializers.ProfileSerializer(many=True)},
>     )

**Comment by IMBlues** [comment]
确实有这个问题。我们会在 milestone 前修复这个问题，当然如果有余力可以提交 PR 就更好啦。
