### ISSUE TITLE
【MAD登录】 MAD同步成功，但域账号登录时仍然提示“账户名和密码不匹配”

### ISSUE THREAD

**Issue by relovely** [TencentBlueKing/bk-user#262]
**用文字描述你遇到的问题**

MAD同步成功，但域账号登录时提示“账户名和密码不匹配”，导致登录失败

**重现方法**

MAD同步成功后，凭借账号：`用户名@登录域`，密码：`域密码`登录 paas ，提示“账户名和密码不匹配”，导致登录失败

**预期行为**

域用户能正常登录 paas 平台

**版本**
- 版本: v6 社区版

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**
 - Browser：chrome
 - Version：版本 97.0.4692.71（正式版本） (arm64)
 - bkcli check usermgr：[SUCCESS] 
 - 域账号及域密码已验证过无问题

**额外信息**
login.log 异常如下：
<br>
INFO [2022-01-25 15:01:11] ./components/usermgr_api.py 40 _call_usermgr_api 59519 140077745212784 
         _call_usermgr_api fail: url=http://usermgr.service.consul:8009/api/v1/login/check/, data={u'username': u'AAAAAAA', u'domain': u'BBBBBBB.tech', u'password': u'******'}, _data={u'message': u'\u8d26\u6237\u540d\u548c\u5bc6\u7801\u4e0d\u5339\u914d', u'code': 3210013, u'data': None, u'result': False} 

(说明：域账号已脱敏为：AAAAAAA，登录域已脱敏为：BBBBBBB.tech )

任何你觉得有助于问题解决的内容

**Comment by IMBlues** [comment]
请提供一下用户管理后台 API 的版本

@relovely

**Comment by relovely** [comment]
> 

2.2.5
![image](https://user-images.githubusercontent.com/20235554/151099637-133e0a59-10ed-4ae2-9911-2df0c4a344ce.png)

**Comment by IMBlues** [comment]
登录使用的是 cn 字段，密码就是 AD 中的字段，这个逻辑目前在其他各种企业中都是可以正常登录的。目前提供的信息也看不出有什么问题，感觉上还是账号密码本身填写有问题。

可以考虑把以下信息脱敏后贴出来：
- AD 中的具体用户信息，包括不限于 cn、dn、objectclass 这些。

也可以尝试升级到开源版本中的 2.3.x 版本，会更有利于问题推动，不过要注意升级前必要步骤。

**Comment by IMBlues** [comment]
暂时没有进一步提供信息，我先关闭当前 issue，有问题可以再次打开、继续留言。
