### ISSUE TITLE
人员列表搜索体验汇总

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#270]
- [x]   需要支持模糊查询
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/19284021/154004054-7637ccea-b830-44dc-8fcc-48ed3fa9cac9.png">

- [x]  组织搜索无效
<img width="818" alt="image" src="https://user-images.githubusercontent.com/19284021/154004226-054802e4-b70f-41ee-968d-b297e4b17136.png">

- [x]  搜索的结果，人员详情显示为空
<img width="2530" alt="image" src="https://user-images.githubusercontent.com/19284021/154004403-33ee98fd-9646-4d15-815d-c4154918b9be.png">

**Comment by IMBlues** [comment]
- 默认字符串均支持模糊查询，浮点和整形只支持精确搜索
- 组织和上级搜索暂时不支持，还需要额外的 API 调用
