### ISSUE TITLE
改造当前版本元信息的文件组织方式，拆分成多个文件

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#280]
当前是一个巨长的 [yaml](https://github.com/TencentBlueKing/bk-user/blob/d39373ac4a66741a77271c9e76ae6f00267225fc/src/saas/RELEASE.yaml) 保存版本元信息，每次 SaaS 打开时都会读取该 yaml 并加载，随着版本增多，后期或许会有性能问题，考虑拆分成多个文件，需要联合前端动态加载

**Comment by wklken** [comment]
1. 开发框架有现成的模块可以用(不确定是否好用)
2. 权限中心bk-iam-saas也实现了类似的功能, 代码量不大, 识别并渲染md文件, 前端等都是现成的

**Comment by IMBlues** [comment]
用户管理自己有一套版本管理方案 😂，个人觉得还是比较好用的（可能比开发框架的好），只是元数据的定义这块需要小幅改动。

目前只需要在一个 yaml 中定义结构化的更新日志，然后 `make generate-release-md` 即可生成 markdown，前端展示也不需要额外修改。
