### ISSUE TITLE
[logging] 数据源数据同步流程打印更详细的日志

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#296]
- [ ] 阅读代码, 梳理整体流程
- [ ] 执行过程中关键步骤都有日志
- [ ] 报错都有明确说明与堆栈

**Comment by wklken** [comment]
需要包含一些 进度数据(当前处理到哪里), 统计数据(同步了多少人, 删除了多少人)

**Comment by IMBlues** [comment]
https://github.com/TencentBlueKing/bk-user/blob/057f270d66a1834312306c9fba1f4e95521f10b1/src/api/bkuser_core/categories/models.py#L159

建议看下 SyncTask，我们所有进度都默认向 DB 中存储
