### ISSUE TITLE
增加组织架构数据正确性检测脚本

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#3]
在企业中部署时，常常会手动修改数据库情况，由于代码本身无法感知，会引发一些程序异常。

例如：
- 将 `department` 的 `enabled` 字段手动修改成 0，但仍被 `enabled=1` 的子部门关联，此时权限中心同步接口将出现无法建树的情况

可以提供一个扫描脚本，对于有关联关系的数据模型，判断其关联是否有效，输出一个报告，辅助实施侧运维判断。

**Comment by Canway-shiisa** [comment]
权限中心的组织架构数据是通过调用用户管理接口来生成的：
1.同步用户：`/api/v2/profiles/`（在ESB中为`/api/c/compapi/v2/usermanage/list_users/`）

- 新增：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，对于新增的用户执行新增的变更
- 更新：对于变更了 display_name、staff_status、category_id的用户，进行更新操作
- 删除：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，不存在的用户则为需要删除的，进行删除处理

2.同步部门：`/api/v2/departments/`（在ESB中为`/api/c/compapi/v2/usermanage/list_departments/`）

- 新建：遍历接口获取过来的所有新数据，对比数据库中原本的部门数据，对于新增的部门执行新增的变更
- 更新部门拓扑：更新变更了parent的部门
- 删除部门：遍历接口获取过来的所有新数据，对比数据库中原本的部门旧数据，不存在的部门则为需要删除的，进行删除处理【使用BFS转换出可顺序删除的列表，以mptt方式进行删除处理】
- 更新部门基本信息：对于变更了的name、category_id、order的部门，进行更新操作

3.同步部门与用户关系：`/api/v2/edges/department_profile/`（在ESB中为`/api/c/compapi/v2/usermanage/list_edges_department_profile/）

- 新增部门成员：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，对于新增的部门成员执行新增的变更
- 删除部门成员：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，不存在的用户则为需要删除的，进行删除处理

4.同步用户与leader的关系：`/api/v2/edges/leader/`（在ESB中为`/api/c/compapi/v2/usermanage/list_edges_leader_profile/`）

- 新建用户leader：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，对于新增的用户执行新增的变更
- 删除用户leader：遍历接口获取过来的所有新数据，对比数据库中原本的用户旧数据，不存在的用户则为需要删除的，进行删除处理

**Comment by IMBlues** [comment]
暂时没有这个需求，先 close，有想法时可以再打开
