### ISSUE TITLE
将 API 接入 ApiGateway

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#305]
- 是否支持通过 swagger 直接导入数据？
- 是否支持通过 swagger 自动生成文档？

**Comment by wklken** [comment]
问题:
1. 现在对外版, 只有通过esb暴露的接口, 没有直接绕过esb直接访问用户管理的(登录除外)
2. 哪些 API 是给 SaaS 用的, 无需接入 APIGateway 的
3. 考虑 a)给esb b)给 SaaS c)其他, 如果接入 APIGateway, 如何做权限控制? 申请得到权限, 相当于就能调用对应一批接口? 

-------

暂时的结论:
1. 给 SaaS 用的, 不接入

**Comment by wklken** [comment]
初期只接入查询类的, esb 的几个api

**Comment by wklken** [comment]
#327

**Comment by wklken** [comment]
## 定义的组件调用的接口


https://github.com/Tencent/bk-PaaS/blob/develop/paas2/esb/components/bk/apisv2/usermanage/fs_list_users.py

- GET /api/v1/profile_list/
- GET /api/v2/profiles/
- GET /api/v2/categories/

## 代理的流量

https://github.com/Tencent/bk-PaaS/blob/develop/paas2/esb/components/confapis/usermanage/usermanage.yaml

----

理论上, 先只对接代理的几个查询接口

**Comment by wklken** [comment]
```
 GET /ping/
 GET /healthz/
 GET /api/v2/profiles/
 GET /api/v2/departments/
 GET /api/v2/profiles/{id}/
 GET /api/v2/departments/{id}/
 GET /api/v2/profiles/{id}/departments
 GET /api/v2/departments/{id}/profiles
 GET /api/v2/edges/department_profile/
 GET /api/v2/edges/leader/
 GET /api/v2/categories/
```

**Comment by IMBlues** [comment]
> ```
>  GET /ping/
>  GET /healthz/
>  GET /api/v2/profiles/
>  GET /api/v2/departments/
>  GET /api/v2/profiles/{id}/
>  GET /api/v2/departments/{id}/
>  GET /api/v2/profiles/{id}/departments
>  GET /api/v2/departments/{id}/profiles
>  GET /api/v2/edges/department_profile/
>  GET /api/v2/edges/leader/
>  GET /api/v2/categories/
> ```

后三个目前是隐藏的，仅开放给权限中心
