### ISSUE TITLE
对接单点登录之后如何新增admin超级管理员？

### ISSUE THREAD

**Issue by ganzaofang** [TencentBlueKing/bk-user#314]
**功能需求背景，例如你遇到了什么问题**

对接公司内部的单点系统之后，所有用户登录都是普通用户，admin不能登录了， 通过代码逻辑控制role无效。
如何新增admin超级管理员？

**描述你觉得更好的解决方案**

希望可以给一个重新创建admin超级管理员方法或者python脚本

**额外信息**

原贴地址：https://bk.tencent.com/s-mart/community/question/6612?type=answer

**Comment by IMBlues** [comment]
```python
from bkuser_core.profiles.models import Profile
from bkuser_core.categories.models import ProfileCategory

p = ProfileCategory.objects.get(id=${期望目录id})
Profile.objects.create(username="admin", domain=p.domain, category_id=p.id)
```

**Comment by ganzaofang** [comment]
创建好admin超级管理员后，admin的密码是什么？

**Comment by ChainsDW** [comment]
我创建了admin怎么登录呢，我的单点登录里没有这个账户啊
