### ISSUE TITLE
[SaaS]同步任务页面功能

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-user#32]

**Comment by IMBlues** [comment]
<img width="661" alt="企业微信截图_9ac9ca82-c952-4a93-b7fa-1b5b07169326" src="https://user-images.githubusercontent.com/4225292/132218499-bfd86a21-19a9-4d69-92c9-d398170f0a36.png">

是否考虑根据数值内容来选择单位？

- <1 分钟
- 59 分钟
- 13.5 小时

最大单位到小时应该足够了

**Comment by IMBlues** [comment]
![image](https://user-images.githubusercontent.com/4225292/132218810-9ce72f74-8259-478a-80a4-661ddc2b729d.png)

- 目标目录的说法有些奇怪，是否直接写“用户目录” 更合理？
- 触发类型，可能需要做一次 code -> display_name 的映射
  - manual -> 手动触发
  - auto -> 定时触发

**Comment by IMBlues** [comment]
![image](https://user-images.githubusercontent.com/4225292/132219114-84f6cb97-b6c1-4f3a-bf52-7155ed2a4d77.png)

没有对应条目是否增加一个表示 “空” 的图标或者提示更清晰一些？

**Comment by IMBlues** [comment]
![image](https://user-images.githubusercontent.com/4225292/132219408-64e1e4c0-c179-4e13-9a5a-94b86b66876d.png)

`用户和上级关系数据更新` ?

**Comment by IuzreO** [comment]
done
