### ISSUE TITLE
未关联部门的用户应该有地方展示

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#35]
当前用户如果没有关联到具体的部门，在 SaaS 的组织架构上是无法展示的（可以搜索到），应该有一个专门的地方用来展示这些孤立的用户，并支持管理员手动给他们关联到具体部门。

**Comment by IMBlues** [comment]
通过搜索能找到未关联部门的用户，但是由于我们的权限只绑定到了部门层级，所以针对这些用户的操作会有异常产生。

**Comment by wklken** [comment]
@Xmandon 这个算是高优先级事项

**Comment by Xmandon** [comment]
已跟嘉为产品同学确认，目前并不存在不在某个组织下的用户，所以可以转为缺陷处理。

**Comment by abbyWJM** [comment]
通过接口创建客户：
1、接口如果不传组织，无法成功创建用户
2、接口传不存在的组织，可以创建成功，组织架构就是空的
产品功能侧：
1、如果用户被删除后，原组织架构被删掉，恢复后就会出现空组织架构的情况
@Xmandon

**Comment by wklken** [comment]
新版删除用户, 不会同步删除其组织架构;

**Comment by wklken** [comment]
需要高优先级处理, 产品上这类用户怎么查看/展示

当前搜索接口能查到

当前权限处理: 如果没有部门, fallback到category_id管理权限

**Comment by Xmandon** [comment]
@Shutulee  问题已经从源头修复，不存在“没有组织的用户”，如果确认已修复，需要验证下新版是否还存在这个问题。

**Comment by wklken** [comment]
@Xmandon 本地excel导入修复了, 但是ldap同步还是会出现`没有部门的用户`

当一个部门被删除时, 其用户关系被清理, 那么会出现 `没有部门的用户`

这是个共性问题, 是否考虑产品上做展示

**Comment by wklken** [comment]
close, #760 fixed this
