### ISSUE TITLE
[容器化] livenessProbe和readinessProbe配置的HTTP GET探测返回302

### ISSUE THREAD

**Issue by ssflying** [TencentBlueKing/bk-user#377]
**用文字描述你遇到的问题**

用户管理SaaS的pod（bk-user-saas-xxxx）的存活探测、健康探测配置的不合理
HTTP GET / 由于无登录态跳转返回302。会导致kubelet一直产生ProbeWarning
事件。

**重现方法**

`kubectl describe pod bk-user-saas-xxxx` 查看events
`kubectl logs bk-user-saas-xxxx -f | grep kube-probe` 查看请求日志返回码都是302

**预期行为**

预期健康、存活时返回 http code 200

**版本**
- helm charts: bk-user-1.2.5

**额外信息**
见：https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#urgent-upgrade-notes
kubelet段：

> Health check (liveness & readiness) probes using an HTTPGetAction will no longer follow redirects to different hostnames from the original probe request. Instead, these non-local redirects will be treated as a Success (the documented behavior). In this case an event with reason "ProbeWarning" will be generated, indicating that the redirect was ignored. If you were previously relying on the redirect to run health checks against different endpoints, you will need to perform the healthcheck logic outside the Kubelet, for instance by proxying the external endpoint rather than redirecting to it.

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/blob/development/src/saas/bkuser_shell/monitoring/views.py#L20

已经有/healthz/

缺一个 /ping/

------
加上后, 修改helm charts配置

**Comment by wklken** [comment]
v2.3.4-beta.14
