### ISSUE TITLE
将公司的openldap导入蓝鲸平台后，在“用户管理”模块看到的用户，在“权限中心”模块的“用户”中看不到

### ISSUE THREAD

**Issue by wangyu8460958** [TencentBlueKing/bk-user#381]
**用文字描述你遇到的问题**
当我将公司的openldap导入到蓝鲸平台后，用户管理里面可以看的到相关的用户，但是在权限中心中却看不到相关的用户，我点击了权限中心的“刷新”后仍然没有效果。
请用简练的文字描述你遇到的问题，问题描述的清晰程度决定了问题被解决的效率。

**重现方法**

请描述问题重现的方法，如果不方便描述，可以通过截图或者视频辅助。
用户管理界面：
![image](https://user-images.githubusercontent.com/34674414/164426001-14dd54e5-95c5-40d1-86b4-bf464b3efaef.png)
权限中心界面：
![image](https://user-images.githubusercontent.com/34674414/164426381-f89e038a-6a9e-466d-869c-297b57c48465.png)

**预期行为**

预期的正常行为
用户管理里面可以看到相关的用户，权限中心中应该是看的到相关的用户。
****
- 提供用户管理的具体版本号
- 是否是企业版问题？
是社区版本 6.0，用户管理的具体版本号是 2.2.5
**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wklken** [comment]
1. 点击权限中心的组织架构同步按钮
<img width="472" alt="image" src="https://user-images.githubusercontent.com/2002216/164430500-54983796-e0e0-4ac5-afe5-7f7cbb7c8ea6.png">

2. 另外, 需要确认这10 个人的状态, 权限中心同步只会拉取到`合法`的用户;
