### ISSUE TITLE
请求接口/api/v2/setting_metas/base_dn/，返回request failed, please check api log of bk-user

### ISSUE THREAD

**Issue by Ysach** [TencentBlueKing/bk-user#44]
请求接口`/api/v2/setting_metas/base_dn/`，返回错误`request failed, please check api log of bk-user`

检查日志报错大致如下：
`bkuser_core.user_settings.models.SettingMeta.MultipleObjectsReturned: get() returned more than one SettingMeta -- it returned 2!`

而表结构的主键是：`unique_together = ("key", "namespace", "category_type")`

而lookup_field的值是key：`lookup_field = "key"`

因为调用的是`get_object()`，这个最终调用的是django--->shortcuts.py的
```python
return queryset.get(*args, **kwargs)
```

建议修改如下：
文件：`bkuser_core/user_settings/views.py`
原内容：
```python
class SettingMetaViewSet(AdvancedModelViewSet, AdvancedListAPIView):
    """配置信息"""

    queryset = SettingMeta.objects.all()
    serializer_class = serializers.SettingMetaSerializer
    lookup_field = "key"
```

修改内容：
```python
class SettingMetaViewSet(AdvancedModelViewSet, AdvancedListAPIView):
    """配置信息"""

    queryset = SettingMeta.objects.all()
    serializer_class = serializers.SettingMetaSerializer
    lookup_field = "id"
```

**Comment by IMBlues** [comment]
目前可以通过参数来实现 `id` 读取：
```
/api/v2/setting_metas/${id}/?lookup_field=id
```

当然这里默认使用 `key` 做路径参数也不是很合理，我另开一个 issue 处理
