### ISSUE TITLE
用户目录逻辑删除会导致相同登陆域的目录不可创建

### ISSUE THREAD

**Issue by abbyWJM** [TencentBlueKing/bk-user#441]
在实施过程中，客户习惯创建一个本地目录用于功能验证。在功能验证完毕后，需要正式对接ad或ldap时，本地目录的登录域会重复，在页面上删除该目录也无法解决此问题，目前解决方式为手动去数据库中清理对应的目录，或者直接重置用户管理saas的数据库。
基于此逻辑，也会衍生出一系列权限中心无法正常同步组织架构的问题。

**Comment by wklken** [comment]
需要看下, 目前会引入很多问题, 带来很多排查

删除后, 不可见, 没有地方恢复会执行真删除, 导致软删除的目录占用了唯一字段

1. 当用户新建一个目录存在重复唯一值时, 报错, 并且无解;
2. 当用户新建一个目录, 配置了同一个ladp源, 点击同步, 同步会失败, 无解

-----

需要考虑:
1. 怎么展示
2. 可以恢复软删除目录及其用户
3. 可以执行真删除

**Comment by wklken** [comment]
或者, 点击删除目录, 直接物理删除目录+目录下用户? 
风险: 误删除无法恢复

**Comment by wklken** [comment]
<img width="1834" alt="image" src="https://user-images.githubusercontent.com/2002216/196879103-9cd0a249-5bff-463d-a2b8-4655f977b1b1.png">

**Comment by wklken** [comment]
@Shutulee  @Xmandon  这里目前导致了很多问题排查(原因, 被删除目录没有真正删除, 占坑导致后续新增目录/新增同步数据报错)

**Comment by wklken** [comment]
close, #760 fixed this
