### ISSUE TITLE
会话重放漏洞

### ISSUE THREAD

**Issue by abbyWJM** [TencentBlueKing/bk-user#477]
@wklken 用户管理现在可以无限制添加用户，导致客户处渗透性测试无法通过。期待禁止用户在短时间内多次提交数据

**Comment by wklken** [comment]
- 谁, 可以无限制添加用户? 超管被破解?
- 加限制, 会影响到正常用户使用吗? 如何判定是异常的? 需要避免影响正常用户使用

--------

**Comment by abbyWJM** [comment]
与客户确认非会话重放问题
