### ISSUE TITLE
LDAP 用户同步 ，用户组名字段 修改无效

### ISSUE THREAD

**Issue by Yjunie** [TencentBlueKing/bk-user#488]
**用文字描述你遇到的问题**

LDAP 用户同步 ，用户组名字段 修改为CN后 仍读取OU字段

**重现方法**

请描述问题重现的方法，如果不方便描述，可以通过截图或者视频辅助。

**预期行为**

预期的正常行为

**版本**
- 提供用户管理的具体版本号 

2.2.6

</html>
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by Yjunie** [comment]
![SB13MVQGE}Q61FT{`{GHLI2](https://user-images.githubusercontent.com/43564390/172546335-796dfe84-0918-401f-b2a4-f052c09ea022.png)
![%ATR3(@@9JJQE 0R56~0CPA](https://user-images.githubusercontent.com/43564390/172546369-0f33a6cd-346a-476d-8bfd-de984b1b2083.png)
![G5O2LBGRNH3(%_K9GNVN9ZA](https://user-images.githubusercontent.com/43564390/172546396-553082e1-107d-4a1d-bbb4-95710faa9fda.png)

**Comment by wklken** [comment]
ldap 相关问题汇总: https://github.com/TencentBlueKing/bk-user/issues/429

--------------

1. 修改配置后, 是否重新进行同步? 
2. 麻烦到问答社区发帖, 直接把issue链接贴进去, 社区管理员会协助解决

**Comment by wklken** [comment]
超过 1 个月, close, 如果还有问题, 按照上面步骤操作
