### ISSUE TITLE
同步MAD没有任何用户账号

### ISSUE THREAD

**Issue by lewjj** [TencentBlueKing/bk-user#491]
**用文字描述你遇到的问题**

设置MAD同步，测试连接正常，同步正常，实际没有任何账号同步过来。

**重现方法**

配置MAD成功后，没有任何账号同步过来。

**预期行为**

预期的正常行为

**版本**
- 提供用户管理的具体版本号
- 蓝鲸社区版6.1
- 用户管理模块2.3.4
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wklken** [comment]
1. 先从配置说明文档+FAQ 确认配置;  ldap 相关问题汇总: https://github.com/TencentBlueKing/bk-user/issues/429
2. 如果还无法确定问题, 麻烦到问答社区发帖, 直接把issue链接贴进去, 社区管理员会协助解决

**Comment by wklken** [comment]
> 1. 先从配置说明文档+FAQ 确认配置;  ldap 相关问题汇总: [[文档] ldap 配置/使用/FAQ 汇总 #429](https://github.com/TencentBlueKing/bk-user/issues/429)
> 2. 如果还无法确定问题, 麻烦到问答社区发帖, 直接把issue链接贴进去, 社区管理员会协助解决

超过 1 个月, close, 如果还有问题, 按照上面步骤操作
