### ISSUE TITLE
【departments】组织上下移功能无效

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#500]
**用文字描述你遇到的问题**

在组织架构任意部门下进行上下移操作，刷新后失效，实际无法实现上下移

**重现方法**

进入用户管理 -> 点击组织架构 -> 对应组织右侧点击上下移 -> 刷新页面确认组织排序是否调整
![image](https://user-images.githubusercontent.com/90179140/174747473-57dde92f-f6de-4b64-9e1b-7f6c9ec73eb5.png)

**预期行为**

- 在指定组织进行上下移操作之后，刷新页面之后，看到重新排序的组织序列

**版本**
- 目前最新版代码仍旧存在该问题

**Comment by IMBlues** [comment]
考虑不使用 order 进行排序？

https://github.com/TencentBlueKing/bk-user/issues/162

**Comment by wklken** [comment]
bug 在重构版已修复
