### ISSUE TITLE
蓝鲸社区版6.1-用户管理ldap同步组织和用户成功，但是关联组织和用户失败

### ISSUE THREAD

**Issue by renxiaodong121** [TencentBlueKing/bk-user#515]
用户管理，ldap同步组织和用户正常，但是关联组织和用户失败，查看数据库同步日志提示“同步组织和用户的关联关系失败，失败原因：部门不存在”,查看组织和用户关联表发现没有数据
![1](https://user-images.githubusercontent.com/105206241/176133914-d0b069b8-ed5d-4520-b45f-7e54bfe604bb.jpg)
![3](https://user-images.githubusercontent.com/105206241/176135995-be548fa5-dcc4-47a7-af3c-94e61e7d9d79.jpg)
![微信图片_20220628163817](https://user-images.githubusercontent.com/105206241/176136110-87deb311-4ea7-43d2-bf70-3371ee7c1ae6.jpg)

**Comment by wklken** [comment]
同步的执行顺序:
- 同步部门/组
- 同步用户
- 建立用户-部门关系

--------

应该是部门没同步进来, 可以往上翻日志, 找下部门同步的报错

- 可能是ldap配置中部门配置有问题, 获取不到(概率比较高), 看具体报错
- 可能是部门入库失败, 看具体报错

1. ldap同步 FAQ 汇总: https://github.com/TencentBlueKing/bk-user/issues/429
2. 到社区发帖, 助手会协助解决  https://bk.tencent.com/s-mart/community/question

**Comment by renxiaodong121** [comment]
查看department_department部门入库正常，日志显示同步组织成功，
![4](https://user-images.githubusercontent.com/105206241/176157146-3780fd8d-1291-4200-89e0-a1ca5e5b9ac1.jpg)
![5](https://user-images.githubusercontent.com/105206241/176157178-7bff9cd3-2ebb-4a10-b303-cd7da117f248.jpg)
就是建立关联的时候失败

**Comment by wklken** [comment]
1. 这批部门的enabled=0, 代表并没有完成同步并激活
2. 这个issue第一张截图打的failed records, 用户的departments字段是空的, 代表拉这些用户的时候没有获取到用户的部门, 可能是配置有问题
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/2002216/176166617-0a9e7039-67f9-494f-9a35-171d6e537eeb.png">

**Comment by renxiaodong121** [comment]
请问下，department对应openldap什么字段，不是组织吗？

**Comment by ganzaofang** [comment]
> 请问下，department对应openldap什么字段，不是组织吗？

麻烦截图发下用户管理页面 ldap 目录的字段配置

**Comment by renxiaodong121** [comment]
![6](https://user-images.githubusercontent.com/105206241/176399339-ffeae69a-a347-409e-9528-8865beb428b5.jpg)
![7](https://user-images.githubusercontent.com/105206241/176399360-54986c20-3855-4e73-9e21-496425d341bb.jpg)
![8](https://user-images.githubusercontent.com/105206241/176399362-05364ec8-7b5d-472a-889b-fcb4fd5856b2.jpg)
![9](https://user-images.githubusercontent.com/105206241/176399364-23fc44de-d44a-4633-98b6-76f11727eae4.jpg)
![10](https://user-images.githubusercontent.com/105206241/176399367-714dbd5c-b21e-46b8-b7d2-adfcad9d700e.jpg)
