### ISSUE TITLE
前端在用户设置选择上级用户报错

### ISSUE THREAD

**Issue by Ysach** [TencentBlueKing/bk-user#53]
## API 地址
`api/v2/categories/%s/profiles/$`

## 应用
`saas`
## 报错信息
`KeyError: "Got KeyError when attempting to get a value for field `email` on serializer `ProfileSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'email'."
`
## 建议解决
`saas ---> bk_shell ---> organization ---> views ---> profiles.py`

### 原始代码
```python
    def list(self, request, category_id, validated_data):
        lookup_param = {
            "page": validated_data["page"],
            "page_size": validated_data["page_size"],
            "lookup_field": "category_id",
            "exact_lookups": [
                category_id,
            ],
        }
        # 全量用户返回体过大，只选择某些字段展示
        if validated_data["no_page"]:
            lookup_param.update({"fields": ["id", "username", "display_name"]})
```
### 修改后的代码
```python
    def list(self, request, category_id, validated_data):
        lookup_param = {
            "page": validated_data["page"],
            "page_size": validated_data["page_size"],
            "lookup_field": "category_id",
            "exact_lookups": [
                category_id,
            ],
        }
        # 全量用户返回体过大，只选择某些字段展示
        if validated_data["no_page"]:
            lookup_param.update({"fields": ["id", "username", "display_name", "email", "iso_code", "departments"]})
```

**Comment by IMBlues** [comment]
确实是个问题，感谢提醒。

除了描述中说到的问题，这里还有一个问题就是由于后端已经[去掉了 no_page 参数](https://github.com/TencentBlueKing/bk-user/blob/development/docs/precautions/upgrade_from_2dot2.md)，所以这里的全量拉取 admin 实际上只能拿到第一页内容。

而前端页面拉取全量上级的组件也不是很合理，需要改造成人员选择器分页拉取更好一些，这里的问题也能顺便解决。
