### ISSUE TITLE
用户管理邮箱的正则校验规则是否可以放开，反馈非 .com 后缀的邮箱都不能输入

### ISSUE THREAD

**Issue by ganzaofang** [TencentBlueKing/bk-user#549]
**功能需求背景，例如你遇到了什么问题**

用户管理邮箱的正则校验规则是否可以放开，反馈非 .com 后缀的邮箱都不能输入

**描述你觉得更好的解决方案**

建议换成更通用的正则校验规则

**额外信息**

![image](https://user-images.githubusercontent.com/30789292/177908720-ebbfe097-c3fa-436c-80a0-70ff8683d909.png)

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/pull/591

-----
对应分支: https://github.com/TencentBlueKing/bk-user/pull/596

对应的版本号: 2.3.5 (尚未提测/出包)
