### ISSUE TITLE
用户目录导出excel表异常

### ISSUE THREAD

**Issue by Canway-jessonwang** [TencentBlueKing/bk-user#550]
**重现方法**
在已有自定义字段的基础上新增内置字段，使用用户目录内的导出功能时会导致导出的excel表信息错乱，自定义字段的详细信息会填在内置字段的位置上
- 此处自定义字段为<性别>
- 新增内置字段为<账号过期时间><最近登录时间><创建时间>
![image](https://user-images.githubusercontent.com/90179140/177931477-a0fcf9c1-b9cd-4162-ac75-dc768cdf6288.png)

**预期行为**
excel表信息错乱，自定义字段的详细信息会填在内置字段的位置上
预期的正常行为
excel表逻辑清晰，和表头对应
**版本**
- v2.3.4
- 是企业版问题

**Comment by neronkl** [comment]
问题导致原因，进行表头写入的时候后，内置和非内置字段是分开写入，但是用户属性写入的时候，并没有区分而是顺序写入。从而导致的数据乱序

**Comment by wklken** [comment]
合并账号有效期分支

**Comment by wklken** [comment]
PR: https://github.com/TencentBlueKing/bk-user/pull/554

close
