### ISSUE TITLE
[规范] 代码提交规范

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#565]
- 配置使用项目中的pre-commint: black/pep8/isort/mypy检查
- 使用 `f-string` 而不是`%` or `.format`(日志打印除外)
- 使用 typehint
- 单元测试

**Comment by wklken** [comment]
协作开发中逐步构建规范, 降低未来的成本

**Comment by nannan00** [comment]
必须搭建本地环境，PR需要在本地进行测试OK后才能提交

**Comment by wklken** [comment]
协作开发:
- 导师制, 这边只review导师确认过的 PR(即, 需要内部完成review)
- 个人开发, 即使变更再少, 也需要经过严格自测(之前PR 中出现过语法错误/变量不存在等非常低级的错误)

**Comment by wklken** [comment]
每次review不超过 3 轮, 3 轮没通过, close, 由导师重新梳理/变更/测试后提交 PR

需要控制时间成本
