### ISSUE TITLE
设置初始密码为发送随机密码时，增加短信通知方式

### ISSUE THREAD

**Issue by abbyWJM** [TencentBlueKing/bk-user#566]
![企业微信截图_1657874349250](https://user-images.githubusercontent.com/101699798/179186819-6b1f74f2-3b2e-4d5b-bb3c-b1d51c967f62.png)
#117

**Comment by wklken** [comment]
感觉应该是没有对齐这个地方是否支持短信? 

两种处理方式:
1. 这里也要支持短信, 那么 
   1.1 后台需要实现这里的短信发送
   1.2 增加前端展示模板

2. 这里暂时不支持短信, 那么
   2.1 前端 发送随机密码这里, 需要保留原来的方式, 只有content, 只有 *_mail_config

-----------------

**Comment by wklken** [comment]
![Uploading 企业微信截图_36049897-6f52-4dfd-a842-875835572e38.png…]()
