### ISSUE TITLE
发布支持【二进制/Smart】格式包

### ISSUE THREAD

**Issue by Laotanling** [TencentBlueKing/bk-user#6]
**用文字描述你遇到的问题**

请用简练的文字描述你遇到的问题，问题描述的清晰程度决定了问题被解决的效率。

**重现方法**

请描述问题重现的方法，如果不方便描述，可以通过截图或者视频辅助。

**预期行为**

预期的正常行为

**版本**
- 提供用户管理的具体版本号
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by IMBlues** [comment]
首先做一些释义：
- 蓝鲸 SaaS 框架（blueapps）本身并不是规范，而一种开发使用的 SDK。如果不熟悉 Django 或 蓝鲸体系的开发确实推荐使用 blueapps 作为入门选择
- 用户管理 SaaS 从一开始就没有使用 blueapps，所以后面也不会引入

另外我猜测你说的是蓝鲸 Smart 应用提供的部署规范，用户管理 SaaS 确实通过 Smart 的方式提供服务。同时，有几点需要在这里说明：
- 开源仓库聚焦于通过更通用的方式部署，例如已经提供的 [Helm Chart](https://github.com/TencentBlueKing/bk-user/blob/master/deploy/helm/README.md)，完备的容器化部署也是当前蓝鲸整体方向。所以开源仓库应该不会包含 Smart 相关文件（会挪入到出包流水线）。
- 同时我们会保证原来的发布渠道保持一致，无论是企业版还是社区版，请通过原来的方式获取 Smart 包。
- 当前开源版本还没有正式发布 release，预计在本月底发布 v2.3.0(可以查看 [milestone](https://github.com/TencentBlueKing/bk-user/milestones))，届时会在原来的渠道推送 Smart 包。

**Comment by Laotanling** [comment]
我如果想用开源的用户管理saas,替换原有的saas该如何操作呢？

**Comment by IMBlues** [comment]
目前需要等到本月底的 2.3.0 版本发布，会同步更新对应的 Smart 包和 API 的后台安装包，到时向原渠道申请即可

**Comment by Laotanling** [comment]
没有对应的渠道，到时候github上会有吗

**Comment by IMBlues** [comment]
原来你是怎么获取到用户管理 SaaS 的呢？GitHub 目前只会放容器化部署的内容

**Comment by Laotanling** [comment]
原来是社区版基础包安装的，现在想在用户管理sass加入一些我们自己的功能，所以想用开源的用户管理sass替换原有的sass

**Comment by IMBlues** [comment]
开源代码对原来社区版的内容做了小幅度重构，直接替换原有 Smart SaaS 的步骤可能略繁琐，我们这里暂时不能提供。

建议等待发布 2.3.0，可以在这个版本的产出物基础上来做自己的修改。

**Comment by IMBlues** [comment]
对应流水线已就绪，近期将发布二进制包

**Comment by Laotanling** [comment]
没看到呀

**Comment by IMBlues** [comment]
@Laotanling 

https://github.com/TencentBlueKing/bk-user/releases/tag/v2.3.0-beta.1

这里已经发布了，目前还只是 beta 版本，如果部署过程中有问题可以新开 issue 提出来
