### ISSUE TITLE
复杂度分析

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#613]
## Part0: 日志/报错/可观测性

这块的缺失, 给问题排查带来了比较大的阻碍; 
已经优化了几轮, 补齐了大部分日志打印/上下文, 增加调用来源app_code/request_id等等, 并且把后台报错也向上传递到了SaaS, 近期在接入otel

仍然存在的问题:
1. 日志全部输出到标准输出, 混在一起, 导致非常难以捞日志
2. 同步相关的过程日志过多

## <del> Part1: 整体调用链路及架构 </del>

> 前端vue -> SaaS -> SDK -> API

存在一个由 API 反向生成的 SDK 嵌入到了 SaaS; 

并且, SaaS 调用 API 除了 SDK, 还存在`call_through`透传的方式; 

另外, 通过 SDK 调用 API 拼装了一批 headers, 用于控制返回值等 [bkuser_shell/apis/viewset.py](https://github.com/wklken/bk-user/blob/47e76c09201bfbbaf3f5748e7413cb353f604ec2/src/saas/bkuser_shell/apis/viewset.py#L168)

本身功能并不多, 是否可以考虑:
1. 简化甚至去掉SDK, 使用独立文件封装
2. 简化SaaS到API之间的协议, 去掉大部分header封装 (可能需要引入/api/v3)
3. 优化报错提示, 后台报错到SaaS再到前端, 直接在页面可见

## <del> Part2: API auth的复杂度 (**运维切换耗时最多**)</del> 

> 最早没有api auth, 后来也没有统一接入esb走jwt, 而是实现了自定义token进行的api auth

后来优化实现 [bkuser_core/enhanced_account/authentication.py](https://github.com/wklken/bk-user/blob/47e76c09201bfbbaf3f5748e7413cb353f604ec2/src/api/bkuser_core/enhanced_account/authentication.py#L212)

三种认证, 四种场景:
1. app_code / app_secret (用于容器化前后台调用的接口认证, 此时saas 和api的app_code/app_secret一致)
2. TOKEN 认证 (原先的token认证, 目前在逐步去除, 外部版已去除, 内部上云版规划去除中)
3. jwt (内外部版均已支持, 从esb过来的流量)
4. 无认证 (原先二进制版, 未暴露服务, 无认证)

目前, 需要逐步推动去掉 2/4; 只保留 1/3; 主推 3;(只有本项目自己模块内调用用 1)

## <del>  Part3: API 层的复杂度 (**bug重灾区**) </del> 

当前由于历史原因, 存在
- `/api/v1`(login在用)
- `/api/v2`(当前主要暴露的接口)
- `/api/v3`(已有实现, saas有两个接口调用)

存在问题:
- `/api/v2`由于接口非常灵活, 同一个viewset有多重继承, 并且由参数控制了input slz/output slz以及一些过滤的逻辑, 导致整体耦合在一起; 
    - 不好排查问题
    - 目前已经有性能问题, 但是难以优化, 因为一些参数已经放出, 使用方误用/滥用无法控制
- `/api/v3`当前的实现方案还是过于灵活, 需要考虑去掉重做方案

目标: 对外提供简单 API, 所有参数可控; 降低参数与逻辑的耦合; 强单一职责, 一个viewset只做一件事情; 

- 给 SaaS 的API, 尽量灵活(可控的, 减少开发量)
- 给外部的 API, 尽量简单(不可控, 降低风险)

## Part4: 目录同步的复杂度 (**排查问题耗时最多**)

当前的plugin及同步:
- local
- ldap
- mad
- http
- tof

重点是local+ldap/mad; 

当前存在的问题:
1. 过于抽象, 层层嵌套;
2. 使用了十分动态的语法糖实现, 导致很难跟踪代码调用链路, 很难拿到明确的报错及堆栈; 

需要考虑的处理:
1. 简化模型, 减少抽象(足够当前 5 种plugin即可), 统一的数据模型+适当的adapter;
2. 去动态化, 去掉dataclass(post_init)和get_attr等语法糖, 明确的注入及调用链, 明确的报错堆栈
3. 减少`约定`; 

可以考虑设计一个新的数据模型+plugin模型, 逐步迁移;

## <del>  Part6: 权限模块 </del> 

权限模型比较特殊, 资源是基于目录的递归(都是同一种类型, 但是带层次)

所以实现时, 做了大量定制;

目前这块逻辑需要考虑如何优化, 必要时考虑重新设计权限模型(尽量简化)

```
iam_filter_actions = ("list", "list_tops")

=>  self.filter_queryset
=>  
```

https://github.com/wklken/bk-user/blob/891cb75458ccf514e0e87415784beee51617f4a7/src/api/bkuser_core/apis/v2/viewset.py#L231

问题: 权限落在api上, api需要处理来自saas的请求(有iam), 也要处理来自esb的请求, 此时 SaaS 的场景会更多, 导致 api 很多地方没法配合理的权限(多个场景调用统一个 API) => **应该把权限控制移动到saas层**

## Part6: 分层及缓存

- 分层: 目前缺少一层中间抽象层, 例如service; (由于是django models, 这层本身就比较模糊), 但是需要考虑切一层出来
- 缓存: 目前用的 cache_page(有bug), django localmem(jwt获取公钥缓存)

考虑的处理方式:
- api层到viewset
- service层 (缓存控制/权限控制)
- model层

**Comment by wklken** [comment]
## 权限的实现

------

### saas

saas调用api, 根据viewset中是否配置ACTION_ID或生成client是否加了force_action_id, 往header头里面放user_iam + action

问题: 
1. 存在忘了放action_id的
2. action_id 不对的,例如前面资源是settings, 实际检查应该检查settings的对应 category是否有权限

------
### API

继承 AdvancedModelViewSet
1. list接口 => iam_filter_actions 配置(基类是空的, 子类很多忘了配) + self.filter_queryset(list实现必须调用这个方法, 否则权限也不会生效)

2. 主动调用 check_object_permissions(request, instance)  (存在忘了调用的)

3. self.get_object -> drf filter_queryset + check_object_permissions -> PermissionClass = [IAMPermission] ->  has_object_permission 

4. 只声明 PermissionClass = [IAMPermission], 调用这个view的时候 => has_permission => 拿request_id中的 action_id 判断非关联资源实例的操作

**Comment by wklken** [comment]
# 处理(待讨论)

- 只保留 `models.py`
- 增加 `/api/v3`
- saas重写, 依赖`/api/v3`, 并且权限控制转移到saas(api不再涉及权限)
- 逐步下掉`/api/v1/`和`/api/v2/`
- API 目录同步机制重写, 逐个plugin迁移

**Comment by wklken** [comment]
## 前端调用后台的所有接口


```
src/pages/src/api/index.js:60:    return http.queue.cancel(requestId);
src/pages/src/store/index.js:68:      return http.get('api/v2/me/');
src/pages/src/store/index.js:71:      return http.get('api/v2/version_logs_list/');
src/pages/src/store/index.js:74:      return http.get('api/footer/');
src/pages/src/store/modules/password.js:22:      return http.get(`api/v1/password/check_token/?token=${params}`);
src/pages/src/store/modules/password.js:26:      return http.post('api/v1/password/reset_by_token/', params);
src/pages/src/store/modules/password.js:30:      return http.post('api/v1/password/modify/', params);
src/pages/src/store/modules/password.js:34:      return http.post('api/v1/password/reset/', params);
src/pages/src/store/modules/catalog.js:51:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:57:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:63:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:69:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:75:      return http.post(`api/v2/categories/${params.id}/sync/`);
src/pages/src/store/modules/catalog.js:81:      return http.post(`api/v2/categories/${params.id}/sync/`, params.data);
src/pages/src/store/modules/catalog.js:89:      return http.post(url, {
src/pages/src/store/modules/catalog.js:97:      return http.delete(url, config);
src/pages/src/store/modules/catalog.js:103:      return http.patch(url, params.data, config);
src/pages/src/store/modules/catalog.js:108:      return http.patch(url, params.data, config);
src/pages/src/store/modules/catalog.js:113:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:121:      return http.put(url, params.data, config);
src/pages/src/store/modules/catalog.js:126:      return http.put(url, params.data, config);
src/pages/src/store/modules/catalog.js:131:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:136:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:143:      return http.post(url, params.data, config);
src/pages/src/store/modules/catalog.js:148:      return http.put(url, params.data, config);
src/pages/src/store/modules/catalog.js:153:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:158:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:168:      return http.post(url, obj, config);
src/pages/src/store/modules/catalog.js:175:      return http.post(url, params.data, config);
src/pages/src/store/modules/catalog.js:180:      return http.put(url, params.data, config);
src/pages/src/store/modules/catalog.js:185:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:190:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:200:      return http.post(url, obj, config);
src/pages/src/store/modules/catalog.js:207:      return http.get(url, config);
src/pages/src/store/modules/catalog.js:211:      return http.put(url, params.data, config);
src/pages/src/store/modules/organization.js:33:      return http.get(`api/v2/departments/?only_enabled=${onlyEnabled}`);
src/pages/src/store/modules/organization.js:40:      return http.get(`api/v2/departments/${params.id}/`);
src/pages/src/store/modules/organization.js:46:        return http.get(`api/v2/categories/${id}/departments/search/?keyword=${keyword}&max_items=${searchLength}&with_ancestors=true`);
src/pages/src/store/modules/organization.js:48:      return http.get(`api/v2/categories/${id}/departments/search/?keyword=${keyword}&max_items=${searchLength}`);
src/pages/src/store/modules/organization.js:52:      return http.post('api/v2/departments/', params);
src/pages/src/store/modules/organization.js:56:      return http.delete(`api/v2/departments/${params.id}/`);
src/pages/src/store/modules/organization.js:61:      return http.patch(`api/v2/departments/${id}/`, { name });
src/pages/src/store/modules/organization.js:65:      return http.patch(`api/v2/${params.nodeType}/${params.id}/switch_order/${params.upId}/`);
src/pages/src/store/modules/organization.js:70:      return http.post(`api/v2/departments/${id}/profiles/`, { profile_id_list: idList });
src/pages/src/store/modules/organization.js:75:      return http.get(`api/v2/search/detail/?keyword=${params.searchKey}&max_items=${params.searchLength}&only_enabled=true`);
src/pages/src/store/modules/organization.js:87:      return http.post('api/v2/profiles/', params);
src/pages/src/store/modules/organization.js:92:      return http.delete('api/v2/batch/profiles/', config);
src/pages/src/store/modules/organization.js:97:      return http.patch(`api/v2/profiles/${id}/`, data);
src/pages/src/store/modules/organization.js:101:      return http.patch('api/v2/batch/profiles/', params);
src/pages/src/store/modules/organization.js:105:      return http.get(`api/v2/categories/${params.id}/profiles/?no_page=true`);
src/pages/src/store/modules/organization.js:110:      return http.get(`api/v2/categories/${id}/profiles/?keyword=${keyword}&page=${page}&page_size=${pageSize}`);
src/pages/src/store/modules/organization.js:114:      return http.get(`api/v2/profiles/${params.id}/`);
src/pages/src/store/modules/organization.js:119:      return http.post(`/api/v2/profiles/${id}/restoration/`);
src/pages/src/store/modules/organization.js:123:      return http.get(`api/v3/profiles/?${params}`);
src/pages/src/store/modules/organization.js:127:      return http.get(`api/v3/departments/?${params}`);
src/pages/src/store/modules/setting.js:21:      return http.get('api/v2/fields/manageable/');
src/pages/src/store/modules/setting.js:24:      return http.post('api/v2/fields/', params.data);
src/pages/src/store/modules/setting.js:27:      return http.delete(`api/v2/fields/${params.id}/`);
src/pages/src/store/modules/setting.js:30:      return http.patch(`api/v2/fields/${params.id}/`, params.data);
src/pages/src/store/modules/setting.js:34:      return http.get('api/v2/fields/');
src/pages/src/store/modules/setting.js:39:      return http.patch(`api/v2/fields/${id}/order/${index}/`);
src/pages/src/store/modules/setting.js:43:      return http.patch('api/v2/fields/visible/', {
src/pages/src/store/modules/audit.js:27:      return http.get(`api/v2/audit/login_log/?start_time=${startTime}&end_time=${endTime}&page=${page}&page_size=${pageSize}`);
src/pages/src/store/modules/audit.js:38:      return http.get(`api/v2/audit/operation_logs/?start_time=${startTime}&end_time=${endTime}&page=${page}&page_size=${pageSize}${keyword && (`&keyword=${keyword}`)}`);
src/pages/src/store/modules/audit.js:44:      return http.get(`${url}/api/v2/audit/login_log/export/?start_time=${startTime}&end_time=${endTime}`);
```

**Comment by wklken** [comment]
考虑第一期的处理: 

1. 将 saas的逻辑挪到api层 (saas 直接将请求代理到api, 需要考虑登录态如何处理)
2. api 层saas viewset逻辑, 直接访问 db,
3. 权限控制在 saas api处理(需小规模调整)

-------
好处:
1. 解耦 saas api/open api
2. 去掉 saas 主体逻辑/去掉saas sdk/去掉 saas 权限处理等
3. 未来可以直接去掉saas 

问题:
1. 登录态如何处理
2. 怎么做透传

**Comment by wklken** [comment]
saas 的version_log封装去掉, 直接以md的文件展示处理; (性能问题 / 封装报错无法调试)

**Comment by IMBlues** [comment]
之前的思路，仅供参考：

SaaS 之所以存在的目的，是和 API 的逻辑做分离（虽然目前做的不是很好），更关注 SaaS 的行为和表现层。相当于 client 端，依托服务端 API 做各种操作。类似之前讨论可能会将“个人中心”页面作为另一个 client 端。

**Comment by wklken** [comment]
@nannan00 
2.5.x 之后的剩余工作

1. 上云版独立集群部署, 使用统一容器化, 并且拆分日志
2. 目录同步逻辑, 配合多渠道登录一起优化(重点处理ldap的, 解决确定的问题, 减少咨询量)
3. 敏感字段/字段加密等
4. 新版OpenAPI `/api/v3`协议设计实现, 需要解决过滤/翻页/性能/缓存等问题

**Comment by wklken** [comment]
close
多渠道登录/多租户设计时降低复杂度; 同时根据需求设计新版并提供`/api/v3`协议
