### ISSUE TITLE
用户目录接入LDAP

### ISSUE THREAD

**Issue by czzxbo** [TencentBlueKing/bk-user#619]
**用文字描述你遇到的问题**

用户目录接入LDAP，同步成功，组架和人员都已同步成功，LDAP账号格式：用户名@登录域
**问题：用LDAP账号登录PAAS平台报错，提示：账户或者密码错误，请重新输入**

**预期行为**

预期的正常行为：使用LDAP账号正常访问paas平台

**版本**
- 具体版本号：社区版6.1.1-beta1

![用户管理-组架](https://user-images.githubusercontent.com/111425264/185088515-6ff400ec-3b09-4ce7-bbf0-9a2d95998d81.png)
![PAAS登录报错](https://user-images.githubusercontent.com/111425264/185088503-83b52c88-5f20-440a-8119-00412f6a9a7b.png)

**Comment by wklken** [comment]
登录代码: 
- https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/profiles/v2/views.py#L551
- https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/categories/plugins/ldap/login.py#L28

安全考虑所有报错都会统一返回 `密码错误`;

------
调试:
1. 获取usermgr的日志, 里面应该有报错堆栈
2. 可以将usermgr的日志级别改成debug, 复现, 日志中会打印更多的信息

**Comment by czzxbo** [comment]
你好，


问题已解决，感谢支持~


———————————————————


周雪松             Cedar ZHOU
运维工程师      Operation and Maintenance Engineer
运维中心          Operation and Maintenance Center  
 
北京小波科技有限公司 | Beijing X-BO Technology Co., Ltd.
 
地址：北京市海淀区西四环北路143号 邮编：100143
Add：No.143 West 4th Ring North Road, Haidian District, Beijing 100143, P.R. China
Tel：+86 10 58739392    M: +86 18766998261
***@***.***






---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2022年8月18日 13:58收件人 ***@***.******@***.***>抄送人 ***@***.******@***.***> ,
 ***@***.******@***.***>主题 回复： [TencentBlueKing/bk-user] 用户目录接入LDAP (Issue #619)

你好，
按照调试1.获取usermgr日志：
以下为分别获取的 api.log、beat.log、worker.log最新报错日志，还请协助













---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2022年8月18日 11:05收件人 ***@***.***>抄送人 ***@***.***> ,
 ***@***.***>主题 Re: [TencentBlueKing/bk-user] 用户目录接入LDAP (Issue #619)

登录代码:
https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/profiles/v2/views.py#L551 https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/categories/plugins/ldap/login.py#L28安全考虑所有报错都会统一返回 密码错误;
调试:
获取usermgr的日志, 里面应该有报错堆栈 可以将usermgr的日志级别改成debug, 复现, 日志中会打印更多的信息—

**Comment by czzxbo** [comment]
你好，
按照调试1.获取usermgr日志：
以下为分别获取的 api.log、beat.log、worker.log最新报错日志，还请协助













---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2022年8月18日 11:05收件人 ***@***.***>抄送人 ***@***.***> ,
 ***@***.***>主题 Re: [TencentBlueKing/bk-user] 用户目录接入LDAP (Issue #619)

登录代码:
https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/profiles/v2/views.py#L551 https://github.com/TencentBlueKing/bk-user/blob/master/src/api/bkuser_core/categories/plugins/ldap/login.py#L28安全考虑所有报错都会统一返回 密码错误;
调试:
获取usermgr的日志, 里面应该有报错堆栈 可以将usermgr的日志级别改成debug, 复现, 日志中会打印更多的信息—
