### ISSUE TITLE
首次登录强制修改密码，企业版与社区版无相同跳转操作

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#627]
![image](https://user-images.githubusercontent.com/49228807/185834849-dc24ce5c-3358-422e-86d2-a66a85596555.png)

**Comment by Canway-shiisa** [comment]
这个问题 社区版已经解决，在bk_user优化重构过程是否会同步一致呢 @wklken

**Comment by wklken** [comment]
二进制版的, 在 bk-PaaS 仓库里面,跟bk-user无关; 之前有 PR 提错了

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/pull/630

**Comment by Zoeyzhou11** [comment]
> 二进制版的, 在 bk-PaaS 仓库里面,跟bk-user无关; 之前有 PR 提错了

亮哥，我再确认一下，这个需求是不是需要paas的开发来做，再提到bk_paas的相关分支是吗？ @wklken

**Comment by Zoeyzhou11** [comment]
> 二进制版的, 在 bk-PaaS 仓库里面,跟bk-user无关; 之前有 PR 提错了

龙哥，我确认下，所以现在这个需求是需要去bk_paas那边去提pr是嘛？

**Comment by wklken** [comment]
是的

https://github.com/TencentBlueKing/bk-user/pull/630#issuecomment-1221992164

**Comment by Zoeyzhou11** [comment]
> 是的
> 
> [#630 (comment)](https://github.com/TencentBlueKing/bk-user/pull/630#issuecomment-1221992164)



> 是的
> 
> [#630 (comment)](https://github.com/TencentBlueKing/bk-user/pull/630#issuecomment-1221992164)

https://github.com/Tencent/bk-PaaS/pull/1034已提，麻烦亮哥看看 @wklken

**Comment by wklken** [comment]
reviewed

**Comment by wklken** [comment]
https://github.com/Tencent/bk-PaaS/releases/tag/2.14.32
