### ISSUE TITLE
添加用户页面中“最近登录时间”、“创建时间”是不操作的，建议前端删除

### ISSUE THREAD

**Issue by shenguli** [TencentBlueKing/bk-user#633]
**功能需求背景，例如你遇到了什么问题**

为什么会有这个点子？或者遇到了什么问题驱使你需要这个功能？

**描述你觉得更好的解决方案**

可以举例子来描述你觉得怎样做会更好

**额外信息**

任何你觉得有助于理解的信息

**Comment by wklken** [comment]
去掉这两个字段的展示(目前展示出来了, 不能编辑的状态)

**Comment by wklken** [comment]
2.5.x已处理
