### ISSUE TITLE
ldap可以同步用户，但是在users中看不到同步过来的用户

### ISSUE THREAD

**Issue by linyanan521** [TencentBlueKing/bk-user#649]
**用文字描述你遇到的问题**

ldap可以同步用户，但是在users中看不到同步过来的用户，用同步过来的ldap用户也可以登录到系统

**重现方法**

![image](https://user-images.githubusercontent.com/48748534/187368835-a340805c-8c66-40bb-bec7-8f55054a46ac.png)
![image](https://user-images.githubusercontent.com/48748534/187368948-6467107e-8d71-4b7f-8b29-425b1e784bec.png)
![image](https://user-images.githubusercontent.com/48748534/187368976-90e11da4-a0e0-4e15-b7d0-6a245630a4a0.png)

**预期行为**

预期是users中可以看到同步过来的ldap用户

**版本**
6.1.1
-用户管理的版本
2.3.4-beta.20
- 是否是企业版问题？
- 否

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容
ldap配置字段
选择拉取节点
*
ou=Users,domainName=wanganxin.com,o=domains,dc=iartemis,dc=cn
从指定的组织开始拉取数据，填写对应的 distinguished name，比如 ou=org1,dc=example,dc=org

用户对象类
*
mailUser
用户对象过滤
*
(&(enabledService=cmdb)(objectClass=mailUser)(accountStatus=active))
组织架构类
*
organizationalUnit
用户基础字段
收起
蓝鲸用户管理字段

对应 ldap 目录字段

用户名
cn
中文名
displayName
邮箱
mail
手机号
telephonenumber

[api日志.txt](https://github.com/TencentBlueKing/bk-user/files/9450427/api.txt)

**Comment by wklken** [comment]
看下用户是否是同步过来, 但是所属的组织没有同步成功, 导致其状态异常

- `select * from profiles_profile`
- `select * from departments_department`
- `select * from departments_department_profiles`

**Comment by linyanan521** [comment]
mysql> select * from profiles_profile
    -> ;
+----+----------------------------+----------------------------+------------------+----+-------------------------+-----------+-----------+-----------+---------------+-------------+--------------+------+------------------------------------------------------------------------------------------+--------+--------------+---------------------+------+------+----------+---------------+----------+--------------+----------+--------+---------+------------------------------------------------------------------+----------------------+
| id | create_time                | update_time                | username         | qq | email                   | telephone | wx_userid | wx_openid | domain        | category_id | display_name | logo | password                                                                                 | status | staff_status | password_valid_days | type | role | position | time_zone     | language | country_code | iso_code | extras | enabled | code                                                             | password_update_time |
+----+----------------------------+----------------------------+------------------+----+-------------------------+-----------+-----------+-----------+---------------+-------------+--------------+------+------------------------------------------------------------------------------------------+--------+--------------+---------------------+------+------+----------+---------------+----------+--------------+----------+--------+---------+------------------------------------------------------------------+----------------------+
|  1 | 2022-08-29 09:32:14.319235 | 2022-08-30 08:05:40.554755 | admin            |    |                         |           |           |           | default.local |           1 |              | NULL | pbkdf2_sha256$260000$Q0ZSFtpeuhIxSr1YNfg19V$aP3rVHMtcP9LhOZfpJMATQUzAtz35iuM+NXaGS65fyQ= | NORMAL | IN           |                  -1 |      |    1 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       1 | NULL                                                             | NULL                 |
|  3 | 2022-08-30 02:55:17.111402 | 2022-08-30 02:55:17.111449 | runfeng.liu      |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 8b8155d0ea191ea38a82c3367250cc915cc93ec60ea25e5974526f89e85f9f56 | NULL                 |
|  4 | 2022-08-30 02:55:17.111609 | 2022-08-30 02:55:17.111649 | junjun.wang      |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 3f8d17d99fba8a7488e094153deebd9d37f0e8bbcb1b8abb99263c20e5e24fa3 | NULL                 |
|  5 | 2022-08-30 02:55:17.111779 | 2022-08-30 02:55:17.111801 | shaodong.lin     |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 0dcb3ad17ee58a5937a3d2de225987db2d7f9180b16679d862416a9c95401a68 | NULL                 |
|  6 | 2022-08-30 02:55:17.111938 | 2022-08-30 02:55:17.111964 | waibao.www       |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 9bd51013cf839743d925c0ba55fbdf7399d99adaaa2f656faa98ab7a54040f1e | NULL                 |
|  7 | 2022-08-30 02:55:17.112090 | 2022-08-30 02:55:17.112111 | mr.ye            |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | eed62250c2f7513a867699b2b2d9af1c493194448db45a07acf768c421573770 | NULL                 |
|  8 | 2022-08-30 02:55:17.112231 | 2022-08-30 02:55:17.112252 | curry            |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 637ddf149df967b4c0d8de726c472f17bc35be0eb0463ba4282d55ef08026716 | NULL                 |
|  9 | 2022-08-30 02:55:17.112371 | 2022-08-30 02:55:17.112392 | xiaozhang        |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 281d9c3425f5523052616eb86d39b712d8be3dbf460429fc93e26f8788e179cb | NULL                 |
| 10 | 2022-08-30 02:55:17.112511 | 2022-08-30 02:55:17.112531 | xiaoming         |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 1d854cfbe0cce2f8e429301b701c31d40deac647ce18c19109a7113c3b24eeec | NULL                 |
| 11 | 2022-08-30 02:55:17.112667 | 2022-08-30 02:55:17.112690 | na.li            |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 1be6e92361a5932d72815aaff73581f2bc962612b2aefa34c1c28a8373452c14 | NULL                 |
| 12 | 2022-08-30 02:55:17.112811 | 2022-08-30 02:55:17.112832 | xiaowen          |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 21525ae81ff8e1922f6631b3ff47cd1cbbe74e484d7a9f1c2cb1b87050f489fc | NULL                 |
| 13 | 2022-08-30 02:55:17.112951 | 2022-08-30 02:55:17.112971 | mattermost       |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 1eda880780d40de660f4d846d16ae9da43edaf9ae449302222c0be8fcd3cbb5e | NULL                 |
| 14 | 2022-08-30 02:55:17.113089 | 2022-08-30 02:55:17.113110 | workweixin528d4f |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 97bc1e58c03dbf8123f3817eb4e9fe72639051d2790ae5408d3526875582954e | NULL                 |
| 15 | 2022-08-30 02:55:17.113229 | 2022-08-30 02:55:17.113249 | de.wu            |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 94a0fba2ce1fd306e85618d7165a2d909baae50ba0d76ffff055e193bf73d087 | NULL                 |
| 16 | 2022-08-30 02:55:17.113368 | 2022-08-30 02:55:17.113389 | info             |    |                         |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       0 | 7bcc09bed70c4c3fbd0070fc9742cdd21c430356480f09745a0a63456d2c9159 | NULL                 |
| 18 | 2022-08-30 03:12:18.961170 | 2022-08-30 03:37:20.872199 | you.zhang        |    | you.zhang@wanganxin.com |           |           |           | wanganxin.com |           2 | 张友         | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       1 | c477135a1958d42676e99788f12f06943bf7b353f14f416014cd790a30215d24 | NULL                 |
| 20 | 2022-08-30 03:12:53.020519 | 2022-08-30 08:07:36.516448 | yanan.lin        |    | yanan.lin@wanganxin.com |           |           |           | wanganxin.com |           2 |              | NULL |                                                                                          | NORMAL | IN           |                  -1 |      |    0 |        0 | Asia/Shanghai | zh-cn    | 86           | CN       | {}     |       1 | 6dc91f3154160cd7aee13336204c2a9fac68a4467ea9e29a9125cf2d6131f262 | NULL                 |
+----+----------------------------+----------------------------+------------------+----+-------------------------+-----------+-----------+-----------+---------------+-------------+--------------+------+------------------------------------------------------------------------------------------+--------+--------------+---------------------+------+------+----------+---------------+----------+--------------+----------+--------+---------+------------------------------------------------------------------+----------------------+
17 rows in set (0.00 sec)

mysql> select * from departments_department;
+----+----------------------------+----------------------------+-----------+-------+-------+-------------+-----+------+---------+-------+-----------+---------+--------------------------------+
| id | create_time                | update_time                | name      | code  | order | category_id | lft | rght | tree_id | level | parent_id | enabled | extras                         |
+----+----------------------------+----------------------------+-----------+-------+-------+-------------+-----+------+---------+-------+-----------+---------+--------------------------------+
|  1 | 2022-08-29 09:32:14.321281 | 2022-08-29 09:32:14.321316 | 总公司    | NULL  |     1 |           1 |   1 |    2 |       2 |     0 |      NULL |       1 | {}                             |
|  3 | 2022-08-30 02:55:17.013741 | 2022-08-30 02:55:17.013788 | Users     | Users |     1 |           2 |   1 |    2 |       1 |     0 |      NULL |       1 | {"type": "organizationalUnit"} |
+----+----------------------------+----------------------------+-----------+-------+-------+-------------+-----+------+---------+-------+-----------+---------+--------------------------------+
2 rows in set (0.00 sec)

mysql> select * from departments_department_profiles
    -> ;
+----+---------------+------------+
| id | department_id | profile_id |
+----+---------------+------------+
|  1 |             1 |          1 |
+----+---------------+------------+
1 row in set (0.00 sec)

**Comment by linyanan521** [comment]
![image](https://user-images.githubusercontent.com/48748534/187579336-9cf83e36-fde4-41db-994f-6c43959054cd.png)
我们的ldap中没有部门，怎么来解决这个问题？department属性在哪添加？

**Comment by ganzaofang** [comment]
![image](https://user-images.githubusercontent.com/30789292/187626802-51b0c279-4d49-448f-b2e8-9865a0e43ce2.png)
![image](https://user-images.githubusercontent.com/30789292/187626903-3648aaab-6905-415c-95d9-f8757ad7c511.png)
用户基础字段
收起
选择拉取节点
*
ou=Users,domainName=wanganxin.com,o=domains,dc=iartemis,dc=cn
从指定的组织开始拉取数据，填写对应的 distinguished name，比如 ou=org1,dc=example,dc=org

用户对象类
*
mailUser
用户对象过滤
*
(&(enabledService=cmdb)(objectClass=mailUser)(accountStatus=active))
组织架构类
*
organizationalUnit
用户基础字段
收起
蓝鲸用户管理字段

对应 ldap 目录字段

用户名
sn
中文名
displayName
邮箱
mail
手机号
telephonenumber
自定义字段
展开
用户组字段 (如果不需要使用用户组，请将以下字段留空)
收起
用户组对象类
groupOfNames
用户组对象过滤
(objectclass=groupOfNames)
用户组名字段
cn
用户组描述字段
description
用户组关联字段

某些 LDAP 服务(如 OpenDJ)需要填写成 isMemberOf

**Comment by ganzaofang** [comment]
> ![image](https://user-images.githubusercontent.com/48748534/187579336-9cf83e36-fde4-41db-994f-6c43959054cd.png) 我们的ldap中没有部门，怎么来解决这个问题？department属性在哪添加？

是否可以请用户在ldap中加个部门, 然后部门加个人, 测试下同步
