### ISSUE TITLE
ldap用户登录后没有权限，怎么分配权限

### ISSUE THREAD

**Issue by linyanan521** [TencentBlueKing/bk-user#650]
**用文字描述你遇到的问题**

ldap用户登录后没有权限，怎么分配权限

**重现方法**

ldap用户登录后没有权限，怎么分配权限
![image](https://user-images.githubusercontent.com/48748534/187578590-7c81776f-8bee-4521-a7fc-e36ce583027e.png)

**预期行为**

ldap用户登录后可以操作cmdb中的资源

**版本**
![G1LE6OLBG8GO@HR_I ~XTAX](https://user-images.githubusercontent.com/48748534/187578474-2a7d14da-d25d-4df9-9619-ce51c29d3853.png)

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wklken** [comment]
无权限, 各个产品页面有无权限申请弹窗, 点击会跳转权限中心申请权限;

使用超级管理员可以在权限中心直接分配权限; 
----

有产品使用上的问题, 在问答社区中发帖
