### ISSUE TITLE
新用户使用初始密码登入平台希望能实提示需要修改密码时，希望能实现自动跳转

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-user#706]
当前交互：需要手动点击跳转
<img width="678" alt="image" src="https://user-images.githubusercontent.com/110165979/192673976-45d37fdf-a3bd-4a48-a579-e91662f2b771.png">
期望：点击登陆后，若为首次登陆，则直接跳转到修改密码页面

**Comment by Xmandon** [comment]
1. 社区版不要用户点击“请修改密码”，登录成功后直接跳转到修改密码页面
2. 企业版同样处理

**Comment by wklken** [comment]
- 二进制版, bk-PaaS的 ft_upgrade_py3分支
- 容器化版, 基于develop分支切功能分支开发

**Comment by wklken** [comment]
已合并, 下个版本生效 (2.5.1)
