### ISSUE TITLE
用户管理升级到2.2.26会把随机发送密码的邮件模板清空（但实际模板内容还在，能正常发送出来）

### ISSUE THREAD

**Issue by xiaoge888168** [TencentBlueKing/bk-user#713]
<img width="1258" alt="企业微信截图_16653703714106" src="https://user-images.githubusercontent.com/39146216/194795163-9f69f2fd-454c-40f5-8f34-bbcf395e5152.png">

![image](https://user-images.githubusercontent.com/39146216/194796048-40d60a61-e085-4ea8-b88d-568236200c9c.png)

**Comment by wklken** [comment]
已知问题, 已定位, 处理中

**Comment by wklken** [comment]
related to #566

**Comment by wklken** [comment]
感觉应该是没有对齐这个地方是否支持短信? 

两种处理方式:
1. 这里也要支持短信, 那么 
   1.1 后台需要实现这里的短信发送
   1.2 增加前端展示模板

2. 这里暂时不支持短信, 那么
   2.1 前端 发送随机密码这里, 需要保留原来的方式, 只有content, 只有 *_mail_config

---

要么分两步走?  先修问题, 再加个issue开发支持?

**Comment by wklken** [comment]
refactor_saas分支
