### ISSUE TITLE
通过excel导入用户组织支持全量更新

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-user#728]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/110165979/196080711-5f0441d3-fc67-49f2-98b2-03186408aa1b.png">

**Comment by wklken** [comment]
导入组织:
1. 查询用户的就有组织关系, 删除(清理动作)
2. 根据新的组织, 执行原先的逻辑(创建或更新)

**Comment by wklken** [comment]
https://github.com/wklken/bk-user/blob/f58d356580b6cdd1ba8a2f15677120b8ab1cb984/src/api/bkuser_core/categories/plugins/local/syncer.py#L283

**Comment by Shutulee** [comment]
# 初版草案
## 风险分析
![image](https://user-images.githubusercontent.com/50794209/201250229-a0b8035a-531a-43da-9d8c-ba9e93414dfa.png)
## 方案说明
![image](https://user-images.githubusercontent.com/50794209/201250273-892e7285-56f8-47ab-a1bc-c9ad9dd09579.png)
![image](https://user-images.githubusercontent.com/50794209/201250297-a7059549-5cf9-4c63-a4a2-ca80d7aa3077.png)

**Comment by wklken** [comment]
单选框勾选应该附加参数在query里面   /xxxx?key=value

**Comment by wklken** [comment]
需要补充下前端的提示文本

**Comment by Canway-shiisa** [comment]
1.导入在旧的逻辑中就支持用户信息更新了，并且在部门处理上是：如果用户不存在于excel中指定的部门，会新增该用户(并且不会删除原有部门下的该用户)；
2. 该issue原始的需求是 部门处理上，变成可选=》假设导入的时候勾选<覆盖更新>，那如果excel中的用户不存在于指定部门中则新增，并且会将该用户从旧的部门中移除【新的原型感觉有点偏差，这个需要确认清楚】

**Comment by wklken** [comment]
新的逻辑: 如果不勾选, 同名用户的数据什么都不会做? 例如更新其某个属性? (相当于忽略所有同名的用户)

----

需要确认下
代码看着 OK

**Comment by Shutulee** [comment]
> 新的逻辑: 如果不勾选, 同名用户的数据什么都不会做? 例如更新其某个属性? (相当于忽略所有同名的用户)
> 
> 需要确认下 代码看着 OK

没问题。后续预期是导入操作会分「批量新增」和「批量更新」两个入口来做。「批量新增」只做新增（即不勾选的逻辑），「批量更新」只做更新。

**Comment by Canway-shiisa** [comment]
![image](https://user-images.githubusercontent.com/90179140/205020293-9b5f4928-51ff-49c2-b36f-cb9c64188e38.png)
=>
1.【前端】如果勾选<覆盖更新>，需要在导入接口中新增 query参数：is_overwrite  =true；未勾选<覆盖更新>则传递is_overwrite  =false
2.接口示例：
/api/v1/web/categories/1/operations/sync_or_import/?is_overwrite=true

**Comment by Shutulee** [comment]
## 评审后方案
![image](https://user-images.githubusercontent.com/50794209/205654905-b4cd06b1-0e10-4bca-ad83-75a1c17f95fc.png)

**Comment by wklken** [comment]
需要协调前端开发, 增加交互和请求参数, 合入分支 pre_2.5.2
