### ISSUE TITLE
itsm 中无法获取到用户管理中的用户

### ISSUE THREAD

**Issue by zm007520** [TencentBlueKing/bk-user#735]
![image](https://user-images.githubusercontent.com/10609456/196368324-2c614d7c-0773-4a9b-98ba-8daf4c1c5812.png)
itsm 中无法获取到用户管理中的用户，admin都获取不到，无法创建服务
服务流程流程中审批人也无法找到用户管理中的用户

**Comment by wklken** [comment]
这个接口调用报错了吧? 

看 URL 拼错了, 这里应该拼接的是 ESB 组件调用地址, URL 中不应该出现 `/o/bk_itsm/`

需要找ITSM开发处理
