### ISSUE TITLE
PUT /password 接口传递的init_mail_config参数及reset_mail_config参数异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#744]
异常表现：修改用户目录-密码设置 邮件模板的数据失效；

页面修改：
![image](https://user-images.githubusercontent.com/90179140/196682344-ddd11453-63e4-4dd7-8c7e-e6f454ad2819.png)

相关接口及传参：
<img width="815" alt="Snipaste_2022-10-19_19-44-32" src="https://user-images.githubusercontent.com/90179140/196681806-1cc9bd6b-3fc7-488e-9d2d-f0b25d7e12c4.png">

![image](https://user-images.githubusercontent.com/90179140/196682010-a115e751-8c8a-4bda-b7d4-4b7b89e7a3af.png)

**Comment by wklken** [comment]
看着数据没更新成功

**Comment by wklken** [comment]
@yuri0528 前端提交的数据不是表格内容, 而是原来的数据
