### ISSUE TITLE
用户密码过期时，希望能够自助修改密码

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-user#758]
**需求背景**
当前在管理用户信息时，可以为用户密码配置有效期。当密码到期且用户错过了密码过期的提醒邮件后，只能联系管理协助重置。现在希望能够支持用户自助修改过期的密码。

**需求描述**
当用户使用过期的密码（仅限上一个过期的，以往过期的会提示密码错误）登陆时，登陆页提交后会自动弹出以下弹窗提示用户修改密码。
<img width="959" alt="image" src="https://user-images.githubusercontent.com/110165979/197736414-a9ee29f5-e833-4784-9fdc-e33970fcdcde.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/110165979/198924541-cb720c62-e2d6-4579-ab61-3b8cb1760b76.png">
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/110165979/198924570-6d53cfbf-57f5-4f33-b002-effe9bd4ef37.png">

**Comment by neronkl** [comment]
1. 版本2.5.2已满足，登录校验密码过期自动跳转，重置密码页面
2. 版本2.5.2 已满足 通过profile_token获取密码配置，进行密码格式校验（前端需确认效果）
3. 后端未满足：新密码是否和前三次的密码重复
@Canway-shiisa

**Comment by wklken** [comment]
目前是做不到检测历史密码的, 因为没有存

**Comment by neronkl** [comment]
我记得是满足密码的修改记录，通用函数check_former_passwords中有校验新密码是否和前三次密码重复的逻辑

**Comment by wklken** [comment]
看了下 check_former_passwords 应该可以用, 可以看下怎么改动来支持

**Comment by neronkl** [comment]
https://github.com/TencentBlueKing/bk-user/blob/9e4686e44ebdfc3ba9df782c1d00950851e9730b/src/api/bkuser_core/api/web/password/views.py#L99

 validate_password  <- check_former_passwords 
已满足

**Comment by neronkl** [comment]
https://github.com/TencentBlueKing/bk-user/blob/9e4686e44ebdfc3ba9df782c1d00950851e9730b/src/api/bkuser_core/api/web/password/views.py#L99

 validate_password  <- check_former_passwords 
功能已满足
