### ISSUE TITLE
itsm触发器触发邮件通知以后收到的邮件变量获取不到值

### ISSUE THREAD

**Issue by zm007520** [TencentBlueKing/bk-user#765]
触发器这里插入的变量，在流程里面触发告警以后，收到的邮件变量获取不到值，如下图
![image](https://user-images.githubusercontent.com/10609456/197991006-f449cf62-0948-4e63-9733-4cc09cc4622d.png)

![image](https://user-images.githubusercontent.com/10609456/197991289-1c17ae52-e061-4928-bdd6-ed1c8df383a2.png)

**Comment by wklken** [comment]
非用户管理/权限中心问题, 请到相应的项目issue @zm007520
