### ISSUE TITLE
用户登陆会话过期时，希望能够弹出预计xx秒后登出提示

### ISSUE THREAD

**Issue by Zoeyzhou11** [TencentBlueKing/bk-user#768]
示例：
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/110165979/198463384-df44cbf0-4152-455f-8df9-15ebbb223878.png">

**Comment by wklken** [comment]
- 目前登录态认证接口并没有返回 过期时间
- 登录还存在一个逻辑: 用户两个小时无操作自动过期(相当于另一个隐形的过期时间, 动态的)

**Comment by wklken** [comment]
每个产品可以自己读取 cookie中 bk_token的 ttl, 计算并弹出对应的交互

注意: 这个逻辑无法感知到`连续两个小时无操作`的行为;

**Comment by pagezz-canway** [comment]
每个产品可以自己读取 cookie中 bk_token的 ttl, 计算并弹出对应的交互
—— SaaS可以按照该方案实现
