### ISSUE TITLE
组织架构-用户搜索功能异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#776]
**重现方法**
进入用户管理 -> 点击组织架构 -> 点击进入其中一个目录 -> 进行用户搜索
![image](https://user-images.githubusercontent.com/90179140/199655467-5c1da117-f3ce-4321-9a5d-b69d1822ff06.png)

**预期行为**
- ![image](https://user-images.githubusercontent.com/90179140/199655512-e4cd9500-e4b9-4cff-a57c-8fb9527a4158.png)

- 接口调用情况： 
![image](https://user-images.githubusercontent.com/90179140/199655792-6e21349b-14b9-4c7d-918e-92df16a936c4.png)

**异常现象**
输入搜索内容后回车：
- ![image](https://user-images.githubusercontent.com/90179140/199655574-e739d9ab-227d-4bc5-a576-3d013c7d443a.png)

- 接口调用情况【异常情况下前端没有触发接口调用】：
![image](https://user-images.githubusercontent.com/90179140/199655842-4a595cca-36a1-41ae-befc-39affe342006.png)

**版本**
- 用户管理2.5.0-beta1
- github开源版本

**Comment by wklken** [comment]
已知问题, 升级到 2.5.0-beta3;

已经不会存在`/api/v2`, 所有前端触发的请求路径都是`/api/v1/web/`开头

**Comment by wklken** [comment]
升级验证如果没问题再关闭

**Comment by wklken** [comment]
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/2002216/200239279-fa935848-a534-4811-a746-3f5aefa20927.png">

**Comment by wklken** [comment]
先close, 有问题再开

**Comment by Canway-shiisa** [comment]
已验证

> 升级验证如果没问题再关闭
