### ISSUE TITLE
bk-user登录后shortcuts/departments/tops接口返回404

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-user#782]
使用源码编译部署，版本号：[v2.5.0-beta.3](https://github.com/TencentBlueKing/bk-user/releases/tag/v2.5.0-beta.3)
登录之后进入用户管理目录返回404
WARNING [2022-11-11 15:40:26,610] "GET /api/v2/shortcuts/departments/tops/ HTTP/1.1" 404 6853
![2](https://user-images.githubusercontent.com/2127677/201289725-d2cda22a-5d4f-4039-9cdb-d4785a831e93.jpg)
![1](https://user-images.githubusercontent.com/2127677/201289803-bf437c71-f18d-4916-b413-74b5369f2511.jpg)
点击各个页面均返回404，bk-user目前只能实现登录验证，用户管理界面无法使用

请教下是因为源码不全，还是需要哪个模块进行依赖，源码里没有找到相关接口的源码
shortcuts/departments/tops

**Comment by wklken** [comment]
v2.5.0 SaaS 及后台, 已经整体去掉了`/api/v2`接口, 前端发起请求都是`/api/v1/web/`

-------

需要确认是不是 SaaS 没切? SaaS 及 API 必须使用同一个分支

**Comment by gushedaoren** [comment]
![图片](https://user-images.githubusercontent.com/2127677/201310231-8a9d9d80-c12b-4ed7-8026-5373eaa0704e.png)
正解答案：
.env文件里加入默认版本号

# 请求 ESB API 默认版本号
DEFAULT_BK_API_VER = "v2"
