### ISSUE TITLE
修改代码后如何打包成saas包？

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-user#784]
请教下修改代码后如何编译部署，有没有教程？

**Comment by wklken** [comment]
二进制:

目前走的内部流水线交付包, 除了前端需要编译, 都是python源码; 

部分内部私有仓库没有整合到github(配置文件), 未来会全部放进来; 

理论上解开官方下到的包, 替换源码重新压缩就行;
---

容器化打镜像可以参考dockerfile: https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/Dockerfile

**Comment by gushedaoren** [comment]
![image](https://user-images.githubusercontent.com/2127677/202368340-b49e7e51-b071-43e9-b7a3-b45b490ffd43.png)
请教下官方包里src文件是一个二进制文件，请教下如何替换源码？ @wklken

**Comment by wklken** [comment]
这个看着是部署套件统一做了目录加密, 部署侧是看不到源码的;(也做不了替换)

可以到蓝鲸官网问答社区咨询
