### ISSUE TITLE
pages目录执行npm run dev 大量的404

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-user#791]
源码版本v2.4.2
在pages目录下运行npm run dev报404，api/v2 全部找不到

![image](https://user-images.githubusercontent.com/2127677/201881679-f3d0b2e6-5096-40d2-9241-2baeea1c07ed.png)

index-dev.html配置如下：
![image](https://user-images.githubusercontent.com/2127677/201881905-eeb0f35e-709b-466d-9767-d3e6c96ed61a.png)

请教下：
1.如何解决404的问题？
2.pages部署的源码是否在bk_user_manage_V2.4.2-bkofficial.tar.gz里？部署在服务器的哪个目录下？为啥在服务器上找不到相关文件？

**Comment by wklken** [comment]
第一个问题 @yuri0528 有空看下

第二个问题, pages是编译后直接放在 用户管理SaaS 的Smart应用包里 bk_user_manage_V2.4.2.tar.gz (即, 跟 SaaS 代码放一起), 不是单独部署的

**Comment by yuri0528** [comment]
第一个问题，前后端源码版本需保持一致，请确认一下前后端源码版本是否都是 v2.4.2
