### ISSUE TITLE
前端调用saas后端联调跨域问题

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-user#795]
![image](https://user-images.githubusercontent.com/2127677/201894707-fec49768-e6d4-4412-ba8a-7a5c7b9525c8.png)
前端调用后端saas api返回跨域问题，
我在config.js 配置了proxytable依然无效：
![image](https://user-images.githubusercontent.com/2127677/201894918-3479a685-5b4e-4335-ac34-c885b52d5a0e.png)
后端也通过nginx加入了跨域配置依然无效

请教下如何解决saas前后端联调跨域问题

**Comment by wklken** [comment]
1. 使用域名而不是 ip+端口号 (本地配置host)
2. 进入bkuser_shell/config/overlays `cp dev.tmpl dev.py`  https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/overlays/dev.tmpl#L42
3. 进入bkuser_shell/config/common `cp .env-tmpl .env`  https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/common/.env-tmpl
4. 配置 .env 中的 CORS_ORIGIN_WHITELIST/CSRF_COOKIE_DOMAIN
5. pages中  localDevUrl: 'http://域名'
6. 启动 pages和saas

**Comment by gushedaoren** [comment]
> 5\. localDevUrl

请问下pages和saas的域名和端口是否必须要配置成一致才行？我配置了相同的域名但不同的端口号仍存在跨域问题

**Comment by Xouer** [comment]
> > 5. localDevUrl
> 
> 请问下pages和saas的域名和端口是否必须要配置成一致才行？我配置了相同的域名但不同的端口号仍存在跨域问题 要加个nginx把端口配置成一致吗？我现在pages的端口是8009，saas的端口是8090

请问，您解决了吗？解决方式是什么？

**Comment by Xouer** [comment]
> 1. 使用域名而不是 ip+端口号 (本地配置host)
> 2. 进入bkuser_shell/config/overlays `cp dev.tmpl dev.py`  https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/overlays/dev.tmpl#L42
> 3. 进入bkuser_shell/config/common `cp .env-tmpl .env`  https://github.com/TencentBlueKing/bk-user/blob/master/src/saas/bkuser_shell/config/common/.env-tmpl
> 4. 配置 .env 中的 CORS_ORIGIN_WHITELIST/CSRF_COOKIE_DOMAIN
> 5. pages中  localDevUrl: '[http://域名](http://%E5%9F%9F%E5%90%8D)'
> 6. 启动 pages和saas

我遇到了类似的问题，可能比他的错误，还要多，我设置成了您说的方法，没有解决。下面是我描述的问题。
https://github.com/TencentBlueKing/bk-user/issues/1122#issue-1830387357
