### ISSUE TITLE
存在高危漏洞：存储型XSS

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#796]
示例：
编辑用户名：<img src=1 onerror=alert(1) //>
![image](https://user-images.githubusercontent.com/49228807/201895682-89045549-71ea-4b21-9c7b-99dc8ca1e727.png)

触发:
权限中心，人员选择器，输入该用户username，即可触发
![image](https://user-images.githubusercontent.com/49228807/201896648-8cbcf7c0-5860-435f-93a8-916f01421bc4.png)

**Comment by wklken** [comment]
是`全名`

- 页面编辑
- excel 导入
- ldap同步

这类地方需要加下校验(xss处理)

**Comment by wklken** [comment]
先自测

**Comment by wklken** [comment]
#807 
2.5.2统一提测

**Comment by neronkl** [comment]
安全测试仍存在该问题： 测试人员通过抓包修改，仍然存在该问题
@wklken @nannan00 @Canway-shiisa

**Comment by wklken** [comment]
通过别的方式处理了
