### ISSUE TITLE
saas本地运行401认证怎么处理

### ISSUE THREAD

**Issue by gushedaoren** [TencentBlueKing/bk-user#797]
![image](https://user-images.githubusercontent.com/2127677/202075911-3107517d-9f11-4c02-8d51-a6ee0d9656c5.png)
这个401返回后会跳转到登录，登录结束后会继续401然后又跳转登录，反复跳转

有办法处理掉401？或者取消用户认证进行开发吗？

env下面已经配置了DISABLE_IAM=1

**Comment by IMBlues** [comment]
可以确认下 SaaS 和 bk_login 服务是否是同域的，401 的意思就是 SaaS 获取不到 Cookie 里的 bk_token 登陆凭证
