### ISSUE TITLE
增加 actions 在每次 PR/MR 时自动跑单元测试

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-user#8]
当前的阻碍：
- ldap 相关测试需要使用 docker 启动真实的 ldap 服务

两个解决方向：
- actions 中增加 ldap 服务
- 增加 ldap mock 服务

**Comment by IMBlues** [comment]
一些半死不活的类似实现：

- https://github.com/zulip/fakeldap
- https://github.com/psagers/mockldap

代码量很少，考虑直接参考并在仓库中自己维护

**Comment by shabbywu** [comment]
ldap3 也提供了 mock 功能. https://ldap3.readthedocs.io/en/latest/mocking.html

**Comment by IMBlues** [comment]
> ldap3 也提供了 mock 功能. https://ldap3.readthedocs.io/en/latest/mocking.html

看起来 ldap3 更靠谱
