### ISSUE TITLE
对接LDAP时候，为什么总是提示2022-11-18 15:34:14.415665: 同步组织【Users】与用户【zifeng.liu】的关联关系失败, 失败原因: 部门不存在

### ISSUE THREAD

**Issue by wlytwmssjo-li** [TencentBlueKing/bk-user#803]
**用文字描述你遇到的问题**
同步数据遇到：2022-11-18 15:34:14.415665: 同步组织【Users】与用户【zifeng.liu】的关联关系失败, 失败原因: 部门不存在
![image](https://user-images.githubusercontent.com/113082542/202646910-7a1da89e-9eec-46a0-9882-c9928fca1ca2.png)
![image](https://user-images.githubusercontent.com/113082542/202646942-09fc4ff8-207b-42aa-b7b6-e52039ae0916.png)
![image](https://user-images.githubusercontent.com/113082542/202646994-ec34e034-c047-418c-b85b-c476903a3bb4.png)

**Comment by wklken** [comment]
1. 这类问题, 大概率是配置问题, 先自查
参考链接:  https://github.com/TencentBlueKing/bk-user/issues/429  (里面有目前遇到所有问题/有社区论坛官方配置教程/有论坛问答的分享)

2. 如果还有问题, 请到问答社区发帖, 会有助手协助处理 (需要附上完备的问题描述, 做了哪些尝试等等)

**Comment by wklken** [comment]
确认下用户在数据库表是否存在/部门是否存在: 具体参考这里的sql [sql](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1167117436)

**Comment by wlytwmssjo-li** [comment]
em...我没看懂动你让我查的这些在那个位置
