### ISSUE TITLE
部分接口没有做权限限制，如低权限用户可通过直接调用接口，可获取默认目录的配置

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#804]
接口示例：https://xxxx.com/o/bk_user_manage/api/v2/categories/1/settings/namespaces/password/
使用新建用户，进行访问，可直接获取数据

**Comment by wklken** [comment]
已知问题, 使用2.5.1/2.4.3验证是否还存在;

后续报 bug 需要给下对应用户管理版本号

**Comment by wklken** [comment]
2.4.3 这个接口修复的对应行
https://github.com/TencentBlueKing/bk-user/blob/v2.4.3/src/api/bkuser_core/user_settings/views.py#L84

----

2.5.x已经全部重构, 没有对应的api了, 新版api都是`/api/v1/web`, 所有权限控制都通过drf的permission处理

https://github.com/TencentBlueKing/bk-user/blob/v2.5.1/src/api/bkuser_core/bkiam/permissions.py#L253

----

close, 还有问题请重新提issue
