### ISSUE TITLE
【安全】密码试错次数超过设置，自动锁定账户对admin无效

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-user#810]
**用文字描述你遇到的问题**

密码试错次数超过设置，自动锁定账户对admin无效

**重现方法**

1.对默认目录设置密码试错次为3
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/8849151/203013216-0ec18a24-6892-4ec9-86d3-abd28b27df8b.png">

2.登录时使用admin，故意输错密码超过3次，发现一直可以重试，账户未锁定
<img width="504" alt="image" src="https://user-images.githubusercontent.com/8849151/203013314-6904f352-9a83-453e-aa3f-18423ff9727c.png">

**预期行为**

输错密码超过3次，提示密码被锁定，需要X秒后重试

**版本**
- 提供用户管理的具体版本号
2.5.1
- 是否是企业版问题？
是

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wklken** [comment]
- 2.5.x: https://github.com/TencentBlueking/bk-user/blob/master/src/api/bkuser_core/api/login/views.py#L106
- 2.4.x: https://github.com/TencentBlueKing/bk-user/blame/v2.4.3/src/api/bkuser_core/profiles/v2/views.py#L672

这里条件导致admin不会进入到判断
原因需要确认当时为什么超管不检查, 确认后才能改

**Comment by Canway-shiisa** [comment]
追溯不到当时具体的原因，跟blues沟通后判断应该是当时特意留的一个口子，@Xmandon 看下是否清楚

**Comment by wklken** [comment]
可以去掉条件判断后测试一下, 相当于admin登录当成普通用户处理 => 没问题的话推个 PR

记得加一行注释说明原来有这么一个条件现在因为什么原因去掉了
