### ISSUE TITLE
登录审计导出报错

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#812]
对登录日志进行导出，接口报错。

reason字段是一个经过ugettext_lazy后的对象，导致写入报错

**Comment by wklken** [comment]
提bug要提供版本, 报错日志等, 最好用bug report模板

有利于快速确认和解决

-------

**Comment by wklken** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/2002216/203456918-ac1e1380-0847-490f-9249-949a0083cd6d.png">

bug report:
1. 版本
2. 现象描述
3. 如何复现
4. 日志/报错堆栈截图

**Comment by wklken** [comment]
v2.5.2修复
