### ISSUE TITLE
v2.5.1 页面展示没有显示职务

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#820]
**用文字描述你遇到的问题**

在用户管理2.5.1版本，用户的职务字段会有默认值，但是页面没展示的值，查看详细也没有，但是进行编辑时正常

**重现方法**

<img width="836" alt="企业微信截图_16702069543620" src="https://user-images.githubusercontent.com/49228807/205542392-f5f5571a-1d31-4d91-a9e4-aad4c822c953.png">

<img width="827" alt="企业微信截图_16702069676421" src="https://user-images.githubusercontent.com/49228807/205542449-d5a728c3-3201-4df6-8045-adacaceb4b49.png">

**预期行为**

预期的正常行为
正常显示职务字段值

**版本**
- 提供用户管理的具体版本号： 2.5.1
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by Canway-shiisa** [comment]
接口返回正常，疑似前端展示问题
