### ISSUE TITLE
【组织架构】用户信息中的【账号到期时间】填充优化

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/bk-user#834]
**功能需求背景，例如你遇到了什么问题**

当前新增用户属性【账户过期时间】在创建用户时为非必填；希望在创建用户时，能够自动拉取用户目录中设置的【账号有效期】计算到期时间，自动带出在用户属性中，并支持用户编辑

**描述你觉得更好的解决方案**

在创建用户时，能够自动拉取用户目录中设置的【账号有效期】计算到期时间，自动带出在用户属性中，并支持用户编辑
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/8849151/206390090-91d6ba1b-27e2-452f-a1b9-4902ba333239.png">

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/8849151/206390038-88b619ad-5041-4030-809b-96345fd86551.png">

**额外信息**

任何你觉得有助于理解的信息

**Comment by Canway-shiisa** [comment]
更新原型为：
![企业微信截图_16734224451863(1)](https://user-images.githubusercontent.com/90179140/211766844-97a9ade7-a89f-4f16-a378-4637ac69a9f4.png)
=》新建用户 原先的<账号过期字段>变更成<账号有效期>
====================================================
目前：
1.用户表没有类似<密码有效期>一样，在目录配置中存储了一份密码有效期，在用户表中再单独存储一份用户个人密码有效期
2.用户表是存储的 <账号过期时间>，新建用户默认是通过所在目录配置的<账号有效期>及新建用户时间进行<账号过期时间>计算，<账号过期时间>支持编辑

如果按照更新的原型进行修改，需要确认下面几个问题：
1.支持用户编辑<账号有效期>的话，用户表需要新增对应字段，枚举值类比<密码有效期>
2.账号有效期的计算是  【账号创建时间+账号有效期】，类比密码有效期的枚举，账号有效期也是除了永久之外最长时间为365天；由于密码修改会刷新一个密码更新时间=》密码过期时间也随着变更，但是账号创建时间是不会变的，这里计算账号过期时间上可能会有问题？

**Comment by wklken** [comment]
1. 密码有效期暂不处理; 保持现状(即, 保持现在的编辑和展示)
2. 账号有效期
   - 展示: 返回`账号过期时间`(原来的) +  还剩多少天账号过期(=账号过期时间-当前时间), 前端转成多少天展示
   - 编辑: 将`账号过期时间`设置为 用户选择的时间 (此时不用考虑账号创建时间, 不用管账号新建), 注意不允许大于永久的

即, 前端才有账号有效期的概念, 后台还是账号过期时间

**Comment by wklken** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2002216/215420923-bb8dfa20-31b1-4130-9fae-0bccc033024e.png">

**Comment by Shutulee** [comment]
设计稿的逻辑目前看没问题。用户通常来讲不太关注上次选择的相对时间，而更关注目前账号还有多少天剩余可用。

展示：账号剩余天数（过期时间：xxxx-xx-xx）。
编辑：选择有效期（过期时间:xxxx-xx-xx）。过期时间=当前更新时间+有效期。即进行续期。

但假如上次选择的相对时间能被记录，展示上会更友好一些——例如，「账号有效期：剩余12/30天（过期时间xxxx-xx-xx）」。
nice to have，可以评估一下改动量。

**Comment by wklken** [comment]
即:
- 展示：账号剩余 Y 天（过期时间：xxxx-xx-xx）。   Y=过期时间-当前时间 或者 0天(如果是负数); 这里 过期时间 xxxx-xx-xx即账号过期时间
- 编辑：选择有效期（过期时间: xxxx-xx-xx）。     这里 过期时间=当前时间+有效期。
       向后台提交的 账号有效期=用户下拉选择的过期时间 (注意编辑态没有不展示原有的账号过期时间), 如果没有更新表单提交的是原始的账号过期时间(或者没有修改表单不提交这个字段)

-----
记住上次选择的成本会比较高, 本身这个字段是非核心字段暂时不考虑
