### ISSUE TITLE
导入用户报错，请问这是格式还有问题吗

### ISSUE THREAD

**Issue by aa297236041** [TencentBlueKing/bk-user#847]
社区版V7 用户管理 bk-user-1.3.5  bk_user_manage  v2.4.2 
导入用户报错，请问这是格式还有问题吗
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
![image](https://user-images.githubusercontent.com/66426170/207821473-9288fc5f-9727-4c32-82e4-0aa299ddf0cf.png)

**Comment by wklken** [comment]
捞下 SaaS + 后台对应的 报错日志堆栈

**Comment by wklken** [comment]
1. 可以二分法定位是什么数据导致的报错, 先去除异常数据导入
2. 需要捞后台的报错日志才能进一步确认报错点, 修复代码处理相关的异常
