### ISSUE TITLE
2.5.2 登录页面忘记密码没有反应

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#864]
步骤一：paa6环境，进入登录页面，点击忘记密码，显示没有反应。

步骤二：进入登录页面，点击忘记密码，没有反应，输入账户和密码进行登录，跳转密码重置页面。请问这样的操作符合预期吗？？而在输入的账户和密码是正确的才能跳转密码重置页面

![image](https://user-images.githubusercontent.com/2002216/210030005-c8d2a565-7a44-47d2-997f-188950cebd55.png)

------

原因: 二进制版的登录是 bk-PaaS下的登录, 不是bk-user下的, 所以如果有相关的修改, 二进制版的也得同步处理

**Comment by Canway-shiisa** [comment]
这个问题在版本2.5.1也能够复现，我看了下估计是白名单的问题，我们这边的开发同学已经提PR尝试修复，请亮哥帮忙确认下哈
