### ISSUE TITLE
新用户首次登录无法修改初始密码

### ISSUE THREAD

**Issue by Shutulee** [TencentBlueKing/bk-user#873]
**用文字描述你遇到的问题**

原issue：
https://github.com/TencentBlueKing/bk-user/issues/33

目前的逻辑：
新用户首次登录，默认必须修改初始密码

问题点：
1、实现方案没有按照原先设计的产品逻辑。
https://github.com/TencentBlueKing/bk-user/issues/706
2、点击弹出的修改密码提醒后，跳转的不是「修改密码」界面，而仍然是「登录界面」。这就导致新用户的登录行为被完全阻塞，因为首次登录必须进行初始密码修改，而密码修改又无法被完成。
3、多次登录失败被冻结，没有在账户状态中体现出来。

**重现方法**
<img width="948" alt="企业微信截图_6285ed1a-98de-4cf6-b14a-370d62827ec0" src="https://user-images.githubusercontent.com/50794209/211237135-a03f88eb-cd05-4b59-b211-99bb69e7a51d.png">
<img width="633" alt="企业微信截图_52b2c431-2d2d-4565-b0a0-f7d020755675" src="https://user-images.githubusercontent.com/50794209/211237146-bb0155f2-e36d-4b59-9040-0f3a84c99799.png">

**预期行为**
https://github.com/TencentBlueKing/bk-user/issues/706

**版本**
ivp6环境：
http://bkuser.ipv6-dual.bktencent.com/organization#/agent-manager/status
经验证，测试环境也有该问题：
http://paas6.bktencent.com/o/bk_user_manage/organization

**操作系统和浏览器信息**
 - OS: MAC
 - Browser：chrome

**额外信息**
http://paas6.bktencent.com/o/bk_user_manage/organization
测试版本太久没维护？现在无法查看用户信息了。
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/50794209/211237319-750ecd85-bd78-496a-be9a-62193e831f94.png">

**Comment by wklken** [comment]
1、实现方案没有按照原先设计的产品逻辑。
https://github.com/TencentBlueKing/bk-user/issues/706
2、点击弹出的修改密码提醒后，跳转的不是「修改密码」界面，而仍然是「登录界面」。这就导致新用户的登录行为被完全阻塞，因为首次登录必须进行初始密码修改，而密码修改又无法被完成。
3、多次登录失败被冻结，没有在账户状态中体现出来。

-----

1. 最新版本应该是有的, 确定下没有生效的环境的用户管理版本(>=2.5.1)
2. 这个是个bug, 2.5.2 最新包已有 PR 修复
3. 需要确认

**Comment by wklken** [comment]
新用户无法修改密码确认是 2.5.0/2.5.1 引入的bug, 已经在v2.5.2-alpha.4中修复

**Comment by wklken** [comment]
52 已修复

51 账号锁定指的是短时间内不让登录(例如 600 秒), 跟账号冻结是有区别的(冻结是一个长期的状态), 所以密码错误锁定并不会体现在账户状态上

-------

**Comment by wklken** [comment]
2.5.2 最新版已修复, 环境更新到这个版本后可以重新验证相关的问题
