### ISSUE TITLE
页面中同一个用户左侧搜索，以及组织内搜索展示数据不一致

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#888]
**用文字描述你遇到的问题**

页面中同一个用户左侧搜索，以及组织内搜索展示数据不一致

**重现方法**

新建不同的动态用户字段，测试用户补充新字段内容。
左侧搜索测试用户
<img width="926" alt="企业微信截图_16749828179039" src="https://user-images.githubusercontent.com/49228807/215369087-044f5ac8-c0bb-4e99-8689-e13d62f06522.png">

组织内搜索测试用户
<img width="792" alt="企业微信截图_1674982885309" src="https://user-images.githubusercontent.com/49228807/215369093-206441f7-9d26-488f-b54c-d817720d7dec.png">

**预期行为**

两种搜索数据应该一致

**版本**
- v2.5.2/v2.5.1

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wklken** [comment]
规划放 2.5.3

**Comment by yuri0528** [comment]
两个搜索接口返回的数据格式不一致，我调整一下交互逻辑

**Comment by yuri0528** [comment]
api/v1/web/profiles/search/ 这个接口缺少 account_expiration_date 字段，搜索结果也不一致

**Comment by wklken** [comment]
我一会看下, 加上这个字段
