### ISSUE TITLE
[删除回收] 回收策略设置

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#896]
增加配置, 支持配置回收策略

当前需求: 
1. 回收站数据保留天数, 当前只有一个字段, 未来可能会加其他设置, 例如一些开关等, 所以设计上需要同用户字段设置一致
2. 在删除页面交互中需要返回这个配置, 前端展示给用户  `删除数据将会为你保存 x 天` (返回时也应该返回多个, 未来可能有其他设置的字段要返回)

原型：
- 回收策略设置页面 
![回收策略设置](https://user-images.githubusercontent.com/90179140/216911088-bef5acd8-c741-40a0-8ec9-9114503183fe.png)
- 重置回收策略
<img width="507" alt="企业微信截图_ecd90adb-f57a-4721-a9e8-3aadac09d2a8" src="https://user-images.githubusercontent.com/90179140/217135107-b03582fe-f827-4c5e-b316-6c5e970b14d0.png">

**Comment by wklken** [comment]
初始化值多少找产品确认

**Comment by neronkl** [comment]
回收策略归属为全局设置，新增全局设置模块

Global Settings 模型设置

| 字段      | 数据类型 | 释义                  |
| --------- | -------- | --------------------- |
| key       | char     | 配置键                |
| value     | char     | 配置内容              |
| namespace | char     | 命名空间, index=True  |
| choices   | char     | 可选值                |
| enable    | boolean  | 使能状态 defalut=True |
| default   | char     | 默认值                |

回收策略设置

```
key=data_storage_day
value=30
default=30
namespace="recycle_bin"
enable=True
choices=[7, 30, 90, 180, 365]
```

全局配置视图类

```python
class GlobalSettingsListUpdateApi()
	pass
	
url: path(
    "global_settings/namespaces/<str:namespace>/", 
    GlobalSettingsListUpdateApi.as_view
	)

class GlobalSettingUpdateInputSLZ:
	key = serializers.CharField()
    value = serializers.JSONField()
    enabled = serializers.BooleanField(required=False, default=True)

class GlobalSettingOutputSLZ:
	key
	value
	default
	region
	enable
	choices
```

**Comment by Canway-shiisa** [comment]
原型：
![回收策略设置](https://user-images.githubusercontent.com/90179140/216911011-5994daec-7048-46bc-9089-31527e78ba3e.png)

**Comment by neronkl** [comment]
@Canway-shiisa

**Comment by Canway-shiisa** [comment]
> 回收策略归属为全局设置，新增全局设置模块
> 
> Global Settings 模型设置
> 
> 字段	数据类型	释义
> key	char	配置键
> value	char	配置内容
> namespace	char	命名空间, index=True
> choices	char	可选值
> enable	boolean	使能状态 defalut=True
> default	char	默认值
> 回收策略设置
> 
> ```
> key=data_storage_day
> value=30
> default=30
> namespace="recycle_bin"
> enable=True
> choices=[7, 30, 90, 180, 365]
> ```
> 
> 全局配置视图类
> 
> ```python
> class GlobalSettingsListUpdateApi()
> 	pass
> 	
> url: path(
>     "global_settings/namespaces/<str:namespace>/", 
>     GlobalSettingsListUpdateApi.as_view
> 	)
> 
> class GlobalSettingUpdateInputSLZ:
> 	key = serializers.CharField()
>     value = serializers.JSONField()
>     enabled = serializers.BooleanField(required=False, default=True)
> 
> class GlobalSettingOutputSLZ:
> 	key
> 	value
> 	default
> 	region
> 	enable
> 	choices
> ```

建议：可以按照下列这个逻辑来写，比如
回收逻辑模块
1. 设计思路
 - 写清楚是新增模块处理还是复用哪一个模块，假如是新增，可以**写清楚新增在哪**；如：在bkuser_core/api/web新增一个回收策略模块 recycling_strategy
 - 新增哪些View及方法，用于实现什么；如：recycling_strategy模块下新增views.py，定义Recycling_StrategyCreateApi类-POST方法，实现新增回收策略的全局配置（这里可以写成伪代码更直观，文字描述是实现什么即可）
2.涉及接口
 - 这里要写清楚新增了哪些接口或者复用了哪些接口及对应的接口入出参，如：
![image](https://user-images.githubusercontent.com/90179140/216934446-e2ee7698-5e4e-4562-9a66-ae209d0a7f3c.png)

**Comment by neronkl** [comment]
@Canway-shiisa 
设计思路：
      回收策略只是全局配置的其中一个配置项，无需为它单独建立一个模块。后续可能会有更多的配置项，全局配置模块统一进行管理。bkuser_core中增加global_settings模块，bkuser_core/api/web 增加对应视图。

获取对应命名空间的的全局配置项目
请求地址 
api/v1/web/global_settings/namespaces/<str:namespace>/
请求方式：GET
QUERY_PARAMS: 无
RESPONSE：
| 字段      | 数据类型 | 释义     |
| --------- | -------- | -------- |
| key       | char     | 配置键   |
| value     | char     | 配置内容 |
| namespace | char     | 命名空间 |
| choices   | char     | 可选值   |
| enable    | boolean  | 使能状态 |
| default   | char     | 默认值   |

变更配置项的值
请求地址 
api/v1/web/global_settings/namespaces/<str:namespace>/
请求方式：PUT
BODY: 
| 字段      | 数据类型 | 释义     |
| --------- | -------- | -------- |
| key       | char     | 配置键   |
| value     | char     | 配置内容 |
| enable| boolean     | 使能状态 |

RESPONSE：
| 字段      | 数据类型 | 释义     |
| --------- | -------- | -------- |
| key       | char     | 配置键   |
| value     | char     | 配置内容 |
| namespace | char     | 命名空间 |
| choices   | char     | 可选值   |
| enable    | boolean  | 使能状态 |
| default   | char     | 默认值   |

```python
url: path(
    "global_settings/namespaces/<str:namespace>/", 
    GlobalSettingsListUpdateApi.as_view
	)

class GlobalSettingsListUpdateApi()
	def get_queryset(self):
        namespace = self.kwargs["namespace"]
 	# 返回命名空间下的全局变量
    
    def put(self):
    	# 更新输入序列化器，data数据校验
        # 更新值

class GlobalSettingUpdateInputSLZ:
	key = serializers.CharField()
        value = serializers.JSONField()
        enabled = serializers.BooleanField(required=False, default=True)

class GlobalSettingOutputSLZ:
	key
	value
	default
	region
	enable
	choices
```

**Comment by Canway-shiisa** [comment]
> @Canway-shiisa 设计思路： 回收策略只是全局配置的其中一个配置项，无需为它单独建立一个模块。后续可能会有更多的配置项，全局配置模块统一进行管理。bkuser_core中增加global_settings模块，bkuser_core/api/web 增加对应视图。
> 
> 获取对应命名空间的的全局配置项目 请求地址 api/v1/web/global_settings/namespaces/str:namespace/ 请求方式：GET QUERY_PARAMS: 无 RESPONSE：
> 
> 字段	数据类型	释义
> key	char	配置键
> value	char	配置内容
> namespace	char	命名空间
> choices	char	可选值
> enable	boolean	使能状态
> default	char	默认值
> 变更配置项的值 请求地址 api/v1/web/global_settings/namespaces/str:namespace/ 请求方式：PUT BODY:
> 
> 字段	数据类型	释义
> key	char	配置键
> value	char	配置内容
> enable	boolean	使能状态
> RESPONSE：
> 
> 字段	数据类型	释义
> key	char	配置键
> value	char	配置内容
> namespace	char	命名空间
> choices	char	可选值
> enable	boolean	使能状态
> default	char	默认值
> ```python
> url: path(
>     "global_settings/namespaces/<str:namespace>/", 
>     GlobalSettingsListUpdateApi.as_view
> 	)
> 
> class GlobalSettingsListUpdateApi()
> 	def get_queryset(self):
>         namespace = self.kwargs["namespace"]
>  	# 返回命名空间下的全局变量
>     
>     def put(self):
>     	# 更新输入序列化器，data数据校验
>         # 更新值
> 
> class GlobalSettingUpdateInputSLZ:
> 	key = serializers.CharField()
>         value = serializers.JSONField()
>         enabled = serializers.BooleanField(required=False, default=True)
> 
> class GlobalSettingOutputSLZ:
> 	key
> 	value
> 	default
> 	region
> 	enable
> 	choices
> ```

数据库表设计：
1. global_setting表的设计 可以增加id、create_time、update_time、required（是否必填标识）？
2. 表设计中没有 region，但是后面GlobalSettingOutputSLZ中有个region？
3. enabled字段好像没有什么作用？扩展用？那PUT修改配置接口似乎也不需要传递这个字段
4. choices字段使用text合适些？

**Comment by neronkl** [comment]
1. id、create_time、update_time 为基础字段，所以没有写。required字段感觉没必要添加，全局配置配置本身作为配置功能，概念上就是必填。
2. region -> namespace
3. enabled字段是个开关字段，后续关闭某个配置可以通过enabled字段。为后续拓展配置开关进行预留
4. choices 实则为longtext，写错了，orm->JSONFeild
@Canway-shiisa

**Comment by Canway-shiisa** [comment]
@wklken 辛苦亮哥看下， 方案没问题的话可以开始开发 @neronkl

**Comment by wklken** [comment]
上面的需求: 重置只能重置成字段`默认值`(不会记录上一次值)

-----------------

模型:
- id/create_time/update_time
- namespace
- key 
- value
- default
- choices
- region 需要, 是namespace下的细化, 用于前端展示分区
- enabled  注意是`enabled`

其他:
- 唯一: namespace + key (不需要其他index了)

------------------

1. 模型放到 bkuser_core/user_settings/models.py, 然后显式指定表名: `global_settings`
2. namespace=`recycling_strategy`, key=`retention_days`
3. 更新接口 不需要暴露`enabled`, 只需要`key/value`


------------------

上面伪代码的排版为啥那么奇怪, 重新排版下?

**Comment by neronkl** [comment]
回收策略:保留时间设置

```
key=retention_days
value=30
default=30
namespace=recycling_strategy
enable=True
choices=[7, 30, 90, 180, 365]
region=defalut
```

全局配置视图类

```python
url: path(
    "global_settings/namespaces/<str:namespace>/", 
    GlobalSettingsListUpdateApi.as_view
)

class GlobalSettingsListUpdateApi()
       def get_queryset(self):
    	   namespace = self.kwargs["namespace"]
    	   # 返回命名空间下的全局变量
    	    .....
    
       def put(self):
    	   # 更新输入序列化器，data数据校验
           # 更新值

class GlobalSettingUpdateInputSLZ:
	key = serializers.CharField()
        value = serializers.JSONField()

class GlobalSettingOutputSLZ:
	key
	value
	default
	region
	enable
        namespace
	choices

```

**Comment by wklken** [comment]
enabled

**Comment by wklken** [comment]
@nannan00 review下方案, 有问题尽早评论

**Comment by nannan00** [comment]
目前看到的只有回收时间的配置，是否还得考虑一下每个回收项可能是独立配置，比如用户回收时间与组织架构回收时间是不一样的？可以先不做，但是只要考虑后续是否能平缓扩展即可

**Comment by neronkl** [comment]
> 目前看到的只有回收时间的配置，是否还得考虑一下每个回收项可能是独立配置，比如用户回收时间与组织架构回收时间是不一样的？可以先不做，但是只要考虑后续是否能平缓扩展即可

这个可以通过region字段进行区分配置（用户，组织，目录），当前设计region=defalut，为回收策略通用项。后续需要的话，可进行单独region=(用户/组织/目录),key=retention_days
