### ISSUE TITLE
【删除回收】目录删除

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#901]
## 目录删除

- 展示列表
    - 存量已删除的目录怎么出现在列表中? 
- 永久删除
    - 生命周期: normal -> inactive -> deleted -> 物理删除
    - 删除需要清理所有关联数据: 所有category_id为外键的数据
    - 需要考虑事务, 以及目录下十万级部门及用户删除的场景
- 因为category在所有地方都会先校验, 所以理论上删除只需要改category本身的状态就行, 不需要联动操作改部门/用户的状态
- 还原
    - 判断有没有冲突即可, 没有冲突直接状态操作改回去(检测冲突)
    - 新建目录的时候也会检测冲突, 冲突提示跟哪个冲突, 用户可以到回收站物理删除=》产品确认：用户正常新建的目录，和回收站内的软删除目录不应该产生同名冲突（部门用户也同理）。

## 相关原型
- 目录删除
![目录删除](https://user-images.githubusercontent.com/90179140/217140086-22a015f1-6be6-4d40-bab0-45e832ee0a6a.png)
- 停用目录
![目录_停用目录](https://user-images.githubusercontent.com/90179140/217140130-450e3997-3ace-4f31-9bb5-a76d56d81d99.png)
- 目录配置未完成
![目录_未完成](https://user-images.githubusercontent.com/90179140/217140177-8caddfc5-0f31-41d4-a793-14f1aae5d2c6.png)
- 目录还原
![回收箱_目录还原预览](https://user-images.githubusercontent.com/90179140/217140250-24ed44f8-8067-42a1-89ef-09aa8acce67b.png)
- 目录永久删除
![回收箱_最近删除目录](https://user-images.githubusercontent.com/90179140/217140290-d635d13a-4c66-49a8-9b1d-08cd89e802a0.png)

**Comment by neronkl** [comment]
当前目录删除的时，会对其下的人员（enable=0，status=delete）或者部门（enable=False）， 定时任务删除。还原时候后，需将人员或者部门进行同步还原？定时同步任务呢？只是单单将目录给还原？@wklken

**Comment by wklken** [comment]
当前目录删除是软删除, 只动了目录的状态, 不会动人员和部门
- 软删除 -> 硬删除, 删目录的所有数据, 人员+部门, 只要目录下都删, 不考虑状态
- 软删除 -> 还原, 目录状态恢复回去就行

**Comment by wklken** [comment]
还原需要注意冲突检测

--------

issue 描述写得比较全, 多仔细读几遍

**Comment by wklken** [comment]
方案设计, 需要画状态流转图, 一个目录的生命周期, 状态怎么流转的, 以及每个状态对应 model 中的属性值是什么

**Comment by neronkl** [comment]
> 当前目录删除是软删除, 只动了目录的状态, 不会动人员和部门
> 
> * 软删除 -> 硬删除, 删目录的所有数据, 人员+部门, 只要目录下都删, 不考虑状态
> * 软删除 -> 还原, 目录状态恢复回去就行

https://github.com/TencentBlueKing/bk-user/blob/40ee56ed90d47b214274819394aa21ec7459b970/src/api/bkuser_core/api/web/category/views.py#L296
https://github.com/TencentBlueKing/bk-user/blob/10d0c5b45706200b5918ae47c5653d6f911a0b00/src/api/bkuser_core/categories/models.py#L70
https://github.com/TencentBlueKing/bk-user/blob/10d0c5b45706200b5918ae47c5653d6f911a0b00/src/api/bkuser_core/categories/models.py#L75

这两源码指向，表示目录软删除，会对相应资源做操作。
后续方案通过，进行开发的时，进行注释？
@wklken

**Comment by wklken** [comment]
注释掉 `category.delete()`整个方法, 需要重新实现相关的逻辑(需要参考注释掉代码内的逻辑)

1. 保护默认用户目录不被删除
2. Profile/Department/Settings 不动
    - 需要确认此时登录用户登录时有没有先检查 category状态(软删除目录下的用户不能登录)
3. 定时任务能否临时停掉 -> 硬删除才删除, 还原的话启用
4. category 本身的属性 enabled / status / update_time 需更新
    - 需要确认category等生命周期流转, status是否加 DELETED 状态等

然后, 还原函数的逻辑是 `冲突检测逻辑 + 上面 2/3/4 相反的逻辑`

**Comment by neronkl** [comment]
![image](https://user-images.githubusercontent.com/49228807/221737640-6e66be57-f2e8-4a67-bb07-4576e201a6ab.png)

1. 新增目录状态Delete
```
class CategoryStatus(AutoLowerEnum):
    ....
    DELETE = auto()
    ....
```
3. 数据迁移:新增迁移文件，存量已删除目录(status=INACTIVE and enable=False) 的数据记录 在回收站新增相应的映射记录，同时status=INACTIVE, enable=False => status=DELETE, enable=False

4. 回收站新增字段extra_info:保存对象的额外信息

5. 重写ProfileCategory.delete方法 => soft_delete
```
def soft_delete(self):
    1.保护默认用户目录不被删除
    2.删除周期任务（此为硬删除，无法复原）：
      extra_info 周期任务记录做额外信息放入该目录的回收站映射记录中(extra_info)
    3. 不动profile，department，settings
    3.变更目录状态enabled=0， status=delete， update_time
```

6. 目录删除接口增加校验，停用后才可进行删除
```
def delete(self, request, *args, **kwargs):
        """删除用户目录"""
        ....
		
        # 增加目录状态校验：停用后，才可删除
        
        # 依赖 model 的 delete 方法, 执行软删除
        instance.soft_delete()
        ....
        # 审计日志接入
        # 回收站数据新增
        recycle_map_generate(....)
        return Response(status=status.HTTP_200_OK)
```

接口设计

2.1 功能说明：目录还原预先检查

URL: "api/v1/web/recycle_bin/batch_check/category/"

Method: POST

body

| 字段            | 数据 | 释义               |
| --------------- | ---- | ------------------ |
| object_ids_list | list | 目录映射关系id列表 |

response

| 字段         | 数据 | 释义     |
| ------------ | ---- | -------- |
| category| char | 目录名称 |
| check_result | bool | 检测结果 |
| message      | char | 检测信息 |



2.2 功能说明：目录还原

URL: "api/v1/web/recycle_bin/batch_revert/category/"

Method: POST

body

| 字段            | 数据 | 释义               |
| --------------- | ---- | ------------------ |
| object_ids_list | list | 目录映射关系id列表 |

response

| 字段  | 数据 | 释义     |
| ----- | ---- | -------- |
| count | int  | 还原个数 |

2.3 功能说明：批量目录对象硬删除

URL: "api/v1/web/recycling_bin/batch_hard_delete/category/"

Method: POST

body

| 字段            | 数据 | 释义               |
| --------------- | ---- | ------------------ |
| object_ids_list | list | 目录映射关系id列表 |

response:

```python
# 目录还原预先检查
url：path("recycle_bin/batch_revert_check/category/")
class CategoryBatchRevertInputSLZ():
    object_ids_list = serializers.ListFeild()
    
class CategoryBatchRevertCheckOutputSLZ():
    display_name = CharField()
    result = BoolField
    message = CharField
    
class RecycleBinBatchCategoryRevertCheckApi()
    def post():
        # request.data slz校验 CategoryBatchRevertInputSLZs
        # object_list 下的目录进行冲突校验
        	# 重名冲突
            # 域名重复冲突
        # 返回冲突校验结果
        return CategoryBatchRevertCheckOutputSLZ.data

# 检查通过的目录才可调用
url：path("recycle_bin/batch_revert/category/")
class CategoryBatchRevertCountOutputSLZ():
    counts = IntegerFiled()
class RecycleBinBatchCategoryRevertApi()
    def post():
        # request.data slz校验 CategoryBatchRevertInputSLZ
        object_type_instance = object_type.object.filter(...).value_list(....)
        # 变更状态
        return CategoryBatchRevertCountOutputSLZ.data
    
        
# 对象硬删除
url: path("recycling_bin/hard_delete/category/<int:id>/")
class RecycleBinCategoryHardDelete()
	
    def delete():
        # 获取对应数据的模型对象
        instance = self.get_object()
        # 数据关联资源删除
        # 进行硬删除，添加审计日志
        return
   
```

**Comment by neronkl** [comment]
@Canway-shiisa

**Comment by Canway-shiisa** [comment]
> > 4. 新增字段extra_info:保存对象的额外信息
> 
> 关于周期任务PeriodicTask模型有enable字段，enable=0使周期任务无效化，无需进行额外存储 目录删除接口=>目录删除
> 
> https://github.com/TencentBlueKing/bk-user/blob/9f2a62f9ec62fb1a5615c01bacfe3d8e102f3dbd/src/api/bkuser_core/api/web/category/views.py#L289
> 
> 1. 确保目录已经停用，
> 2. 增加回收站映射记录
> 
> instance.soft_delete => instance.delete

直接在原始方案上调整一下哩，方案呈现最终修改的结果就可以

**Comment by nannan00** [comment]
> ![image](https://user-images.githubusercontent.com/49228807/221737640-6e66be57-f2e8-4a67-bb07-4576e201a6ab.png)
> 
> 1. 新增目录状态Delete
> 
> ```
> class CategoryStatus(AutoLowerEnum):
>     ....
>     DELETE = auto()
>     ....
> ```
> 
> 3. 数据迁移:新增迁移文件，存量已删除目录(status=INACTIVE and enable=False) 的数据记录 在回收站新增相应的映射记录，同时status=INACTIVE, enable=False => status=DELETE, enable=False
> 4. 重写ProfileCategory.delete方法
> 
> ```
> def delete(self):
>     1. 保护默认用户目录不被删除
>     2. 删除周期任务（PeriodicTask=>enabled=0）：
>     3. 不动profile，department，settings
>     4 .变更目录状态enabled=0， status=delete， update_time
> ```
> 
> 6. 目录删除接口增加校验，停用后才可进行删除
> 
> ```
> def delete(self, request, *args, **kwargs):
>         """删除用户目录"""
>         ....
> 		
>         # 增加目录状态校验：停用后，才可删除
>         
>         # 依赖 model 的 delete 方法, 执行软删除
>         instance.delete()
>         ....
>         # 审计日志接入
>         # 回收站数据新增
>         recycle_map_generate(....)
>         return Response(status=status.HTTP_200_OK)
> ```
> 
> 接口设计
> 
> 2.1 功能说明：目录还原预先检查
> 
> URL: "api/v1/web/recycle_bin/batch_check/category/"
> 
> Method: POST
> 
> body
> 
> 字段	数据	释义
> object_ids	list	目录映射关系id列表
> response
> 
> 字段	数据	释义
> category	json	目录基础信息
> check_status	bool	检测结果
> message	char	检测信息
> 2.2 功能说明：目录还原
> 
> URL: "api/v1/web/recycle_bin/batch_revert/category/"
> 
> Method: POST
> 
> body
> 
> 字段	数据	释义
> object_ids	list	目录映射关系id列表
> response
> 
> 字段	数据	释义
> category	json	目录基础信息
> 2.3 功能说明：批量目录对象硬删除
> 
> URL: "api/v1/web/recycling_bin/batch_hard_delete/category/"
> 
> Method: POST
> 
> body
> 
> 字段	数据	释义
> object_ids	list	目录映射关系id列表
> response:
> 
> ```python
> # 目录还原预先检查
> url：path("recycle_bin/batch_revert_check/category/")
> class CategoryBatchRevertInputSLZ():
>     object_ids_list = serializers.ListFeild()
>     
> class CategoryBatchRevertCheckOutputSLZ():
>     display_name = CharField()
>     result = BoolField
>     message = CharField
>     
> class RecycleBinBatchCategoryRevertCheckApi()
>     def post():
>         # request.data slz校验 CategoryBatchRevertInputSLZs
>         # object_list 下的目录进行冲突校验
>         	# 重名冲突
>             # 域名重复冲突
>         # 返回冲突校验结果
>         return CategoryBatchRevertCheckOutputSLZ.data
> 
> # 检查通过的目录才可调用
> url：path("recycle_bin/batch_revert/category/")
> class CategoryBatchRevertCountOutputSLZ():
>     counts = IntegerFiled()
> class RecycleBinBatchCategoryRevertApi()
>     def post():
>         # request.data slz校验 CategoryBatchRevertInputSLZ
>         object_type_instance = object_type.object.filter(...).value_list(....)
>         # 变更状态
>         return CategoryBatchRevertCountOutputSLZ.data
>     
>         
> # 对象硬删除
> url: path("recycling_bin/hard_delete/category/<int:id>/")
> class RecycleBinCategoryHardDelete()
> 	
>     def delete():
>         # 获取对应数据的模型对象
>         instance = self.get_object()
>         # 数据关联资源删除
>         # 进行硬删除，添加审计日志
>         return
>    
> ```

1. 目录删除后，其关联的用户需要禁止登录，需要check是否判断category

接口设计：
1. 目录还原预先检查，response不需要返回category基本信息，应该是每个category_id和其对应的check后的结果即可

2. 目录还原成功后，不需要返回category基本信息


3. url尽可能的使用restful规范命名，删除应该用DELETE，而且url不需要出现batch_这类的
可以是 `/api/v1/web/recycle_bin/categories/check`

**Comment by neronkl** [comment]
已在原方案上修改：
1. 异常状态目录下的用户，限制登录
2. 目录还原预检查接口返回：category_id, category_display_name, check_status
3. 接口路由变更
    目录预先检查接口：/api/v1/web/recycle_bin/categories/check/
    目录还原接口：/api/v1/web/recycle_bin/categories/revert/
    目录硬删除：/api/v1/web/recycle_bin/<object_type:str >/<int:id >/

**Comment by nannan00** [comment]
> 

第二点，为什么需要返回 category_display_name，一个check接口，实现check本身功能即可，无需做其他额外事情

**Comment by neronkl** [comment]
> > 
> 
> 第二点，为什么需要返回 category_display_name，一个check接口，实现check本身功能即可，无需做其他额外事情

issue设计稿中，检查结果页面有个目录名的字段。前端交互过程可直接获取的话，去掉该字段。
问题一：当前目录创建，目录名称会在逻辑上进行唯一验证，是否去掉（回收站意义：可重复创建）？
问题二：时间差。某个目录通过了检查，未进行还原，刚好一个同名目录被创建了。还原需二次检查？

**Comment by nannan00** [comment]
> 

1. 不能去除，重复了的话，用户可以先删除再创建，之前没有回收站，导致软删除后无法再创建，现在有回收站支持硬删除了，不存在这个问题

2. 这个是必须的，校验通过是一个接口，执行还原是另外一个接口，接口是无状态的，执行还原前必须做检查的，由于一般情况下都是管理员再操作，所以这里暂时可以不需要这么严格，即不需要使用分布式锁等复杂方式来避免并发问题

**Comment by nannan00** [comment]
> > > 
> > 
> > 
> > 第二点，为什么需要返回 category_display_name，一个check接口，实现check本身功能即可，无需做其他额外事情
> 
> issue设计稿中，检查结果页面有个目录名的字段。前端交互过程可直接获取的话，去掉该字段。 问题一：当前目录创建，目录名称会在逻辑上进行唯一验证，是否去掉（回收站意义：可重复创建）？ 问题二：时间差。某个目录通过了检查，未进行还原，刚好一个同名目录被创建了。还原需二次检查？

1. 不能去除，重复了的话，用户可以先删除再创建，之前没有回收站，导致软删除后无法再创建，现在有回收站支持硬删除了，不存在这个问题

2. 这个是必须的，校验通过是一个接口，执行还原是另外一个接口，接口是无状态的，执行还原前必须做检查的，由于一般情况下都是管理员再操作，所以这里暂时可以不需要这么严格，即不需要使用分布式锁等复杂方式来避免并发问题

**Comment by Canway-shiisa** [comment]
产品确认细节：
1. 目录还原校验的是登陆域，非AD连接域
2. 目录永久删除是异步处理，这块的删除详情产品侧会出一个新页面统一展示删除和还原的结果

**Comment by neronkl** [comment]
当前目录的domain字段数据库层面上是唯一的，逻辑层面也做了校验，已经是无法创建相同登录域的目录。
@nannan00

**Comment by neronkl** [comment]
https://github.com/TencentBlueKing/bk-user/issues/960
