### ISSUE TITLE
[组织架构目录合并] 下掉接口

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#907]
#904  目录列表页合并到 home/tree  (所以需要看下目录列表页面上的接口有没有用?)
- /api/v1/web/categories/

**Comment by yuri0528** [comment]
/api/v1/web/categories/

**Comment by yuri0528** [comment]
/api/v1/web/categories/

**Comment by wklken** [comment]
是用到`POST /api/v1/web/categories`, 但是可以下掉 `GET /api/v1/web/categories`? 

> /api/v1/web/categories/ ![image](https://user-images.githubusercontent.com/72436066/226270166-4f78ef4f-d7b5-45b7-960f-313f264aef97.png)
> 
> 接口在新增用户的时候有用到

**Comment by yuri0528** [comment]
进入组织架构页面的时候需要 GET /api/v1/web/categories 拿到展示的信息，extra_info 字段跳转申请权限
![企业微信截图_16793022578902](https://user-images.githubusercontent.com/72436066/226290906-5b42cd0b-cb53-4216-a2fd-e434d31da835.png)
