### ISSUE TITLE
【删除回收】回收站展示

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#908]
## 回收站功能

- 展示列表
    - 已经删除后被放入回收站的数据需要进行展示：包括删除的目录、删除的用户、删除的组织
    - 搜索框过滤展示

## 相关原型：
- 最近删除目录：
![回收箱_最近删除目录](https://user-images.githubusercontent.com/90179140/217138948-2ec98bcd-92f5-43a2-916a-c0370bc7350e.png)
- 最近删除用户：
![回收箱_最近删除用户](https://user-images.githubusercontent.com/90179140/217139024-2e305601-df72-4149-9d14-3c4998df7672.png)
- 最近删除组织：
![回收箱_最近删除组织](https://user-images.githubusercontent.com/90179140/217139023-3f678e1f-918b-46a9-8d7f-66853746b392.png)

**Comment by neronkl** [comment]
1.设计思路
回收站为一个单独功能，新建一个模块。目录（category），组织（department），人员（profile）保留原有的删除的基础上，增加映射关系作为回收站的数据内容。在web模块建立其视图模块

Recycling Bin 模型设置

| 字段          | 数据类型 | 释义                                                |
| ------------- | -------- | --------------------------------------------------- |
| object_type   | char     | 删除对象类型【category，department，profile】       |
| object_id     | int      | 所删除对象id                                        |
| object_status | char     | 数据状态（STAGING/DELETED/REVERT）[暂存，硬删除，被还原] |
| enabled       | bool     | 使能状态                                            |
| operator      | char     | 操作人                                              |

2.接口设计

功能说明：回收站数据展示

URL: "api/v1/web/recycling_bin/<str:object_type >/"

Method: GET

Params: 

| 字段        | 数据 | 字段值选择                  | 释义     |
| ----------- | ---- | --------------------------- | -------- |
| object_type | char | category/department/profile | 对象类型 |

Response：

**object_type=category**

| 字段              | 数据 | 释义     |
| ----------------- | ---- | -------- |
| display_name      | char | 目录名称 |
| domain            | char | 域名     |
| type              | char | 目录类型 |
| department_counts | int  | 部门数   |
| profile_counts    | int  | 人员数   |
| operator          | char | 操作人   |
| update_time       | time | 更新时间 |

**object_type=profile**

| 字段              | 数据 | 释义         |
| ----------------- | ---- | ------------ |
| display_name      | char | 全名         |
| username          | char | 用户名       |
| category_type     | char | 所属目录类型 |
| department_relate | int  | 所属部门     |
| operator          | char | 操作人       |
| update_time       | time | 更新时间     |

**object_type=department**

| 字段                  | 数据 | 释义         |
| --------------------- | ---- | ------------ |
| display_name          | char | 全名         |
| category_type         | char | 所属目录类型 |
| parent_department     | char | 父组织       |
| sub_department_counts | int  | 子部门       |
| profile_count         | int  | 用户数       |
| operator              | char | 操作人       |
| update_time           | time | 更新时间     |

功能说明：回收站搜索数据展示

URL: "api/v1/web/recycling_bin/search/<str:object_type >/"

Method: GET

Params: 

| 字段        | 数据 | 字段值选择                  | 释义     |
| ----------- | ---- | --------------------------- | -------- |
| object_type | char | category/department/profile | 对象类型 |

query_parmas:

**object_type=categoty**

| 字段         | 数据 | 释义   |
| ------------ | ---- | ------ |
| dispaly_name | char | 目录名 |
| domian       | char | 登录于 |

**object_type=department**

| 字段 | 数据 | 释义     |
| ---- | ---- | -------- |
| name | char | 部门名称 |

**object_type=profile**

| 字段         | 数据 | 释义   |
| ------------ | ---- | ------ |
| dispaly_name | char | 全名   |
| username     | char | 用户名 |

Response：

同上



回收站视图

```python
      
_output_serializer_map = {
    "category": CategoryOutputSerializer,
    "department": DepartmentOutputSerializer,
    "profile": ProfileOutputSerializer,
} 

_input_serializer_map = {
    "category": CategorySearchSerializer,
    "department": DepartmentSearchSerializer,
    "profile": ProfileSearchSerializer,
}


url: path("recycling_bin/<str:object_type>/")
class RecyclingBinListApi(generics.ListAPIView)
	def list():
        output_slz = _output_serializer_map["object_type"]
        pass
    
url: path("recycling_bin/search/<str:object_type>/")
class RecyclingBinSearchListApi(generics.ListAPIView)
	def list():
        input_slz = _input_serializer_map["object_type"]
        output_slz = _output_serializer_map["object_type"]
        pass
    

    
```

**Comment by neronkl** [comment]
@Canway-shiisa

**Comment by Canway-shiisa** [comment]
## 数据模型设计：
1. 回收站命名 =》recycle_bin？
2. object_status 字段没有存在的必要？放进回收站的数据就是暂存的数据，还原或永久删除的时候均可以将数据从数据表中删掉，只要审计记录完整即可
3. enabled字段的作用是？
4. 展示接口 应该还有返回一个`过期时间`？
5. 最近删除用户和最近删除组织的接口返回的是`所属目录`，不是`目录类型`
6. 这里统一成一个接口似乎不太合适，可以将共用的数据抽象在一个serializer让三个接口的序列化器分别继承？

**Comment by neronkl** [comment]
1. recycling_bin = > recycle_bin
2. object_status, enabled 两个字段表示映射关系的有效性，限制同一对象还原和软删除状态来回切换，重复生成删除相同的数据，使用这两字段进行标识会更合理。定时任务中进行清理删除状态的映射关系。
3. 响应增加字段：过期时间 => expired_time（或者前端可否计算？）
4. profile，department 的 output_slz中的目录类型 => 所属目录 category_name
5. 这里统一为一个接口），根因是该接口对回收站模型数据展示，只是根据object_type的不同，input_slz和output_slz进行变换（搜索接口亦如此）。
@Canway-shiisa

**Comment by Canway-shiisa** [comment]
1. 这里即使 用status来对回收站数据进行标识，status似乎只需要两种，一个是暂存态，一个是还原态，永久删除的话 数据都从目录表、部门表和用户表中硬删除了，在回收站中也没有存储的必要？
2. enabled的作用还是不是很明确，即使是定时任务 执行的是对回收站的数据进行硬删除，这个字段似乎也没啥作用？
3. 过期时间前后端都可以计算，后台加一个属性计算，前端计算的话 需要调用多一个过期策略的接口获取`数据保留天数`
4. 所属目录的命名感觉可以优化一下，看看from_category合适不？

**Comment by Canway-shiisa** [comment]
1. 这里即使 用status来对回收站数据进行标识，status似乎只需要两种，一个是暂存态，一个是还原态，永久删除的话 数据都从目录表、部门表和用户表中硬删除了，在回收站中也没有存储的必要？
2. enabled的作用还是不是很明确，即使是定时任务 执行的是对回收站的数据进行硬删除，这个字段似乎也没啥作用？
3. 过期时间前后端都可以计算，后台加一个属性计算，前端计算的话 需要调用多一个过期策略的接口获取`数据保留天数`
4. 所属目录的命名感觉可以优化一下，看看from_category合适不？

**Comment by neronkl** [comment]
1. 去掉enabled字段，保留status的两种状态，手动硬删除以及定时硬删除 => 物理删除映射关系
2. 过期时间后台计算进行返回：remain_days
3. category_name => from_category

**Comment by wklken** [comment]
方案讨论完直接 edit 原来的方案 或者整理完重发一个 => 避免其他人得看所有信息流

**Comment by neronkl** [comment]
> 1.设计思路 回收站为一个单独功能，新建一个模块。目录（category），组织（department），人员（profile）保留原有的删除的基础上，增加映射关系作为回收站的数据内容。在web模块建立其视图模块
> 
> Recycle Bin 模型设置
> 
> 字段	数据类型	释义
> object_type	char	删除对象类型【category，department，profile】
> object_id	int	所删除对象id
> status	char	数据状态（STAGING/DELETED/REVERT）[暂存, 还原]
> operator	char	操作人
> 2.接口设计
> 
> 2.1 功能说明：回收站数据展示（目录）
> 
> URL: "api/v1/web/recycling_bin/category/"
> 
> Method: GET
> 
> Response：
> 
> 字段	数据	释义
> display_name	char	目录名称
> domain	char	域名
> category_type	char	目录类型
> department_counts	int	部门数
> profile_counts	int	人员数
> operator	char	操作人
> remain_days	int	离过期剩余天数
> 2.2 功能说明：回收站数据展示（人员）
> 
> URL: "api/v1/web/recycling_bin/profile/"
> 
> Method: GET
> 
> Response：
> 
> 字段	数据	释义
> display_name	char	全名
> username	char	用户名
> from_category	char	所属目录
> department_relate	int	所属部门
> operator	char	操作人
> remain_days	int	离过期剩余天数
> 2.3 功能说明：回收站数据展示（部门）
> 
> URL: "api/v1/web/recycling_bin/department/"
> 
> Method: GET
> 
> Response：
> 
> 字段	数据	释义
> display_name	char	全名
> from_category	char	所属目录
> parent_department	char	父组织
> sub_department_counts	int	子部门
> profile_count	int	用户数
> operator	char	操作人
> remain_days	int	离过期剩余天数
> 2.4功能说明：回收站搜索数据展示（目录）
> 
> URL: "api/v1/web/recycling_bin/search/category/"
> 
> Method: GET
> 
> query_parmas:
> 
> 字段	数据	释义
> dispaly_name	char	目录名
> domian	char	登录域
> Response：
> 
> 同上展示接口
> 
> 2.5功能说明：回收站搜索数据展示（部门）
> 
> URL: "api/v1/web/recycling_bin/search/department/"
> 
> Method: GET
> 
> query_parmas:
> 
> 字段	数据	释义
> name	char	部门名称
> Response：
> 
> 同上展示接口
> 
> 2.5功能说明：回收站搜索数据展示（人员）
> 
> URL: "api/v1/web/recycling_bin/search/profile/"
> 
> Method: GET
> 
> query_parmas:
> 
> 字段	数据	释义
> dispaly_name	char	全名
> username	char	用户名
> Response：
> 
> 同上展示接口
> 
> 回收站视图
> 
> ```python
> url: path("recycling_bin/category/")
> class RecyclingBinCategoryListApi(generics.ListAPIView)
> 	def list():
>         output_slz = CategoryOutputSerializer
>         ...
>     
> url: path("recycling_bin/<str:object_type>/")
> class RecyclingBinDepartmentListApi(generics.ListAPIView)
> 	def list():
>         output_slz = DepartmentOutputSerializer
>         ...
>     
> url: path("recycling_bin/<str:object_type>/")
> class RecyclingBinProfileListApi(generics.ListAPIView)
> 	def list():
>         output_slz = ProfileOutputSerializer
>         ...
>     
> url: path("recycling_bin/search/category/")
> class RecyclingBinSearchListApi(generics.ListAPIView)
> 	def list():
>         input_slz = CategorySearchSerializer
>         output_slz = CategoryOutputSerializer
>         .....
>         
> url: path("recycling_bin/search/department/")
> class RecyclingBinSearchListApi(generics.ListAPIView)
> 	def list():
>         input_slz = DepartmentSearchSerializer
>         output_slz = DepartmentOutputSerializer
>         .....
>         
> url: path("recycling_bin/search/profile/")
> class RecyclingBinSearchListApi(generics.ListAPIView)
> 	def list():
>         output_slz = ProfileOutputSerializer
>         input_slz = ProfileSearchSerializer
>         .....
> 
>     
> ```

讨论结果，已在原来的方案中进行变更@Canway-shiisa @wklken

**Comment by wklken** [comment]
逻辑:
1. 软删除, 对象状态变更 + 回收站加一条记录  A 谁/什么时间/什么对象    soft_deleted
2. 展示
3. 硬删除 => 标注hard_deleting 异步任务或同步删除后, 直接删除记录 A, 记录审计日志
4. 还原 => 标注 reverting 异步任务或同步还原后, 直接删除记录 A, 记录审计日志

根据上面总结 A 记录的生命周期

1. URL 中  recycling_bin = > recycle_bin 
2. URL 遵循restful   `/api/v1/web/recycle_bin/types/[category | profile | department]`  是一个接口, 支持三种类型
3. id / object_type / object_id / operator / deleted_at
4. 搜索接口  `/api/v1/web/recycle_bin/search/?type=x&keyword=` keyword到后台再根据类型决定检索什么字段

4. 接口返回
- expires = deleted_at + 删除策略配置的天数
- 原则: 尽量跟各自模块的 detail slz 字段名保持一致, 不要用 from_category / department_relate 之类的
  - 目录: 返回   id + operator +  expires + category基本信息 + profile_count + department_count 
  - 人员: 返回   id + operator +  expires + 人员基本信息
  - 部门: 返回  id + operator +  expires + 部门基本信息(里面有祖先和孩子节点)

**Comment by neronkl** [comment]
1. 记录A生命周期中只有两个状态存在和不存在（被物理删除）。对象移入回收站生成记录A，对象进行还原或者删除操作，都会对记录A硬删除

**Comment by nannan00** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/17491932/219251087-29369812-0711-4d6c-8237-f9f0b2a8cde2.png">
应该是3个接口，这3个接口的输入和返回都不一样，否则会导致一个接口，多输入多输出的情况

搜索接口，应该是上面查询接口，多个输入参数而已

<img width="839" alt="image" src="https://user-images.githubusercontent.com/17491932/219251532-fbc029cb-b423-4ea0-a62e-80a2e5566cb7.png">
应该不需要deleted_at，model应该都会继承TimestampedModel，直接使用 expires = created_at + 删除策略配置的天数

**Comment by neronkl** [comment]
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/17491932/219251087-29369812-0711-4d6c-8237-f9f0b2a8cde2.png">
> 
> 应该是3个接口，这3个接口的输入和返回都不一样，否则会导致一个接口，多输入多输出的情况
> 搜索接口，应该是上面查询接口，多个输入参数而已
> 
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/17491932/219251532-fbc029cb-b423-4ea0-a62e-80a2e5566cb7.png">
> 
> 应该不需要deleted_at，model应该都会继承TimestampedModel，直接使用 expires = created_at + 删除策略配置的天数

在原方案上，根据建议已经进行修改 @wklken @nannan00
