### ISSUE TITLE
蓝鲸6.1.2ldap同步失败，无法获取到用户信息

### ISSUE THREAD

**Issue by CloudVapour** [TencentBlueKing/bk-user#915]
简述：
同步时在详细日志中显示组织架构同步成功，用户信息无数据，但同步结果为失败，用户目录中也没有显示。
![ILI01L5WAWM(SIHW$OS SMV](https://user-images.githubusercontent.com/58024039/217987275-2e5fbc9e-9d48-437c-a84e-ac9f0126c901.png)
![Z)XCO}PLP6NYUO){BO 430H](https://user-images.githubusercontent.com/58024039/217987297-9404dad3-b7fd-40ed-b6ba-fb66bcb86ce5.png)

填写信息如下：
![1](https://user-images.githubusercontent.com/58024039/217986747-ac204930-8c5b-4c2f-a65f-af40b4d73ab5.png)
![2](https://user-images.githubusercontent.com/58024039/217986759-8afc0030-62bf-44f7-955b-987f184f1715.png)
![3](https://user-images.githubusercontent.com/58024039/217986761-877199cf-df9e-46b9-aaa6-7cab0ee1af4d.png)

![企业微信截图_16759969108151](https://user-images.githubusercontent.com/58024039/217986870-d5452090-6e77-4bb2-8433-f2cd0b69d3c6.png)

**Comment by wklken** [comment]
最后的日志没截全, 需要补充下; 堆栈里是具体 db 报错的原因

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/issues/429

**Comment by CloudVapour** [comment]
> 最后的日志没截全, 需要补充下;堆栈里是具体 db 报错的原因

日志补充：
![企业微信截图_16759987911256](https://user-images.githubusercontent.com/58024039/217991413-7b5b2b1e-6357-4a9a-9a6b-1e96a495c9de.png)

**Comment by CloudVapour** [comment]
> 最后的日志没截全, 需要补充下;堆栈里是具体 db 报错的原因

显示主键重复需要如何解决

**Comment by wklken** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/2002216/217991745-e6b5b8b4-2e4e-421d-8203-d76fc270d052.png">

目前部门的`code`是全局唯一的, 在 db 中有唯一性约束(目前取的是数据源中的 部门层级, 例如 BJIT, BJIT/ITC等

所以, 当多个目录配置同一个数据源, 或者数据源中存在相同的组织架构, 就会导致后面加入的同步失败

具体原因及解决方案: https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1128778024

**Comment by CloudVapour** [comment]
> <img alt="image" width="411" src="https://user-images.githubusercontent.com/2002216/217991745-e6b5b8b4-2e4e-421d-8203-d76fc270d052.png">
> 
> 目前部门的`code`是全局唯一的, 在 db 中有唯一性约束(目前取的是数据源中的 部门层级, 例如 BJIT, BJIT/ITC等
> 
> 所以, 当多个目录配置同一个数据源, 或者数据源中存在相同的组织架构, 就会导致后面加入的同步失败
> 
> 具体原因及解决方案: [#429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1128778024)

您好，想详细了解下解决方案中数据库硬删除方式如何实现，大概是由过去
DELETE categories_profilecategory WHERE id=x；时有其他目录数据源没有清除干净导致

**Comment by CloudVapour** [comment]
> <img alt="image" width="411" src="https://user-images.githubusercontent.com/2002216/217991745-e6b5b8b4-2e4e-421d-8203-d76fc270d052.png">
> 
> 目前部门的`code`是全局唯一的, 在 db 中有唯一性约束(目前取的是数据源中的 部门层级, 例如 BJIT, BJIT/ITC等
> 
> 所以, 当多个目录配置同一个数据源, 或者数据源中存在相同的组织架构, 就会导致后面加入的同步失败
> 
> 具体原因及解决方案: [#429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1128778024)

数据库中之前删除的目录对影响的话，可以通过如何调整数据库解决吗，或者是否有方式完全重置用户信息，重新推送用户数据

**Comment by wklken** [comment]
相关sql参考: https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1277301610

谨慎操作, 建议操作前在测试环境验证, 并且备份数据库

**Comment by CloudVapour** [comment]
> 相关sql参考: [#429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1277301610)
> 
> 谨慎操作, 建议操作前在测试环境验证, 并且备份数据库

按照您提供的方式，组织同步已经成功，但是没有成功拉取用户信息
![企业微信截图_167600071342](https://user-images.githubusercontent.com/58024039/217995554-39782e2b-deca-460a-aa58-5d4edfe37b3e.png)

**Comment by wklken** [comment]
1. 获取同步日志, 看下里面的profile同步日志中打印的信息, 可能是无法关联部门等原因
2. https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1367801346 根据category_id查下相关关系表是否有数据

**Comment by CloudVapour** [comment]
> 1. 获取同步日志, 看下里面的profile同步日志中打印的信息, 可能是无法关联部门等原因
> 2. [[文档] ldap 配置/使用/FAQ 汇总 #429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1367801346) 根据category_id查下相关关系表是否有数据

同步日志中未看到相关错误信息，在相关关系表中通过category_id查询 profiles_profile表中数据为空。
![企业微信截图_16760077293112](https://user-images.githubusercontent.com/58024039/218011774-3426077f-73ae-42bb-9916-7e79eca6c18e.png)
![企业微信截图_16760076714086](https://user-images.githubusercontent.com/58024039/218011775-a7792634-4a50-4795-92a4-a53d499673f4.png)

![企业微信截图_16760083768048](https://user-images.githubusercontent.com/58024039/218012144-f05ceefa-40a3-481b-814c-69ca930f5eb5.png)

**Comment by CloudVapour** [comment]
> 1. 获取同步日志, 看下里面的profile同步日志中打印的信息, 可能是无法关联部门等原因
> 2. [[文档] ldap 配置/使用/FAQ 汇总 #429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1367801346) 根据category_id查下相关关系表是否有数据

worker日志中有以下报错
![企业微信截图_16760091567886](https://user-images.githubusercontent.com/58024039/218015380-ffa6068a-270c-4a4c-8676-b81f8e47a451.png)

**Comment by wklken** [comment]
![企业微信截图_16760077293112](https://user-images.githubusercontent.com/58024039/218011774-3426077f-73ae-42bb-9916-7e79eca6c18e.png)

这张图的日志信息代表, 从数据源没有拉到任何用户信息

-------

最后这个
错误堆栈复制全 => 把日志前后一起放上来(有敏感信息的话替换掉)

**Comment by CloudVapour** [comment]
> ![企业微信截图_16760077293112](https://user-images.githubusercontent.com/58024039/218011774-3426077f-73ae-42bb-9916-7e79eca6c18e.png)
> 
> 这张图的日志信息代表, 从数据源没有拉到任何用户信息
> 
> 最后这个 错误堆栈复制全 => 把日志前后一起放上来(有敏感信息的话替换掉)

多谢，该问题已经解决，用户可以同步，是用户没有同步是默认过滤条件导致修改为了(&(|(objectclass=user)(objectclass=person)(objectclass=inetOrgPerson) (objectclass=organizationalPerson))(!(objectclass=computer)))，但目前ldap上的部分用户是中文字符，有哪些解决方法

**Comment by CloudVapour** [comment]
> > ![企业微信截图_16760077293112](https://user-images.githubusercontent.com/58024039/218011774-3426077f-73ae-42bb-9916-7e79eca6c18e.png)
> > 这张图的日志信息代表, 从数据源没有拉到任何用户信息
> > 最后这个 错误堆栈复制全 => 把日志前后一起放上来(有敏感信息的话替换掉)
> 
> 多谢，该问题已经解决，用户可以同步，是用户没有同步是默认过滤条件导致修改为了(&(|(objectclass=user)(objectclass=person)(objectclass=inetOrgPerson) (objectclass=organizationalPerson))(!(objectclass=computer)))，但目前ldap上的部分用户是中文字符，有哪些解决方法

已解决属性需要修改为
![企业微信截图_16760113871234](https://user-images.githubusercontent.com/58024039/218021944-d3135389-35f1-491d-8c18-df9fd2d42975.png)
