### ISSUE TITLE
用户管理Ldap同步到的用户无法登录

### ISSUE THREAD

**Issue by CloudVapour** [TencentBlueKing/bk-user#921]
蓝鲸6.1.2  用户管理版本2.4.2
使用LDAP同步到的用户登录提示用户名密码错误：
api错误日志：
ERROR [2023-02-12 22:57:26] 753 login 7464 140539906963784
login check, check profile<wxxxua> of username=wxxxua, domain=xxx.com.cn in category<ldap-CGR-9> failed
Traceback (most recent call last):
  File "/data/bkce/usermgr/api/bkuser_core/profiles/v2/views.py", line 745, in login
  File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/login.py", line 60, in check
bkuser_core.categories.plugins.ldap.exceptions.FetchUserMetaInfoFailed: 获取用户基本信息失败
INFO [2023-02-12 23:01:59] 110 _http_request 11844 140539879075144
重启用户管理，paas平台均无法解决。

**Comment by CloudVapour** [comment]
**补充LDAP配置信息：**
用户对象类：inetOrgPerson
用户对象过滤：(&(|(objectclass=user)(objectclass=person)(objectclass=inetOrgPerson) (objectclass=organizationalPerson))(!(objectclass=computer)))
组织架构类：organizationalUnit
**蓝鲸用户管理字段**
用户名：sAMAccountName
中文名：displayName
邮箱：mail
手机号：mobile

连接和推送均无问题，但实际无法登录

**Comment by wklken** [comment]
确认下是不是这个问题: https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1125627101

**Comment by CloudVapour** [comment]
已经核实过，日志中也已经显示通过域去访问，包括登录审计日志中账号状态为正常，但提示密码错误，其间也尝试过通过邮箱，用户名@域名 为账号均无法正常访问

**Comment by CloudVapour** [comment]
> 确认下是不是这个问题: [#429 (comment)](https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1125627101)

已经核实过，日志中也已经显示通过域去访问，包括导出登录审计日志中账号状态为正常，但提示密码错误，其间也尝试过通过邮箱，用户名@域名 为账号均无法正常访问

**Comment by CloudVapour** [comment]
> ```python
>     @staticmethod
>     def fetch_username(field_fetcher, user_info: dict) -> str:
>         return force_str(field_fetcher.get_value(field_name="username", user_meta=user_info["raw_attributes"]))
> 
>     @staticmethod
>     def fetch_dn(user_info: dict) -> str:
>         return force_str(user_info["raw_attributes"]["entryDN"][0])
>    
> #============================================
> 
>     def check(self, profile, password):
>         users = client.search(
>             object_class=config_loader["user_class"],
>             attributes=field_fetcher.get_user_attributes(),
>         )
>         logger.debug("search results users: %s", users)
>         target_dn = None
>         for user in users:
>             if not user.get("raw_attributes"):
>                 logger.debug("user %s has no raw_attributes, skip", user)
>                 continue
> 
>             if self.fetch_username(field_fetcher, user) == profile.username:
>                 target_dn = self.fetch_dn(user)
> 
>         if not target_dn:
>             raise FetchUserMetaInfoFailed("获取用户基本信息失败")
> ```
> 
> 目前应该是能连通到ldap的
> 
> 登录逻辑是 `username@域`登录, 解析得到`username`之后, 请求ldap获取用户信息
> 
> 但是从ldap无法获取到用户的 `raw_attributes` 或者 `raw_attributes.entryDN[0]`, 导致在最后判断失败
> 
> 可以尝试开启debug获取更多的日志
> 
> `bkuser_core/config/overlays/prod.py` 中 `LOG_LEVEL`改成 `"DEBUG"`(注意是字符串, 有引号), 然后重启
> 
> ```
> LOGGING = get_logging(logging_type=LoggingType.STDOUT, log_level=LOG_LEVEL, package_name="bkuser_core")
> ```
> 
> 复现登录失败过程, 拿到登录过程中打的 debug 日志

DEBUG [2023-02-14 10:43:51] 122 process_request 11686 140094817016392
request<bca8d81fcaee4ce49ea09bac097553c9> info: Path(/api/v2/categories/) with QueryString<no_page=True&fields=domain%2Cid%2Cdefault&lookup_field=enabled&exact_lookups=True> via GET from RemoteAddr<10.1.10.53> Agent<python-requests/2.21.0> AcceptLanguage<_MISSING_> Operator<nobody>

DEBUG [2023-02-14 10:43:52] 122 process_request 11689 140094686169416
request<a3c40f42ccab4e42887f533fba88a7d0> info: Path(/api/v1/login/check/) with QueryString<> via POST from RemoteAddr<10.1.10.53> Agent<python-requests/2.21.0> AcceptLanguage<_MISSING_> Operator<nobody>

DEBUG [2023-02-14 10:43:52] 633 login 11689 140094686169416
do login check, username<wuyuhua>, domain=<cgr.com.cn>

DEBUG [2023-02-14 10:43:52] 647 login 11689 140094686169416
do login check, will check in category<ldap-CGR-9>

DEBUG [2023-02-14 10:43:55] 41 check 11689 140094686169416
going to search users, object_class: inetOrgPerson, attributes: ['sAMAccountName', 'displayName', 'mail', 'mobile']

INFO [2023-02-14 10:43:55] 106 search 11689 140094686169416
going to search (objectClass=inetOrgPerson) from OU=ITC,OU=BJIT,DC=cgr,DC=com,DC=cn

DEBUG [2023-02-14 10:43:55] 47 check 11689 140094686169416
search results users: []

ERROR [2023-02-14 10:43:55] 753 login 11689 140094686169416
login check, check profile<wuyuhua> of username=wuyuhua, domain=cgr.com.cn in category<ldap-CGR-9> failed
Traceback (most recent call last):
 File "/data/bkce/usermgr/api/bkuser_core/profiles/v2/views.py", line 745, in login
  File "/data/bkce/usermgr/api/bkuser_core/categories/plugins/ldap/login.py", line 60, in check
bkuser_core.categories.plugins.ldap.exceptions.FetchUserMetaInfoFailed: 获取用户基本信息失败

debug日志如上

**Comment by wklken** [comment]
对应代码的位置


https://github.com/TencentBlueKing/bk-user/blob/73e0dd1238dc454bda427e8e732271b0fea79018/src/api/bkuser_core/categories/plugins/ldap/login.py#L38-L47

```
DEBUG [2023-02-14 10:43:52] 633 login 11689 140094686169416
do login check, username=<用户名>, domain=<cgr.com.cn>

DEBUG [2023-02-14 10:43:52] 647 login 11689 140094686169416
do login check, will check in category

DEBUG [2023-02-14 10:43:55] 41 check 11689 140094686169416
going to search users, object_class: inetOrgPerson, attributes: ['sAMAccountName', 'displayName', 'mail', 'mobile']

INFO [2023-02-14 10:43:55] 106 search 11689 140094686169416
going to search (objectClass=inetOrgPerson) from OU=ITC,OU=BJIT,DC=cgr,DC=com,DC=cn

DEBUG [2023-02-14 10:43:55] 47 check 11689 140094686169416
search results users: []
```

意味着, 调用ldap client向ldap 服务器发起查询没有命中用户

查询条件:
- start root: OU=ITC,OU=BJIT,DC=cgr,DC=com,DC=cn
- object_class: inetOrgPerson
- attributes: ['sAMAccountName', 'displayName', 'mail', 'mobile']

ldap没有报错并且正常返回了, 返回结果是`[]`

> search inetOrgPerson where sAMAccountName=用户名 or displayName=用户名 or mail=用户名 or mobile=用户名

------------

上面日志中的`username=<用户名>`是贴日志的时候手工去掉了? 
用户管理调用 ldap 流程没有报错
两个可能原因:
1. 按照这个查询条件, ldap的确没有数据
2. ldap 对应查询接口做了什么处理, 不支持上面这种查询条件
3. 配置在用户管理的ldap配置有问题, 导致构造的查询条件有问题

依赖的ldap3库, 可以写脚本验证确认问题 https://github.com/TencentBlueKing/bk-user/blob/v2.4.2/src/api/bkuser_core/categories/plugins/ldap/client.py#L17

其他:
- 参考社区论坛 https://bk.tencent.com/s-mart/community/question/1901  确认下是mad还是ldap, ldap的用户名应该是`cn`? 可以验证下
- 这个issue https://github.com/TencentBlueKing/bk-user/issues/429  中有一些目前已经遇到过的问题供参考

**Comment by wklken** [comment]
有确认原因吗? @CloudVapour
