### ISSUE TITLE
同步AD用户后，在权限中心同步组织架构提示主键重复

### ISSUE THREAD

**Issue by CloudVapour** [TencentBlueKing/bk-user#923]
版本6.1.2 用户管理版本2.4.2 权限中心版本1.8.24
有删除过数据库之前的用户数据。重新同步AD域后显示主键重复，请问需要如何解决。
权限中心日志：
![Z0$44D9~Q5342Z))I 6HA6D](https://user-images.githubusercontent.com/58024039/218948941-5d5e5dc0-05a2-4e11-bc39-755b7ed91106.png)

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/issues/429#issuecomment-1167117436

确认为什么会有重复主键, 如果是之前手工操作导致的, 删干净使得不会出现重复主键就行
