### ISSUE TITLE
【优化】用户入职状态变更为离职应该限制登录使用

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#929]
**存在的问题**
目前用户变更入职状态为离职的时候不会同步变更enbaled字段，这就使得离职状态下用户还能进行正常登录及其他一系列操作

**重现方法**
点击用户 -> 进行编辑 -> 将用户的`在职状态`字段变更为`离职` -> 使用该用户进行登录测试及其他用户管理相关操作
![image](https://user-images.githubusercontent.com/90179140/220566739-81ebb65e-b0c8-48db-a681-0697a4983fc8.png)

**理想行为**
离职状态的用户不应该能正常登录及进行用户管理的其他操作

**版本**
当前最新版仍旧存在该问题

**额外信息**
处理：前端可以在该字段更新为离职的时候 同步变更enabled字段为0
- 相关接口：
![image](https://user-images.githubusercontent.com/90179140/220567964-8677c717-19c2-46fe-8c1f-62324b3a8395.png)

![image](https://user-images.githubusercontent.com/90179140/220568171-d1068890-619b-4c5c-b39b-362aead603fd.png)

**Comment by Canway-shiisa** [comment]
1. 这里同步修改enabled可能会影响到用户展示列表，enabled=0的部分默认就不展示了：
![image](https://user-images.githubusercontent.com/90179140/221082634-bad9595a-3fa3-4dd0-b4bc-1490170d25f8.png)
2. 如果变成1.中的展示逻辑，那搜索框中支持`在职状态`就没有意义了：
![image](https://user-images.githubusercontent.com/90179140/221082844-0c6d9945-87fc-4f35-bfba-f16131369bb9.png)
3. 综上，是否不进行enabled的同步变更，而是同步变成`账号状态`字段为禁用=》即status=DISABLED

**Comment by wklken** [comment]
登录的检测逻辑直接多加一条状态必须在职? 如果离职直接禁止登录

其他地方的逻辑不变

**Comment by nannan00** [comment]
> 登录的检测逻辑直接多加一条状态必须在职? 如果离职直接禁止登录
> 
> 其他地方的逻辑不变

+1

用户管理只关注数据自身，不应该关注数据被用于什么场景，然后需要联合变更其他数据

离职不能登录，这个是登录的场景，应该是 登录消费用户管理的数据，即登录时，判断用户的离职状态

需要调整登录的逻辑，支持判断离职状态并提醒具体登录失败原因

**Comment by Canway-shiisa** [comment]
v2.5.3中实现：登录校验用户在职状态，离职用户限制登录
