### ISSUE TITLE
esb接口 retrieve_user 接口参数具有误导性

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#944]
**用文字描述你遇到的问题**

id参数容易误导使用者认为是仅仅常规id
![image](https://user-images.githubusercontent.com/49228807/226302052-42077f74-8219-4d19-a25d-ded10cb4ea81.png)

**重现方法**

![image](https://user-images.githubusercontent.com/49228807/226302692-2b1ea915-96a1-4fd8-a661-91461385ce55.png)
![image](https://user-images.githubusercontent.com/49228807/226302895-eb36a332-32ff-465b-b41d-c676cf9aad31.png)

**预期行为**

无

**版本**
- 提供用户管理的具体版本号
- 是否是企业版问题？

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by nannan00** [comment]
esb文档里，对于ID的描述已经说明不是普通ID了，而是根据lookup_field来确定的，可能是username，也可能是id，所以不存在误导
