### ISSUE TITLE
【BUG】ldap/mad目录配置拉取周期不生效

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#956]
**用文字描述你遇到的问题**
ldap/mad目录配置拉取周期，Saas页面保存成功，配置不生效。原本为拉取周期为0的目录，配置为60的目录。对应表PeriodTask 中无相应定时任务注册

**重现方法**

配置拉取周期为0的ldap/mad目录，然后更新拉取周期。观察PeriodTask是否更新对应目录的同步任务记录。

**预期行为**

同步周期变更

**版本**
- 2.5.2

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by neronkl** [comment]
https://github.com/TencentBlueKing/bk-user/blob/705515df50c5d233f182d642d0344cc6b6093eae/src/api/bkuser_core/api/web/category/views.py#L187
上面的逻辑，导致下面逻辑无法执行，导致信号机制无法触发=>同步任务无法更新
https://github.com/TencentBlueKing/bk-user/blob/705515df50c5d233f182d642d0344cc6b6093eae/src/api/bkuser_core/api/web/category/views.py#L199

**Comment by nannan00** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/17491932/231107163-d9cd6b3f-e64e-43d2-8f83-b9a5b529a49a.png">


最后return需要查询所有的，因为包括了新建的

all_db_settings = Setting.objects.filter(meta__in=metas, category_id=category_id).all()
return Response(self.get_serializer_class()(all_db_settings, many=True).data)

**Comment by Canway-shiisa** [comment]
v2.5.4支持
