### ISSUE TITLE
mad/ldap类型目录进行停用目录操作，其定时同步任务仍在执行

### ISSUE THREAD

**Issue by neronkl** [TencentBlueKing/bk-user#960]
**用文字描述你遇到的问题**

mad/ldap类型目录进行停用目录操作，其定时同步任务仍在执行

**重现方法**

新建一个ldap/mad目录，配置同步周期。停用目录，观察beat日志，

**预期行为**

mad/ldap类型目录进行停用目录操作后，同时无效化其定时同步任务
重新启用的时候，周期任务恢复

**版本**
- 提供用户管理的具体版本号：
2.5.2
- 是否是企业版问题？
否

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by nannan00** [comment]
已确认是bug，对于停用和启用，需要进行周期任务的删除和添加

**Comment by neronkl** [comment]
目录进行停用/启用的状态变更，传入参数：activated。
1. PeriodTask 有开关字段enabled, 由该字段决定定时同步任务的开启/关闭
2. 根据activated， 决定定时同步任务的enabled字段

**Comment by Canway-shiisa** [comment]
<目录删除>（https://github.com/TencentBlueKing/bk-user/issues/901）的需求也涉及到定时同步任务的关停及启用问题，感觉这块在目录删除这里一并处理掉就可以？
1. 任务暂停可以通过周期任务表PeriodTask 的enabled字段控制
2. 任务删除的话 可以复用原来的任务删除逻辑

**Comment by neronkl** [comment]
> <目录删除>（[https://github.com/TencentBlueKing/bk-user/issues/901）](https://github.com/TencentBlueKing/bk-user/issues/901%EF%BC%89) 的需求也涉及到定时同步任务的关停及启用问题，感觉这块在目录删除这里一并处理掉就可以？
> 
> 1. 任务暂停可以通过周期任务表PeriodTask 的enabled字段控制
> 2. 任务删除的话 可以复用原来的任务删除逻辑 : https://github.com/TencentBlueKing/bk-user/blob/be952b848e18fc0e2255da0e59fc14ebc44e4b6a/src/api/bkuser_core/categories/plugins/utils.py#L66
>    
>    @nannan00

定时任务的删除只是针对目录硬删除阶段

**Comment by nannan00** [comment]
可以，从目前产品设计来看，目录停用后才可以进行目录的删除或还原，

所以目录停用后 定时任务enabled=False

如果重新启用，则enabled=True
如果软删除，即放到回收站，则不变，还是维持enabled=False

进一步：
如果在回收站里硬删除，则删除定时任务
如果还原，是直接还原到停用状态还是直接启用？如果是直接启用，则需要变更定时任务enabled=True

**Comment by Canway-shiisa** [comment]
在回收站-目录删除中就进行修复
