### ISSUE TITLE
2.2.x升级到2.3以上后，AD定时同步会失效

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#971]
**异常描述**
用户管理2.2.x升级到2.3以上后，AD定时同步会失效

**初步定位**
由于开源后项目路径从bkuser变更到bkuser_core，但是定时任务表中的任务路径还是维持原有的bkuser
![image](https://user-images.githubusercontent.com/90179140/234530857-83fc2d6e-f162-423c-9c8d-5af1bb0e717a.png)
**版本**
当前只要是从2.2.x版本升级到2.3.x或更高版本的环境都存在该问题

**临时方案**
运维手段进行数据库层面处理

**Comment by Xmandon** [comment]
在部署方案里增加sql支持

**Comment by Canway-shiisa** [comment]
部署脚本增加SQL变更修复：
use bk_user;
UPDATE django_celery_beat_periodictask SET task=REPLACE(task, 'bkuser', 'bkuser_core');

**Comment by nannan00** [comment]
> 部署脚本增加SQL变更修复： use bk_user; UPDATE django_celery_beat_periodictask SET task=REPLACE(task, 'bkuser', 'bkuser_core');

需要考虑重复执行问题，应该将 'bkuser.' 一起包括了，这样重复执行才不会有问题

**Comment by Canway-shiisa** [comment]
> > 部署脚本增加SQL变更修复： use bk_user; UPDATE django_celery_beat_periodictask SET task=REPLACE(task, 'bkuser', 'bkuser_core');
> 
> 需要考虑重复执行问题，应该将 'bkuser.' 一起包括了，这样重复执行才不会有问题

已更新到原方案评论中
